In [ ]:
!pip install pennylane==0.33 pennylane-qiskit==0.33 qiskit qiskit-ibm-provider

Requirement already satisfied: pennylane==0.33 in /usr/local/lib/python3.11/dist-packages (0.33.0)
Requirement already satisfied: pennylane-qiskit==0.33 in /usr/local/lib/python3.11/dist-packages (0.33.0)
Requirement already satisfied: qiskit in /usr/local/lib/python3.11/dist-packages (1.4.2)
Requirement already satisfied: qiskit-ibm-provider in /usr/local/lib/python3.11/dist-packages (0.11.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (1.14.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (3.4.2)
Requirement already satisfied: rustworkx in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (0.16.0)
Requirement already satisfied: autograd in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (1.7.0)
Requirement already satisfied: toml in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (0.10.2)
Requirement already satisfied: appdirs in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (1.4.4)
Requirement already satisfied: semantic-version>=2.7 in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (2.10.0)
Requirement already satisfied: autoray>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (0.7.1)
Requirement already satisfied: cachetools in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (5.5.2)
Requirement already satisfied: pennylane-lightning>=0.33 in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (0.34.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (2.32.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from pennylane==0.33) (4.12.2)
Requirement already satisfied: qiskit-aer in /usr/local/lib/python3.11/dist-packages (from pennylane-qiskit==0.33) (0.17.0)
Requirement already satisfied: qiskit-ibm-runtime in /usr/local/lib/python3.11/dist-packages (from pennylane-qiskit==0.33) (0.37.0)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.11/dist-packages (from qiskit) (1.13.1)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.11/dist-packages (from qiskit) (0.3.9)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from qiskit) (2.8.2)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from qiskit) (5.4.1)
Requirement already satisfied: symengine<0.14,>=0.11 in /usr/local/lib/python3.11/dist-packages (from qiskit) (0.13.0)
Requirement already satisfied: requests-ntlm>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider) (1.3.0)
Requirement already satisfied: urllib3>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider) (2.3.0)
Requirement already satisfied: websocket-client>=1.5.1 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider) (1.8.0)
Requirement already satisfied: websockets>=10.0 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider) (15.0.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.0->qiskit) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->pennylane==0.33) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->pennylane==0.33) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->pennylane==0.33) (2025.1.31)
Requirement already satisfied: cryptography>=1.3 in /usr/local/lib/python3.11/dist-packages (from requests-ntlm>=1.1.0->qiskit-ibm-provider) (43.0.3)
Requirement already satisfied: pyspnego>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from requests-ntlm>=1.1.0->qiskit-ibm-provider) (0.11.2)
Requirement already satisfied: pbr>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from stevedore>=3.0.0->qiskit) (6.1.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy>=1.3->qiskit) (1.3.0)
Requirement already satisfied: psutil>=5 in /usr/local/lib/python3.11/dist-packages (from qiskit-aer->pennylane-qiskit==0.33) (5.9.5)
Requirement already satisfied: ibm-platform-services>=0.22.6 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-runtime->pennylane-qiskit==0.33) (0.63.0)
Requirement already satisfied: pydantic<2.10,>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-runtime->pennylane-qiskit==0.33) (2.9.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-runtime->pennylane-qiskit==0.33) (24.2)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibm-provider) (1.17.1)
Requirement already satisfied: ibm_cloud_sdk_core<4.0.0,>=3.22.1 in /usr/local/lib/python3.11/dist-packages (from ibm-platform-services>=0.22.6->qiskit-ibm-runtime->pennylane-qiskit==0.33) (3.23.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from pbr>=2.0.0->stevedore>=3.0.0->qiskit) (75.1.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.10,>=2.5.0->qiskit-ibm-runtime->pennylane-qiskit==0.33) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.10,>=2.5.0->qiskit-ibm-runtime->pennylane-qiskit==0.33) (2.23.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibm-provider) (2.22)
Requirement already satisfied: PyJWT<3.0.0,>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from ibm_cloud_sdk_core<4.0.0,>=3.22.1->ibm-platform-services>=0.22.6->qiskit-ibm-runtime->pennylane-qiskit==0.33) (2.10.1)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# 📌 Load Data
df = pd.read_csv("/content/drive/MyDrive/QML/parkinson_gait/final_parkinsons_for_the_love_of_god.csv")

df.head()

,Unnamed: 0,Gait_Cycle_Percent,Left_Ankle_Ankle_Dorsi_Plantarflexion_PF_DF,Left_Hip_Hip_Flexion_Extension_EXT_FLX,Left_Knee_Knee_Flx_Extension_EXT_FLX,Right_Ankle_Ankle_Dorsi_Plantarflexion_PF_DF,Right_Hip_Hip_Flexion_Extension_EXT_FLX,Right_Knee_Knee_Flx_Extension_EXT_FLX,Subject_ID,label,...,Left_Knee_Ang_Knee_Flx_Extension_Variability,Right_Ankle_Ang_Ankle_Dorsi_Plantarflexion_Variability,Right_Hip_Ang_Hip_Flexion_Extension_Variability,Right_Knee_Ang_Knee_Flx_Extension_Variability,Left_Ankle_Ang_Ankle_Dorsi_Plantarflexion_Acceleration,Left_Hip_Ang_Hip_Flexion_Extension_Acceleration,Left_Knee_Ang_Knee_Flx_Extension_Acceleration,Right_Ankle_Ang_Ankle_Dorsi_Plantarflexion_Acceleration,Right_Hip_Ang_Hip_Flexion_Extension_Acceleration,Right_Knee_Ang_Knee_Flx_Extension_Acceleration
0,0,1,-2.37648,34.02794,16.14490,1.87055,33.60558,11.36783,SUB01_1,1,...,18.945746,7.692659,15.308019,18.810668,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
1,1,2,-1.87879,33.60433,16.86324,0.98626,33.50635,11.34289,SUB01_1,1,...,18.945746,7.692659,15.308019,18.810668,0.49769,-0.42361,0.71834,-0.88429,-0.09923,-0.02494
2,2,3,-1.15549,33.26338,17.86806,0.16397,33.50398,11.92080,SUB01_1,1,...,18.945746,7.692659,15.308019,18.810668,0.72330,-0.34095,1.00482,-0.82229,-0.00237,0.57791
3,3,4,-0.21892,33.00112,19.09299,-0.47002,33.58014,13.01924,SUB01_1,1,...,18.945746,7.692659,15.308019,18.810668,0.93657,-0.26226,1.22493,-0.63399,0.07616,1.09844
4,4,5,0.88757,32.78223,20.42713,-0.80742,33.70621,14.51952,SUB01_1,1,...,18.945746,7.692659,15.308019,18.810668,1.10649,-0.21889,1.33414,-0.33740,0.12607,1.50028

# Step 1: Quantum Feature Extraction

In [ ]:
from google.colab import userdata
QIBM_API_KEY = userdata.get('QIBM_API_KEY')

In [ ]:
from qiskit_ibm_provider import IBMProvider

IBMProvider.save_account(QIBM_API_KEY, overwrite=True)
provider = IBMProvider()

In [ ]:
from qiskit_ibm_provider import least_busy

backend = least_busy(
    provider.backends(
        simulator=False,
        min_num_qubits=4,
        operational=True,
        dynamic_reprate_enabled=True
    )
)

print(f"Running on backend: {backend.name}")

Running on backend: ibm_sherbrooke

In [ ]:
from qiskit.primitives import Sampler
from qiskit import QuantumCircuit

# Define quantum circuit
num_qubits = 3
features = np.random.uniform(0, np.pi, num_qubits)

qc = QuantumCircuit(num_qubits, num_qubits)

for i in range(num_qubits):
    qc.ry(features[i], i)

for i in range(num_qubits - 1):
    qc.cx(i, i + 1)
qc.cx(num_qubits - 1, 0)

# ✅ Explicitly map qubit i → classical bit i
qc.measure(range(num_qubits), range(num_qubits))

sampler = Sampler()
job = sampler.run([qc])
result = job.result()

print("Quantum output:", result.quasi_dists[0])

Quantum output: {0: np.float64(0.431097250921165), 1: np.float64(0.106352209668219), 2: np.float64(0.007315577337737), 3: np.float64(0.005187449260214), 4: np.float64(0.003059756499286), 5: np.float64(0.012402681800834), 6: np.float64(0.180307384425602), 7: np.float64(0.254277690086943)}

<ipython-input-26-3e425b53d8ea>:20: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()

In [ ]:
def quantum_feature_vector(features, backend_name="ibm_kyiv", num_qubits=5):
    from qiskit_ibm_provider import IBMProvider
    from qiskit.primitives import Sampler
    from qiskit import QuantumCircuit
    import numpy as np

    provider = IBMProvider()
    qc = QuantumCircuit(num_qubits, num_qubits)

    for i in range(num_qubits):
        qc.ry(features[i], i)

    for i in range(num_qubits - 1):
        qc.cx(i, i + 1)
    qc.cx(num_qubits - 1, 0)

    qc.measure(range(num_qubits), range(num_qubits))

    sampler = Sampler()
    job = sampler.run([qc])
    result = job.result()

    vec = [float(result.quasi_dists[0].get(i, 0.0)) for i in range(2 ** num_qubits)]
    return vec

In [ ]:
import hashlib
import json
import os

# --- CONFIG ---
CACHE_FILE = "/content/drive/MyDrive/QML/parkinson_gait/quantum_cache_parkinson_windowed.json"
num_qubits = 5

# --- Hashing utility ---
def hash_input(arr):
    return hashlib.md5(np.round(arr, 6).tobytes()).hexdigest()

# --- Load existing cache ---
if os.path.exists(CACHE_FILE):
    with open(CACHE_FILE, "r") as f:
        cache = json.load(f)
else:
    cache = {}

# --- Safe quantum feature wrapper ---
def cached_quantum_feature_vector(features):
    key = hash_input(features)
    if key in cache:
        return cache[key]

    try:
        vec = quantum_feature_vector(features, num_qubits=num_qubits)
        cache[key] = vec

        # Save after each success
        with open(CACHE_FILE, "w") as f:
            json.dump(cache, f)

        print(f"✅ Processed: {key}")
        return vec

    except Exception as e:
        print(f"❌ Error on input {key}: {e}")
        return [0.0] * (2 ** num_qubits)  # placeholder if fail

# Step 2: Apply Quantum Encoding to Entire Dataset

In [ ]:
def extract_quantum_features_deduplicated(
    df,
    gait_features,
    quantum_feature_fn,
    num_qubits=5,
    cache_file="/content/drive/MyDrive/QML/parkinson_gait/quantum_cache.json",
    save_every=10,
    output_csv="/content/drive/MyDrive/QML/parkinson_gait/parkinsons_features_quantum_hardware.csv"
):
    import numpy as np
    import pandas as pd
    import os
    import json
    import hashlib
    from tqdm import tqdm

    # Step 1: Round + deduplicate
    X_classical = df[gait_features].values
    X_classical_rounded = np.round(X_classical, 6)
    X_unique, idx_unique, idx_inverse = np.unique(
        X_classical_rounded, axis=0, return_index=True, return_inverse=True
    )

    print(f"🔍 Unique samples: {len(X_unique)} / {len(X_classical)} total")

    # Step 2: Load or initialize cache
    if os.path.exists(cache_file):
        with open(cache_file, "r") as f:
            cache = json.load(f)
    else:
        cache = {}

    # Step 3: Hashing function
    def hash_input(arr):
        return hashlib.md5(np.round(arr, 6).tobytes()).hexdigest()

    # Step 4: Safe call with cache
    def cached_quantum_call(features):
        key = hash_input(features)
        if key in cache:
            return cache[key]
        try:
            vec = quantum_feature_fn(features)
            cache[key] = vec
            with open(cache_file, "w") as f:
                json.dump(cache, f)
            return vec
        except Exception as e:
            print(f"❌ Error processing {key}: {e}")
            return [0.0] * (2 ** num_qubits)

    # Step 5: Extract features with incremental saving
    X_quantum_unique = []
    for i, x in enumerate(tqdm(X_unique)):
        X_quantum_unique.append(cached_quantum_call(x))

        # Save progress every N samples
        if (i + 1) % save_every == 0 or (i + 1) == len(X_unique):
            print(f"💾 Saving progress at sample {i + 1}")
            processed_mask = np.isin(idx_inverse, range(i + 1))

            # Reconstruct partial quantum features
            partial_full = np.array(X_quantum_unique)[idx_inverse[processed_mask]]

            partial_df = pd.DataFrame(
                partial_full,
                columns=[f"Quantum_Feature_{j}" for j in range(2 ** num_qubits)]
            )
            partial_df["label"] = df["label"].values[processed_mask]
            partial_df["Subject_ID"] = df["Subject_ID"].values[processed_mask]

            # Save it
            partial_df.to_csv(output_csv, index=False)

    # Step 6: Reconstruct full dataset
    X_quantum_full = np.array(X_quantum_unique)[idx_inverse]

    # Step 7: Final DataFrame
    df_quantum = pd.DataFrame(
        X_quantum_full,
        columns=[f"Quantum_Feature_{i}" for i in range(2 ** num_qubits)]
    )
    df_quantum["label"] = df["label"].values
    df_quantum["Subject_ID"] = df["Subject_ID"].values

    # Final save
    df_quantum.to_csv(output_csv, index=False)
    print(f"✅ Final full CSV saved: {output_csv}")

    return df_quantum

In [ ]:
X_classical = df.drop(columns=["label", "Subject_ID", "Gait_Cycle_Percent", "Unnamed: 0"], errors="ignore")

gait_features = X_classical.columns.tolist()

In [ ]:
gait_features

['Left_Ankle_Ankle_Dorsi_Plantarflexion_PF_DF',
 'Left_Hip_Hip_Flexion_Extension_EXT_FLX',
 'Left_Knee_Knee_Flx_Extension_EXT_FLX',
 'Right_Ankle_Ankle_Dorsi_Plantarflexion_PF_DF',
 'Right_Hip_Hip_Flexion_Extension_EXT_FLX',
 'Right_Knee_Knee_Flx_Extension_EXT_FLX',
 'Left_Ankle_Ang_Ankle_Dorsi_Plantarflexion_Variability',
 'Left_Hip_Ang_Hip_Flexion_Extension_Variability',
 'Left_Knee_Ang_Knee_Flx_Extension_Variability',
 'Right_Ankle_Ang_Ankle_Dorsi_Plantarflexion_Variability',
 'Right_Hip_Ang_Hip_Flexion_Extension_Variability',
 'Right_Knee_Ang_Knee_Flx_Extension_Variability',
 'Left_Ankle_Ang_Ankle_Dorsi_Plantarflexion_Acceleration',
 'Left_Hip_Ang_Hip_Flexion_Extension_Acceleration',
 'Left_Knee_Ang_Knee_Flx_Extension_Acceleration',
 'Right_Ankle_Ang_Ankle_Dorsi_Plantarflexion_Acceleration',
 'Right_Hip_Ang_Hip_Flexion_Extension_Acceleration',
 'Right_Knee_Ang_Knee_Flx_Extension_Acceleration']

In [ ]:
df_quantum = extract_quantum_features_deduplicated(
    df=df,
    gait_features=gait_features,
    quantum_feature_fn=quantum_feature_vector,
    num_qubits=5,
    cache_file="/content/drive/MyDrive/QML/parkinson_gait/quantum_cache.json",
    save_every=10,
    output_csv="/content/drive/MyDrive/QML/parkinson_gait/parkinsons_features_quantum_hardware_please.csv"
)

🔍 Unique samples: 4848 / 4848 total

  0%|          | 0/4848 [00:00<?, ?it/s]<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  0%|          | 10/4848 [00:33<4:34:18,  3.40s/it]

💾 Saving progress at sample 10

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  0%|          | 20/4848 [01:04<4:16:30,  3.19s/it]

💾 Saving progress at sample 20

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  1%|          | 30/4848 [01:38<4:34:20,  3.42s/it]

💾 Saving progress at sample 30

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  1%|          | 40/4848 [02:14<4:30:54,  3.38s/it]

💾 Saving progress at sample 40

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  1%|          | 50/4848 [02:45<4:15:11,  3.19s/it]

💾 Saving progress at sample 50

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  1%|          | 60/4848 [03:17<4:10:42,  3.14s/it]

💾 Saving progress at sample 60

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  1%|▏         | 70/4848 [03:48<4:09:42,  3.14s/it]

💾 Saving progress at sample 70

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  2%|▏         | 80/4848 [04:19<4:03:54,  3.07s/it]

💾 Saving progress at sample 80

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  2%|▏         | 90/4848 [04:50<4:11:21,  3.17s/it]

💾 Saving progress at sample 90

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  2%|▏         | 100/4848 [05:21<3:58:59,  3.02s/it]

💾 Saving progress at sample 100

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  2%|▏         | 110/4848 [05:52<4:01:17,  3.06s/it]

💾 Saving progress at sample 110

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  2%|▏         | 120/4848 [06:21<3:51:58,  2.94s/it]

💾 Saving progress at sample 120

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  3%|▎         | 130/4848 [06:52<3:56:55,  3.01s/it]

💾 Saving progress at sample 130

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  3%|▎         | 140/4848 [07:23<4:00:05,  3.06s/it]

💾 Saving progress at sample 140

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  3%|▎         | 150/4848 [07:54<4:00:15,  3.07s/it]

💾 Saving progress at sample 150

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  3%|▎         | 160/4848 [08:24<4:00:12,  3.07s/it]

💾 Saving progress at sample 160

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  4%|▎         | 170/4848 [08:55<4:02:00,  3.10s/it]

💾 Saving progress at sample 170

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  4%|▎         | 180/4848 [09:25<3:50:00,  2.96s/it]

💾 Saving progress at sample 180

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  4%|▍         | 190/4848 [09:56<3:59:16,  3.08s/it]

💾 Saving progress at sample 190

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  4%|▍         | 200/4848 [10:28<4:03:25,  3.14s/it]

💾 Saving progress at sample 200

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  4%|▍         | 210/4848 [10:59<4:00:06,  3.11s/it]

💾 Saving progress at sample 210

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  5%|▍         | 220/4848 [11:29<3:53:10,  3.02s/it]

💾 Saving progress at sample 220

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  5%|▍         | 230/4848 [11:59<3:56:08,  3.07s/it]

💾 Saving progress at sample 230

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  5%|▍         | 240/4848 [12:30<3:50:17,  3.00s/it]

💾 Saving progress at sample 240

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  5%|▌         | 250/4848 [13:03<4:03:54,  3.18s/it]

💾 Saving progress at sample 250

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  5%|▌         | 260/4848 [13:37<4:17:59,  3.37s/it]

💾 Saving progress at sample 260

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  6%|▌         | 270/4848 [14:07<3:53:49,  3.06s/it]

💾 Saving progress at sample 270

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  6%|▌         | 280/4848 [14:38<3:54:14,  3.08s/it]

💾 Saving progress at sample 280

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  6%|▌         | 290/4848 [15:11<3:55:47,  3.10s/it]

💾 Saving progress at sample 290

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  6%|▌         | 300/4848 [15:41<3:45:49,  2.98s/it]

💾 Saving progress at sample 300

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  6%|▋         | 310/4848 [16:11<3:45:34,  2.98s/it]

💾 Saving progress at sample 310

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  7%|▋         | 320/4848 [16:42<3:54:10,  3.10s/it]

💾 Saving progress at sample 320

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  7%|▋         | 330/4848 [17:12<3:49:37,  3.05s/it]

💾 Saving progress at sample 330

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  7%|▋         | 340/4848 [17:42<3:48:37,  3.04s/it]

💾 Saving progress at sample 340

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  7%|▋         | 350/4848 [18:13<3:51:34,  3.09s/it]

💾 Saving progress at sample 350

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  7%|▋         | 360/4848 [18:44<3:51:07,  3.09s/it]

💾 Saving progress at sample 360

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  8%|▊         | 370/4848 [19:15<3:44:17,  3.01s/it]

💾 Saving progress at sample 370

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  8%|▊         | 380/4848 [19:45<3:42:14,  2.98s/it]

💾 Saving progress at sample 380

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  8%|▊         | 390/4848 [20:16<3:46:48,  3.05s/it]

💾 Saving progress at sample 390

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  8%|▊         | 400/4848 [20:46<3:48:00,  3.08s/it]

💾 Saving progress at sample 400

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  8%|▊         | 410/4848 [21:16<3:38:29,  2.95s/it]

💾 Saving progress at sample 410

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  9%|▊         | 420/4848 [21:46<3:42:11,  3.01s/it]

💾 Saving progress at sample 420

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  9%|▉         | 430/4848 [22:17<3:47:49,  3.09s/it]

💾 Saving progress at sample 430

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  9%|▉         | 440/4848 [22:47<3:42:50,  3.03s/it]

💾 Saving progress at sample 440

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  9%|▉         | 450/4848 [23:18<3:40:50,  3.01s/it]

💾 Saving progress at sample 450

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
  9%|▉         | 460/4848 [23:48<3:44:34,  3.07s/it]

💾 Saving progress at sample 460

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 10%|▉         | 470/4848 [24:19<3:59:58,  3.29s/it]

💾 Saving progress at sample 470

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 10%|▉         | 480/4848 [24:51<3:59:03,  3.28s/it]

💾 Saving progress at sample 480

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 10%|█         | 490/4848 [25:23<3:40:57,  3.04s/it]

💾 Saving progress at sample 490

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 10%|█         | 500/4848 [25:53<3:36:09,  2.98s/it]

💾 Saving progress at sample 500

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 11%|█         | 510/4848 [26:25<3:54:08,  3.24s/it]

💾 Saving progress at sample 510

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 11%|█         | 520/4848 [26:55<3:36:41,  3.00s/it]

💾 Saving progress at sample 520

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 11%|█         | 530/4848 [27:26<3:41:51,  3.08s/it]

💾 Saving progress at sample 530

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 11%|█         | 540/4848 [27:56<3:41:36,  3.09s/it]

💾 Saving progress at sample 540

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 11%|█▏        | 550/4848 [28:27<3:41:21,  3.09s/it]

💾 Saving progress at sample 550

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 12%|█▏        | 560/4848 [28:58<3:38:53,  3.06s/it]

💾 Saving progress at sample 560

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 12%|█▏        | 570/4848 [29:28<3:36:04,  3.03s/it]

💾 Saving progress at sample 570

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 12%|█▏        | 580/4848 [29:59<3:35:22,  3.03s/it]

💾 Saving progress at sample 580

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 12%|█▏        | 590/4848 [30:30<3:37:24,  3.06s/it]

💾 Saving progress at sample 590

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 12%|█▏        | 600/4848 [31:00<3:35:14,  3.04s/it]

💾 Saving progress at sample 600

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 13%|█▎        | 610/4848 [31:30<3:29:11,  2.96s/it]

💾 Saving progress at sample 610

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 13%|█▎        | 620/4848 [32:00<3:29:22,  2.97s/it]

💾 Saving progress at sample 620

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 13%|█▎        | 630/4848 [32:30<3:36:33,  3.08s/it]

💾 Saving progress at sample 630

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 13%|█▎        | 640/4848 [33:00<3:33:53,  3.05s/it]

💾 Saving progress at sample 640

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 13%|█▎        | 650/4848 [33:30<3:28:59,  2.99s/it]

💾 Saving progress at sample 650

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 14%|█▎        | 660/4848 [34:01<3:34:14,  3.07s/it]

💾 Saving progress at sample 660

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 14%|█▍        | 670/4848 [34:33<3:37:09,  3.12s/it]

💾 Saving progress at sample 670

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 14%|█▍        | 680/4848 [35:03<3:27:58,  2.99s/it]

💾 Saving progress at sample 680

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 14%|█▍        | 690/4848 [35:33<3:28:34,  3.01s/it]

💾 Saving progress at sample 690

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 14%|█▍        | 700/4848 [36:06<3:34:55,  3.11s/it]

💾 Saving progress at sample 700

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 15%|█▍        | 710/4848 [36:39<3:48:38,  3.32s/it]

💾 Saving progress at sample 710

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 15%|█▍        | 720/4848 [37:09<3:23:28,  2.96s/it]

💾 Saving progress at sample 720

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 15%|█▌        | 730/4848 [37:40<3:37:57,  3.18s/it]

💾 Saving progress at sample 730

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 15%|█▌        | 740/4848 [38:10<3:28:51,  3.05s/it]

💾 Saving progress at sample 740

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 15%|█▌        | 750/4848 [38:40<3:24:15,  2.99s/it]

💾 Saving progress at sample 750

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 16%|█▌        | 760/4848 [39:11<3:29:06,  3.07s/it]

💾 Saving progress at sample 760

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 16%|█▌        | 770/4848 [39:41<3:23:02,  2.99s/it]

💾 Saving progress at sample 770

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 16%|█▌        | 780/4848 [40:10<3:26:01,  3.04s/it]

💾 Saving progress at sample 780

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 16%|█▋        | 790/4848 [40:41<3:24:04,  3.02s/it]

💾 Saving progress at sample 790

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 17%|█▋        | 800/4848 [41:12<3:27:31,  3.08s/it]

💾 Saving progress at sample 800

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 17%|█▋        | 810/4848 [41:42<3:20:29,  2.98s/it]

💾 Saving progress at sample 810

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 17%|█▋        | 820/4848 [42:12<3:20:21,  2.98s/it]

💾 Saving progress at sample 820

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 17%|█▋        | 830/4848 [42:42<3:20:19,  2.99s/it]

💾 Saving progress at sample 830

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 17%|█▋        | 840/4848 [43:12<3:19:28,  2.99s/it]

💾 Saving progress at sample 840

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 18%|█▊        | 850/4848 [43:43<3:21:50,  3.03s/it]

💾 Saving progress at sample 850

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 18%|█▊        | 860/4848 [44:13<3:24:06,  3.07s/it]

💾 Saving progress at sample 860

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 18%|█▊        | 870/4848 [44:44<3:21:49,  3.04s/it]

💾 Saving progress at sample 870

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 18%|█▊        | 880/4848 [45:14<3:22:27,  3.06s/it]

💾 Saving progress at sample 880

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 18%|█▊        | 890/4848 [45:44<3:18:02,  3.00s/it]

💾 Saving progress at sample 890

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 19%|█▊        | 900/4848 [46:15<3:25:12,  3.12s/it]

💾 Saving progress at sample 900

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 19%|█▉        | 910/4848 [46:46<3:21:50,  3.08s/it]

💾 Saving progress at sample 910

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 19%|█▉        | 920/4848 [47:17<3:15:57,  2.99s/it]

💾 Saving progress at sample 920

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 19%|█▉        | 930/4848 [47:53<4:03:41,  3.73s/it]

💾 Saving progress at sample 930

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 19%|█▉        | 940/4848 [48:27<3:26:09,  3.17s/it]

💾 Saving progress at sample 940

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 20%|█▉        | 950/4848 [48:57<3:19:10,  3.07s/it]

💾 Saving progress at sample 950

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 20%|█▉        | 960/4848 [49:28<3:19:40,  3.08s/it]

💾 Saving progress at sample 960

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 20%|██        | 970/4848 [49:59<3:19:52,  3.09s/it]

💾 Saving progress at sample 970

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 20%|██        | 980/4848 [50:28<3:10:13,  2.95s/it]

💾 Saving progress at sample 980

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 20%|██        | 990/4848 [50:59<3:11:37,  2.98s/it]

💾 Saving progress at sample 990

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 21%|██        | 1000/4848 [51:29<3:12:55,  3.01s/it]

💾 Saving progress at sample 1000

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 21%|██        | 1010/4848 [52:00<3:15:18,  3.05s/it]

💾 Saving progress at sample 1010

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 21%|██        | 1020/4848 [52:31<3:19:31,  3.13s/it]

💾 Saving progress at sample 1020

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 21%|██        | 1030/4848 [53:01<3:11:06,  3.00s/it]

💾 Saving progress at sample 1030

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 21%|██▏       | 1040/4848 [53:32<3:14:09,  3.06s/it]

💾 Saving progress at sample 1040

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 22%|██▏       | 1050/4848 [54:02<3:13:44,  3.06s/it]

💾 Saving progress at sample 1050

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 22%|██▏       | 1060/4848 [54:32<3:08:04,  2.98s/it]

💾 Saving progress at sample 1060

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 22%|██▏       | 1070/4848 [55:03<3:18:02,  3.15s/it]

💾 Saving progress at sample 1070

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 22%|██▏       | 1080/4848 [55:33<3:09:08,  3.01s/it]

💾 Saving progress at sample 1080

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 22%|██▏       | 1090/4848 [56:04<3:06:51,  2.98s/it]

💾 Saving progress at sample 1090

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 23%|██▎       | 1100/4848 [56:34<3:11:05,  3.06s/it]

💾 Saving progress at sample 1100

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 23%|██▎       | 1110/4848 [57:05<3:08:01,  3.02s/it]

💾 Saving progress at sample 1110

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 23%|██▎       | 1120/4848 [57:35<3:06:22,  3.00s/it]

💾 Saving progress at sample 1120

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 23%|██▎       | 1130/4848 [58:05<3:06:37,  3.01s/it]

💾 Saving progress at sample 1130

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 24%|██▎       | 1140/4848 [58:35<3:05:32,  3.00s/it]

💾 Saving progress at sample 1140

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 24%|██▎       | 1150/4848 [59:08<3:18:46,  3.23s/it]

💾 Saving progress at sample 1150

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 24%|██▍       | 1160/4848 [59:41<3:15:13,  3.18s/it]

💾 Saving progress at sample 1160

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 24%|██▍       | 1170/4848 [1:00:12<3:15:46,  3.19s/it]

💾 Saving progress at sample 1170

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 24%|██▍       | 1180/4848 [1:00:42<3:05:25,  3.03s/it]

💾 Saving progress at sample 1180

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 25%|██▍       | 1190/4848 [1:01:13<3:06:01,  3.05s/it]

💾 Saving progress at sample 1190

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 25%|██▍       | 1200/4848 [1:01:43<3:05:12,  3.05s/it]

💾 Saving progress at sample 1200

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 25%|██▍       | 1210/4848 [1:02:14<3:03:17,  3.02s/it]

💾 Saving progress at sample 1210

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 25%|██▌       | 1220/4848 [1:02:45<3:01:16,  3.00s/it]

💾 Saving progress at sample 1220

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 25%|██▌       | 1230/4848 [1:03:15<3:05:54,  3.08s/it]

💾 Saving progress at sample 1230

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 26%|██▌       | 1240/4848 [1:03:46<3:00:52,  3.01s/it]

💾 Saving progress at sample 1240

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 26%|██▌       | 1250/4848 [1:04:17<3:00:14,  3.01s/it]

💾 Saving progress at sample 1250

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 26%|██▌       | 1260/4848 [1:04:47<3:01:22,  3.03s/it]

💾 Saving progress at sample 1260

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 26%|██▌       | 1270/4848 [1:05:17<2:58:30,  2.99s/it]

💾 Saving progress at sample 1270

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 26%|██▋       | 1280/4848 [1:05:48<3:03:01,  3.08s/it]

💾 Saving progress at sample 1280

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 27%|██▋       | 1290/4848 [1:06:19<3:05:16,  3.12s/it]

💾 Saving progress at sample 1290

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 27%|██▋       | 1300/4848 [1:06:49<3:01:10,  3.06s/it]

💾 Saving progress at sample 1300

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 27%|██▋       | 1310/4848 [1:07:20<3:00:34,  3.06s/it]

💾 Saving progress at sample 1310

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 27%|██▋       | 1320/4848 [1:07:49<2:56:50,  3.01s/it]

💾 Saving progress at sample 1320

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 27%|██▋       | 1330/4848 [1:08:20<2:59:25,  3.06s/it]

💾 Saving progress at sample 1330

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 28%|██▊       | 1340/4848 [1:08:50<2:55:24,  3.00s/it]

💾 Saving progress at sample 1340

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 28%|██▊       | 1350/4848 [1:09:21<3:02:43,  3.13s/it]

💾 Saving progress at sample 1350

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 28%|██▊       | 1360/4848 [1:09:52<2:54:12,  3.00s/it]

💾 Saving progress at sample 1360

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 28%|██▊       | 1370/4848 [1:10:24<3:19:59,  3.45s/it]

💾 Saving progress at sample 1370

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 28%|██▊       | 1380/4848 [1:10:58<3:10:59,  3.30s/it]

💾 Saving progress at sample 1380

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 29%|██▊       | 1390/4848 [1:11:32<3:02:12,  3.16s/it]

💾 Saving progress at sample 1390

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 29%|██▉       | 1400/4848 [1:12:03<2:55:55,  3.06s/it]

💾 Saving progress at sample 1400

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 29%|██▉       | 1410/4848 [1:12:33<2:52:52,  3.02s/it]

💾 Saving progress at sample 1410

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 29%|██▉       | 1420/4848 [1:13:04<2:59:23,  3.14s/it]

💾 Saving progress at sample 1420

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 29%|██▉       | 1430/4848 [1:13:35<2:54:53,  3.07s/it]

💾 Saving progress at sample 1430

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 30%|██▉       | 1440/4848 [1:14:06<2:55:31,  3.09s/it]

💾 Saving progress at sample 1440

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 30%|██▉       | 1450/4848 [1:14:36<2:53:16,  3.06s/it]

💾 Saving progress at sample 1450

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 30%|███       | 1460/4848 [1:15:07<2:53:58,  3.08s/it]

💾 Saving progress at sample 1460

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 30%|███       | 1470/4848 [1:15:38<2:54:32,  3.10s/it]

💾 Saving progress at sample 1470

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 31%|███       | 1480/4848 [1:16:09<2:57:38,  3.16s/it]

💾 Saving progress at sample 1480

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 31%|███       | 1490/4848 [1:16:39<2:50:01,  3.04s/it]

💾 Saving progress at sample 1490

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 31%|███       | 1500/4848 [1:17:11<3:04:16,  3.30s/it]

💾 Saving progress at sample 1500

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 31%|███       | 1510/4848 [1:17:42<2:48:17,  3.03s/it]

💾 Saving progress at sample 1510

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 31%|███▏      | 1520/4848 [1:18:12<2:49:47,  3.06s/it]

💾 Saving progress at sample 1520

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 32%|███▏      | 1530/4848 [1:18:43<2:47:29,  3.03s/it]

💾 Saving progress at sample 1530

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 32%|███▏      | 1540/4848 [1:19:13<2:51:40,  3.11s/it]

💾 Saving progress at sample 1540

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 32%|███▏      | 1550/4848 [1:19:44<2:47:42,  3.05s/it]

💾 Saving progress at sample 1550

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 32%|███▏      | 1560/4848 [1:20:15<2:57:00,  3.23s/it]

💾 Saving progress at sample 1560

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 32%|███▏      | 1570/4848 [1:20:47<2:53:03,  3.17s/it]

💾 Saving progress at sample 1570

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 33%|███▎      | 1580/4848 [1:21:18<2:49:47,  3.12s/it]

💾 Saving progress at sample 1580

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 33%|███▎      | 1590/4848 [1:21:48<2:46:00,  3.06s/it]

💾 Saving progress at sample 1590

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 33%|███▎      | 1600/4848 [1:22:22<3:10:22,  3.52s/it]

💾 Saving progress at sample 1600

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 33%|███▎      | 1610/4848 [1:22:55<2:52:23,  3.19s/it]

💾 Saving progress at sample 1610

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 33%|███▎      | 1620/4848 [1:23:27<2:49:28,  3.15s/it]

💾 Saving progress at sample 1620

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 34%|███▎      | 1630/4848 [1:23:57<2:41:33,  3.01s/it]

💾 Saving progress at sample 1630

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 34%|███▍      | 1640/4848 [1:24:28<2:43:25,  3.06s/it]

💾 Saving progress at sample 1640

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 34%|███▍      | 1650/4848 [1:24:58<2:40:54,  3.02s/it]

💾 Saving progress at sample 1650

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 34%|███▍      | 1660/4848 [1:25:29<2:43:22,  3.07s/it]

💾 Saving progress at sample 1660

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 34%|███▍      | 1670/4848 [1:26:00<2:43:40,  3.09s/it]

💾 Saving progress at sample 1670

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 35%|███▍      | 1680/4848 [1:26:30<2:43:51,  3.10s/it]

💾 Saving progress at sample 1680

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 35%|███▍      | 1690/4848 [1:27:01<2:40:01,  3.04s/it]

💾 Saving progress at sample 1690

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 35%|███▌      | 1700/4848 [1:27:32<2:48:35,  3.21s/it]

💾 Saving progress at sample 1700

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 35%|███▌      | 1710/4848 [1:28:03<2:41:40,  3.09s/it]

💾 Saving progress at sample 1710

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 35%|███▌      | 1720/4848 [1:28:33<2:37:55,  3.03s/it]

💾 Saving progress at sample 1720

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 36%|███▌      | 1730/4848 [1:29:04<2:37:37,  3.03s/it]

💾 Saving progress at sample 1730

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 36%|███▌      | 1740/4848 [1:29:35<2:40:36,  3.10s/it]

💾 Saving progress at sample 1740

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 36%|███▌      | 1750/4848 [1:30:06<2:38:32,  3.07s/it]

💾 Saving progress at sample 1750

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 36%|███▋      | 1760/4848 [1:30:37<2:40:26,  3.12s/it]

💾 Saving progress at sample 1760

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 37%|███▋      | 1770/4848 [1:31:08<2:38:19,  3.09s/it]

💾 Saving progress at sample 1770

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 37%|███▋      | 1780/4848 [1:31:39<2:40:30,  3.14s/it]

💾 Saving progress at sample 1780

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 37%|███▋      | 1790/4848 [1:32:10<2:38:51,  3.12s/it]

💾 Saving progress at sample 1790

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 37%|███▋      | 1800/4848 [1:32:41<2:35:31,  3.06s/it]

💾 Saving progress at sample 1800

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 37%|███▋      | 1810/4848 [1:33:12<2:34:25,  3.05s/it]

💾 Saving progress at sample 1810

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 38%|███▊      | 1820/4848 [1:33:45<2:42:06,  3.21s/it]

💾 Saving progress at sample 1820

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 38%|███▊      | 1830/4848 [1:34:18<2:40:51,  3.20s/it]

💾 Saving progress at sample 1830

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 38%|███▊      | 1840/4848 [1:34:50<2:39:02,  3.17s/it]

💾 Saving progress at sample 1840

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 38%|███▊      | 1850/4848 [1:35:20<2:30:09,  3.01s/it]

💾 Saving progress at sample 1850

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 38%|███▊      | 1860/4848 [1:35:51<2:31:58,  3.05s/it]

💾 Saving progress at sample 1860

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 39%|███▊      | 1870/4848 [1:36:22<2:34:33,  3.11s/it]

💾 Saving progress at sample 1870

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 39%|███▉      | 1880/4848 [1:36:53<2:31:23,  3.06s/it]

💾 Saving progress at sample 1880

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 39%|███▉      | 1890/4848 [1:37:23<2:31:32,  3.07s/it]

💾 Saving progress at sample 1890

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 39%|███▉      | 1900/4848 [1:37:55<2:35:10,  3.16s/it]

💾 Saving progress at sample 1900

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 39%|███▉      | 1910/4848 [1:38:25<2:27:55,  3.02s/it]

💾 Saving progress at sample 1910

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 40%|███▉      | 1920/4848 [1:38:57<2:30:05,  3.08s/it]

💾 Saving progress at sample 1920

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 40%|███▉      | 1930/4848 [1:39:28<2:39:36,  3.28s/it]

💾 Saving progress at sample 1930

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 40%|████      | 1940/4848 [1:39:59<2:29:03,  3.08s/it]

💾 Saving progress at sample 1940

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 40%|████      | 1950/4848 [1:40:30<2:27:50,  3.06s/it]

💾 Saving progress at sample 1950

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 40%|████      | 1960/4848 [1:41:01<2:32:29,  3.17s/it]

💾 Saving progress at sample 1960

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 41%|████      | 1970/4848 [1:41:32<2:29:36,  3.12s/it]

💾 Saving progress at sample 1970

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 41%|████      | 1980/4848 [1:42:05<2:31:13,  3.16s/it]

💾 Saving progress at sample 1980

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 41%|████      | 1990/4848 [1:42:37<2:42:06,  3.40s/it]

💾 Saving progress at sample 1990

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 41%|████▏     | 2000/4848 [1:43:08<2:29:17,  3.15s/it]

💾 Saving progress at sample 2000

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 41%|████▏     | 2010/4848 [1:43:40<2:32:41,  3.23s/it]

💾 Saving progress at sample 2010

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 42%|████▏     | 2020/4848 [1:44:12<2:30:19,  3.19s/it]

💾 Saving progress at sample 2020

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 42%|████▏     | 2030/4848 [1:44:42<2:28:26,  3.16s/it]

💾 Saving progress at sample 2030

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 42%|████▏     | 2040/4848 [1:45:16<2:43:01,  3.48s/it]

💾 Saving progress at sample 2040

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 42%|████▏     | 2050/4848 [1:45:51<2:40:39,  3.45s/it]

💾 Saving progress at sample 2050

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 42%|████▏     | 2060/4848 [1:46:22<2:29:34,  3.22s/it]

💾 Saving progress at sample 2060

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 43%|████▎     | 2070/4848 [1:46:53<2:25:03,  3.13s/it]

💾 Saving progress at sample 2070

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 43%|████▎     | 2080/4848 [1:47:24<2:22:44,  3.09s/it]

💾 Saving progress at sample 2080

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 43%|████▎     | 2090/4848 [1:47:55<2:24:36,  3.15s/it]

💾 Saving progress at sample 2090

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 43%|████▎     | 2100/4848 [1:48:26<2:22:34,  3.11s/it]

💾 Saving progress at sample 2100

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 44%|████▎     | 2110/4848 [1:48:57<2:26:09,  3.20s/it]

💾 Saving progress at sample 2110

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 44%|████▎     | 2120/4848 [1:49:29<2:21:57,  3.12s/it]

💾 Saving progress at sample 2120

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 44%|████▍     | 2130/4848 [1:50:01<2:24:43,  3.19s/it]

💾 Saving progress at sample 2130

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 44%|████▍     | 2140/4848 [1:50:31<2:20:35,  3.12s/it]

💾 Saving progress at sample 2140

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 44%|████▍     | 2150/4848 [1:51:03<2:27:10,  3.27s/it]

💾 Saving progress at sample 2150

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 45%|████▍     | 2160/4848 [1:51:36<2:23:43,  3.21s/it]

💾 Saving progress at sample 2160

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 45%|████▍     | 2170/4848 [1:52:09<2:26:10,  3.28s/it]

💾 Saving progress at sample 2170

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 45%|████▍     | 2180/4848 [1:52:40<2:17:48,  3.10s/it]

💾 Saving progress at sample 2180

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 45%|████▌     | 2190/4848 [1:53:11<2:15:17,  3.05s/it]

💾 Saving progress at sample 2190

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 45%|████▌     | 2200/4848 [1:53:42<2:17:35,  3.12s/it]

💾 Saving progress at sample 2200

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 46%|████▌     | 2210/4848 [1:54:13<2:15:56,  3.09s/it]

💾 Saving progress at sample 2210

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 46%|████▌     | 2220/4848 [1:54:44<2:15:43,  3.10s/it]

💾 Saving progress at sample 2220

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 46%|████▌     | 2230/4848 [1:55:16<2:20:17,  3.22s/it]

💾 Saving progress at sample 2230

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 46%|████▌     | 2240/4848 [1:55:47<2:16:05,  3.13s/it]

💾 Saving progress at sample 2240

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 46%|████▋     | 2250/4848 [1:56:19<2:18:51,  3.21s/it]

💾 Saving progress at sample 2250

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 47%|████▋     | 2260/4848 [1:56:52<2:29:14,  3.46s/it]

💾 Saving progress at sample 2260

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 47%|████▋     | 2270/4848 [1:57:27<2:31:05,  3.52s/it]

💾 Saving progress at sample 2270

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 47%|████▋     | 2280/4848 [1:57:59<2:18:53,  3.24s/it]

💾 Saving progress at sample 2280

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 47%|████▋     | 2290/4848 [1:58:30<2:12:12,  3.10s/it]

💾 Saving progress at sample 2290

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 47%|████▋     | 2300/4848 [1:59:01<2:17:03,  3.23s/it]

💾 Saving progress at sample 2300

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 48%|████▊     | 2310/4848 [1:59:33<2:12:42,  3.14s/it]

💾 Saving progress at sample 2310

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 48%|████▊     | 2320/4848 [2:00:03<2:09:07,  3.06s/it]

💾 Saving progress at sample 2320

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 48%|████▊     | 2330/4848 [2:00:33<2:08:59,  3.07s/it]

💾 Saving progress at sample 2330

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 48%|████▊     | 2340/4848 [2:01:05<2:15:13,  3.23s/it]

💾 Saving progress at sample 2340

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 48%|████▊     | 2350/4848 [2:01:36<2:10:31,  3.14s/it]

💾 Saving progress at sample 2350

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 49%|████▊     | 2360/4848 [2:02:07<2:14:17,  3.24s/it]

💾 Saving progress at sample 2360

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 49%|████▉     | 2370/4848 [2:02:38<2:08:28,  3.11s/it]

💾 Saving progress at sample 2370

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 49%|████▉     | 2380/4848 [2:03:09<2:10:51,  3.18s/it]

💾 Saving progress at sample 2380

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 49%|████▉     | 2390/4848 [2:03:39<2:06:18,  3.08s/it]

💾 Saving progress at sample 2390

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 50%|████▉     | 2400/4848 [2:04:11<2:10:20,  3.19s/it]

💾 Saving progress at sample 2400

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 50%|████▉     | 2410/4848 [2:04:41<2:03:39,  3.04s/it]

💾 Saving progress at sample 2410

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 50%|████▉     | 2420/4848 [2:05:12<2:07:57,  3.16s/it]

💾 Saving progress at sample 2420

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 50%|█████     | 2430/4848 [2:05:43<2:05:52,  3.12s/it]

💾 Saving progress at sample 2430

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 50%|█████     | 2440/4848 [2:06:14<2:05:24,  3.12s/it]

💾 Saving progress at sample 2440

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 51%|█████     | 2450/4848 [2:06:45<2:04:50,  3.12s/it]

💾 Saving progress at sample 2450

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 51%|█████     | 2460/4848 [2:07:16<2:05:58,  3.17s/it]

💾 Saving progress at sample 2460

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 51%|█████     | 2470/4848 [2:07:47<2:03:08,  3.11s/it]

💾 Saving progress at sample 2470

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 51%|█████     | 2480/4848 [2:08:20<2:18:30,  3.51s/it]

💾 Saving progress at sample 2480

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 51%|█████▏    | 2490/4848 [2:08:53<2:10:18,  3.32s/it]

💾 Saving progress at sample 2490

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 52%|█████▏    | 2500/4848 [2:09:26<2:03:49,  3.16s/it]

💾 Saving progress at sample 2500

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 52%|█████▏    | 2510/4848 [2:09:56<2:00:53,  3.10s/it]

💾 Saving progress at sample 2510

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 52%|█████▏    | 2520/4848 [2:10:28<2:03:13,  3.18s/it]

💾 Saving progress at sample 2520

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 52%|█████▏    | 2530/4848 [2:10:58<1:58:51,  3.08s/it]

💾 Saving progress at sample 2530

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 52%|█████▏    | 2540/4848 [2:11:30<2:01:15,  3.15s/it]

💾 Saving progress at sample 2540

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 53%|█████▎    | 2550/4848 [2:12:00<1:55:57,  3.03s/it]

💾 Saving progress at sample 2550

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 53%|█████▎    | 2560/4848 [2:12:31<1:59:48,  3.14s/it]

💾 Saving progress at sample 2560

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 53%|█████▎    | 2570/4848 [2:13:01<1:56:41,  3.07s/it]

💾 Saving progress at sample 2570

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 53%|█████▎    | 2580/4848 [2:13:33<1:59:52,  3.17s/it]

💾 Saving progress at sample 2580

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 53%|█████▎    | 2590/4848 [2:14:03<1:54:00,  3.03s/it]

💾 Saving progress at sample 2590

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 54%|█████▎    | 2600/4848 [2:14:34<1:57:22,  3.13s/it]

💾 Saving progress at sample 2600

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 54%|█████▍    | 2610/4848 [2:15:05<1:55:44,  3.10s/it]

💾 Saving progress at sample 2610

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 54%|█████▍    | 2620/4848 [2:15:37<1:58:29,  3.19s/it]

💾 Saving progress at sample 2620

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 54%|█████▍    | 2630/4848 [2:16:08<1:54:53,  3.11s/it]

💾 Saving progress at sample 2630

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 54%|█████▍    | 2640/4848 [2:16:39<1:54:57,  3.12s/it]

💾 Saving progress at sample 2640

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 55%|█████▍    | 2650/4848 [2:17:10<1:54:08,  3.12s/it]

💾 Saving progress at sample 2650

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 55%|█████▍    | 2660/4848 [2:17:41<1:56:37,  3.20s/it]

💾 Saving progress at sample 2660

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 55%|█████▌    | 2670/4848 [2:18:11<1:52:00,  3.09s/it]

💾 Saving progress at sample 2670

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 55%|█████▌    | 2680/4848 [2:18:43<1:54:50,  3.18s/it]

💾 Saving progress at sample 2680

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 55%|█████▌    | 2690/4848 [2:19:14<1:50:41,  3.08s/it]

💾 Saving progress at sample 2690

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 56%|█████▌    | 2700/4848 [2:19:45<1:50:27,  3.09s/it]

💾 Saving progress at sample 2700

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 56%|█████▌    | 2710/4848 [2:20:21<2:10:10,  3.65s/it]

💾 Saving progress at sample 2710

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 56%|█████▌    | 2720/4848 [2:20:55<1:56:24,  3.28s/it]

💾 Saving progress at sample 2720

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 56%|█████▋    | 2730/4848 [2:21:25<1:48:44,  3.08s/it]

💾 Saving progress at sample 2730

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 57%|█████▋    | 2740/4848 [2:21:57<1:50:03,  3.13s/it]

💾 Saving progress at sample 2740

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 57%|█████▋    | 2750/4848 [2:22:27<1:49:55,  3.14s/it]

💾 Saving progress at sample 2750

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 57%|█████▋    | 2760/4848 [2:22:58<1:47:10,  3.08s/it]

💾 Saving progress at sample 2760

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 57%|█████▋    | 2770/4848 [2:23:28<1:44:55,  3.03s/it]

💾 Saving progress at sample 2770

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 57%|█████▋    | 2780/4848 [2:23:59<1:45:28,  3.06s/it]

💾 Saving progress at sample 2780

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 58%|█████▊    | 2790/4848 [2:24:30<1:45:23,  3.07s/it]

💾 Saving progress at sample 2790

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 58%|█████▊    | 2800/4848 [2:25:00<1:46:13,  3.11s/it]

💾 Saving progress at sample 2800

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 58%|█████▊    | 2810/4848 [2:25:31<1:45:55,  3.12s/it]

💾 Saving progress at sample 2810

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 58%|█████▊    | 2820/4848 [2:26:02<1:42:47,  3.04s/it]

💾 Saving progress at sample 2820

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 58%|█████▊    | 2830/4848 [2:26:33<1:43:54,  3.09s/it]

💾 Saving progress at sample 2830

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 59%|█████▊    | 2840/4848 [2:27:04<1:42:01,  3.05s/it]

💾 Saving progress at sample 2840

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 59%|█████▉    | 2850/4848 [2:27:35<1:46:38,  3.20s/it]

💾 Saving progress at sample 2850

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 59%|█████▉    | 2860/4848 [2:28:07<1:45:04,  3.17s/it]

💾 Saving progress at sample 2860

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 59%|█████▉    | 2870/4848 [2:28:38<1:41:22,  3.07s/it]

💾 Saving progress at sample 2870

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 59%|█████▉    | 2880/4848 [2:29:09<1:43:42,  3.16s/it]

💾 Saving progress at sample 2880

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 60%|█████▉    | 2890/4848 [2:29:40<1:44:17,  3.20s/it]

💾 Saving progress at sample 2890

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 60%|█████▉    | 2900/4848 [2:30:12<1:39:37,  3.07s/it]

💾 Saving progress at sample 2900

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 60%|██████    | 2910/4848 [2:30:43<1:38:31,  3.05s/it]

💾 Saving progress at sample 2910

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 60%|██████    | 2920/4848 [2:31:14<1:41:16,  3.15s/it]

💾 Saving progress at sample 2920

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 60%|██████    | 2930/4848 [2:31:45<1:38:36,  3.08s/it]

💾 Saving progress at sample 2930

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 61%|██████    | 2940/4848 [2:32:17<1:46:08,  3.34s/it]

💾 Saving progress at sample 2940

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 61%|██████    | 2950/4848 [2:32:50<1:45:34,  3.34s/it]

💾 Saving progress at sample 2950

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 61%|██████    | 2960/4848 [2:33:23<1:43:30,  3.29s/it]

💾 Saving progress at sample 2960

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 61%|██████▏   | 2970/4848 [2:33:55<1:42:27,  3.27s/it]

💾 Saving progress at sample 2970

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 61%|██████▏   | 2980/4848 [2:34:26<1:39:10,  3.19s/it]

💾 Saving progress at sample 2980

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 62%|██████▏   | 2990/4848 [2:34:57<1:40:05,  3.23s/it]

💾 Saving progress at sample 2990

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 62%|██████▏   | 3000/4848 [2:35:27<1:37:08,  3.15s/it]

💾 Saving progress at sample 3000

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 62%|██████▏   | 3010/4848 [2:35:59<1:43:21,  3.37s/it]

💾 Saving progress at sample 3010

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 62%|██████▏   | 3020/4848 [2:36:29<1:33:13,  3.06s/it]

💾 Saving progress at sample 3020

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 62%|██████▎   | 3030/4848 [2:37:00<1:37:31,  3.22s/it]

💾 Saving progress at sample 3030

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 63%|██████▎   | 3040/4848 [2:37:30<1:31:57,  3.05s/it]

💾 Saving progress at sample 3040

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 63%|██████▎   | 3050/4848 [2:38:01<1:35:12,  3.18s/it]

💾 Saving progress at sample 3050

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 63%|██████▎   | 3060/4848 [2:38:32<1:33:48,  3.15s/it]

💾 Saving progress at sample 3060

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 63%|██████▎   | 3070/4848 [2:39:04<1:36:06,  3.24s/it]

💾 Saving progress at sample 3070

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 64%|██████▎   | 3080/4848 [2:39:34<1:29:49,  3.05s/it]

💾 Saving progress at sample 3080

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 64%|██████▎   | 3090/4848 [2:40:05<1:36:23,  3.29s/it]

💾 Saving progress at sample 3090

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 64%|██████▍   | 3100/4848 [2:40:35<1:29:18,  3.07s/it]

💾 Saving progress at sample 3100

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 64%|██████▍   | 3110/4848 [2:41:06<1:32:51,  3.21s/it]

💾 Saving progress at sample 3110

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 64%|██████▍   | 3120/4848 [2:41:37<1:28:59,  3.09s/it]

💾 Saving progress at sample 3120

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 65%|██████▍   | 3130/4848 [2:42:09<1:33:03,  3.25s/it]

💾 Saving progress at sample 3130

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 65%|██████▍   | 3140/4848 [2:42:40<1:30:06,  3.17s/it]

💾 Saving progress at sample 3140

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 65%|██████▍   | 3150/4848 [2:43:12<1:32:16,  3.26s/it]

💾 Saving progress at sample 3150

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 65%|██████▌   | 3160/4848 [2:43:43<1:28:29,  3.15s/it]

💾 Saving progress at sample 3160

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 65%|██████▌   | 3170/4848 [2:44:19<1:42:47,  3.68s/it]

💾 Saving progress at sample 3170

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 66%|██████▌   | 3180/4848 [2:44:52<1:29:42,  3.23s/it]

💾 Saving progress at sample 3180

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 66%|██████▌   | 3190/4848 [2:45:23<1:28:35,  3.21s/it]

💾 Saving progress at sample 3190

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 66%|██████▌   | 3200/4848 [2:45:54<1:25:57,  3.13s/it]

💾 Saving progress at sample 3200

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 66%|██████▌   | 3210/4848 [2:46:26<1:25:32,  3.13s/it]

💾 Saving progress at sample 3210

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 66%|██████▋   | 3220/4848 [2:46:56<1:23:42,  3.09s/it]

💾 Saving progress at sample 3220

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 67%|██████▋   | 3230/4848 [2:47:28<1:26:42,  3.22s/it]

💾 Saving progress at sample 3230

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 67%|██████▋   | 3240/4848 [2:48:00<1:27:34,  3.27s/it]

💾 Saving progress at sample 3240

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 67%|██████▋   | 3250/4848 [2:48:32<1:24:13,  3.16s/it]

💾 Saving progress at sample 3250

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 67%|██████▋   | 3260/4848 [2:49:03<1:24:28,  3.19s/it]

💾 Saving progress at sample 3260

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 67%|██████▋   | 3270/4848 [2:49:35<1:22:01,  3.12s/it]

💾 Saving progress at sample 3270

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 68%|██████▊   | 3280/4848 [2:50:07<1:24:39,  3.24s/it]

💾 Saving progress at sample 3280

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 68%|██████▊   | 3290/4848 [2:50:39<1:23:08,  3.20s/it]

💾 Saving progress at sample 3290

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 68%|██████▊   | 3300/4848 [2:51:11<1:22:32,  3.20s/it]

💾 Saving progress at sample 3300

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 68%|██████▊   | 3310/4848 [2:51:43<1:19:16,  3.09s/it]

💾 Saving progress at sample 3310

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 68%|██████▊   | 3320/4848 [2:52:14<1:20:18,  3.15s/it]

💾 Saving progress at sample 3320

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 69%|██████▊   | 3330/4848 [2:52:47<1:24:01,  3.32s/it]

💾 Saving progress at sample 3330

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 69%|██████▉   | 3340/4848 [2:53:19<1:23:59,  3.34s/it]

💾 Saving progress at sample 3340

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 69%|██████▉   | 3350/4848 [2:53:51<1:18:41,  3.15s/it]

💾 Saving progress at sample 3350

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 69%|██████▉   | 3360/4848 [2:54:23<1:21:32,  3.29s/it]

💾 Saving progress at sample 3360

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 70%|██████▉   | 3370/4848 [2:54:54<1:18:04,  3.17s/it]

💾 Saving progress at sample 3370

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 70%|██████▉   | 3380/4848 [2:55:26<1:18:36,  3.21s/it]

💾 Saving progress at sample 3380

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 70%|██████▉   | 3390/4848 [2:55:58<1:16:49,  3.16s/it]

💾 Saving progress at sample 3390

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 70%|███████   | 3400/4848 [2:56:30<1:18:53,  3.27s/it]

💾 Saving progress at sample 3400

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 70%|███████   | 3410/4848 [2:57:02<1:17:53,  3.25s/it]

💾 Saving progress at sample 3410

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 71%|███████   | 3420/4848 [2:57:34<1:16:03,  3.20s/it]

💾 Saving progress at sample 3420

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 71%|███████   | 3430/4848 [2:58:07<1:16:22,  3.23s/it]

💾 Saving progress at sample 3430

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 71%|███████   | 3440/4848 [2:58:43<1:19:57,  3.41s/it]

💾 Saving progress at sample 3440

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 71%|███████   | 3450/4848 [2:59:15<1:14:21,  3.19s/it]

💾 Saving progress at sample 3450

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 71%|███████▏  | 3460/4848 [2:59:46<1:13:40,  3.18s/it]

💾 Saving progress at sample 3460

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 72%|███████▏  | 3470/4848 [3:00:18<1:12:46,  3.17s/it]

💾 Saving progress at sample 3470

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 72%|███████▏  | 3480/4848 [3:00:49<1:11:49,  3.15s/it]

💾 Saving progress at sample 3480

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 72%|███████▏  | 3490/4848 [3:01:21<1:10:42,  3.12s/it]

💾 Saving progress at sample 3490

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 72%|███████▏  | 3500/4848 [3:01:53<1:11:21,  3.18s/it]

💾 Saving progress at sample 3500

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 72%|███████▏  | 3510/4848 [3:02:24<1:11:24,  3.20s/it]

💾 Saving progress at sample 3510

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 73%|███████▎  | 3520/4848 [3:02:56<1:10:40,  3.19s/it]

💾 Saving progress at sample 3520

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 73%|███████▎  | 3530/4848 [3:03:29<1:13:13,  3.33s/it]

💾 Saving progress at sample 3530

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 73%|███████▎  | 3540/4848 [3:04:01<1:12:44,  3.34s/it]

💾 Saving progress at sample 3540

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 73%|███████▎  | 3550/4848 [3:04:35<1:14:04,  3.42s/it]

💾 Saving progress at sample 3550

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 73%|███████▎  | 3560/4848 [3:05:07<1:10:42,  3.29s/it]

💾 Saving progress at sample 3560

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 74%|███████▎  | 3570/4848 [3:05:39<1:08:56,  3.24s/it]

💾 Saving progress at sample 3570

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 74%|███████▍  | 3580/4848 [3:06:11<1:07:33,  3.20s/it]

💾 Saving progress at sample 3580

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 74%|███████▍  | 3590/4848 [3:06:42<1:08:01,  3.24s/it]

💾 Saving progress at sample 3590

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 74%|███████▍  | 3600/4848 [3:07:14<1:06:05,  3.18s/it]

💾 Saving progress at sample 3600

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 74%|███████▍  | 3610/4848 [3:07:45<1:06:15,  3.21s/it]

💾 Saving progress at sample 3610

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 75%|███████▍  | 3620/4848 [3:08:17<1:04:29,  3.15s/it]

💾 Saving progress at sample 3620

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 75%|███████▍  | 3630/4848 [3:08:48<1:03:25,  3.12s/it]

💾 Saving progress at sample 3630

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 75%|███████▌  | 3640/4848 [3:09:19<1:04:20,  3.20s/it]

💾 Saving progress at sample 3640

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 75%|███████▌  | 3650/4848 [3:09:54<1:09:21,  3.47s/it]

💾 Saving progress at sample 3650

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 75%|███████▌  | 3660/4848 [3:10:28<1:05:30,  3.31s/it]

💾 Saving progress at sample 3660

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 76%|███████▌  | 3670/4848 [3:10:59<1:01:18,  3.12s/it]

💾 Saving progress at sample 3670

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 76%|███████▌  | 3680/4848 [3:11:30<1:01:14,  3.15s/it]

💾 Saving progress at sample 3680

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 76%|███████▌  | 3690/4848 [3:12:02<1:01:28,  3.19s/it]

💾 Saving progress at sample 3690

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 76%|███████▋  | 3700/4848 [3:12:34<1:01:15,  3.20s/it]

💾 Saving progress at sample 3700

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 77%|███████▋  | 3710/4848 [3:13:05<59:39,  3.15s/it]

💾 Saving progress at sample 3710

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 77%|███████▋  | 3720/4848 [3:13:38<1:03:21,  3.37s/it]

💾 Saving progress at sample 3720

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 77%|███████▋  | 3730/4848 [3:14:12<1:03:40,  3.42s/it]

💾 Saving progress at sample 3730

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 77%|███████▋  | 3740/4848 [3:14:48<1:06:06,  3.58s/it]

💾 Saving progress at sample 3740

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 77%|███████▋  | 3750/4848 [3:15:22<1:03:30,  3.47s/it]

💾 Saving progress at sample 3750

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 78%|███████▊  | 3760/4848 [3:15:56<1:02:08,  3.43s/it]

💾 Saving progress at sample 3760

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 78%|███████▊  | 3770/4848 [3:16:29<59:18,  3.30s/it]

💾 Saving progress at sample 3770

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 78%|███████▊  | 3780/4848 [3:17:01<58:49,  3.30s/it]

💾 Saving progress at sample 3780

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 78%|███████▊  | 3790/4848 [3:17:33<56:19,  3.19s/it]

💾 Saving progress at sample 3790

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 78%|███████▊  | 3800/4848 [3:18:05<55:18,  3.17s/it]

💾 Saving progress at sample 3800

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 79%|███████▊  | 3810/4848 [3:18:37<56:38,  3.27s/it]

💾 Saving progress at sample 3810

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 79%|███████▉  | 3820/4848 [3:19:10<55:12,  3.22s/it]

💾 Saving progress at sample 3820

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 79%|███████▉  | 3830/4848 [3:19:41<53:32,  3.16s/it]

💾 Saving progress at sample 3830

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 79%|███████▉  | 3840/4848 [3:20:13<54:09,  3.22s/it]

💾 Saving progress at sample 3840

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 79%|███████▉  | 3850/4848 [3:20:45<52:46,  3.17s/it]

💾 Saving progress at sample 3850

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 80%|███████▉  | 3860/4848 [3:21:17<53:36,  3.26s/it]

💾 Saving progress at sample 3860

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 80%|███████▉  | 3870/4848 [3:21:49<51:13,  3.14s/it]

💾 Saving progress at sample 3870

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 80%|████████  | 3880/4848 [3:22:21<52:52,  3.28s/it]

💾 Saving progress at sample 3880

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 80%|████████  | 3890/4848 [3:22:55<57:19,  3.59s/it]

💾 Saving progress at sample 3890

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 80%|████████  | 3900/4848 [3:23:29<56:37,  3.58s/it]

💾 Saving progress at sample 3900

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 81%|████████  | 3910/4848 [3:24:02<51:23,  3.29s/it]

💾 Saving progress at sample 3910

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 81%|████████  | 3920/4848 [3:24:34<49:17,  3.19s/it]

💾 Saving progress at sample 3920

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 81%|████████  | 3930/4848 [3:25:06<49:08,  3.21s/it]

💾 Saving progress at sample 3930

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 81%|████████▏ | 3940/4848 [3:25:38<48:39,  3.21s/it]

💾 Saving progress at sample 3940

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 81%|████████▏ | 3950/4848 [3:26:10<47:54,  3.20s/it]

💾 Saving progress at sample 3950

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 82%|████████▏ | 3960/4848 [3:26:42<46:50,  3.16s/it]

💾 Saving progress at sample 3960

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 82%|████████▏ | 3970/4848 [3:27:13<46:04,  3.15s/it]

💾 Saving progress at sample 3970

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 82%|████████▏ | 3980/4848 [3:27:45<47:37,  3.29s/it]

💾 Saving progress at sample 3980

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 82%|████████▏ | 3990/4848 [3:28:18<46:18,  3.24s/it]

💾 Saving progress at sample 3990

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 83%|████████▎ | 4000/4848 [3:28:48<43:32,  3.08s/it]

💾 Saving progress at sample 4000

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 83%|████████▎ | 4010/4848 [3:29:21<45:43,  3.27s/it]

💾 Saving progress at sample 4010

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 83%|████████▎ | 4020/4848 [3:29:52<44:42,  3.24s/it]

💾 Saving progress at sample 4020

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 83%|████████▎ | 4030/4848 [3:30:24<43:49,  3.21s/it]

💾 Saving progress at sample 4030

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 83%|████████▎ | 4040/4848 [3:30:57<43:52,  3.26s/it]

💾 Saving progress at sample 4040

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 84%|████████▎ | 4050/4848 [3:31:29<43:24,  3.26s/it]

💾 Saving progress at sample 4050

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 84%|████████▎ | 4060/4848 [3:32:00<41:47,  3.18s/it]

💾 Saving progress at sample 4060

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 84%|████████▍ | 4070/4848 [3:32:32<41:09,  3.17s/it]

💾 Saving progress at sample 4070

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 84%|████████▍ | 4080/4848 [3:33:03<40:08,  3.14s/it]

💾 Saving progress at sample 4080

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 84%|████████▍ | 4090/4848 [3:33:35<40:41,  3.22s/it]

💾 Saving progress at sample 4090

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 85%|████████▍ | 4100/4848 [3:34:06<39:25,  3.16s/it]

💾 Saving progress at sample 4100

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 85%|████████▍ | 4110/4848 [3:34:39<39:09,  3.18s/it]

💾 Saving progress at sample 4110

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 85%|████████▍ | 4120/4848 [3:35:12<40:39,  3.35s/it]

💾 Saving progress at sample 4120

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 85%|████████▌ | 4128/4848 [3:35:40<40:58,  3.41s/it]WARNING:urllib3.connectionpool:Retrying (PostForcelistRetry(total=4, connect=3, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /runtime/backends/?provider=ibm-q%2Fopen%2Fmain
 85%|████████▌ | 4130/4848 [3:35:48<43:21,  3.62s/it]

💾 Saving progress at sample 4130

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 85%|████████▌ | 4140/4848 [3:36:20<38:16,  3.24s/it]

💾 Saving progress at sample 4140

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 86%|████████▌ | 4150/4848 [3:36:52<36:51,  3.17s/it]

💾 Saving progress at sample 4150

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 86%|████████▌ | 4160/4848 [3:37:24<37:29,  3.27s/it]

💾 Saving progress at sample 4160

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 86%|████████▌ | 4170/4848 [3:37:55<35:30,  3.14s/it]

💾 Saving progress at sample 4170

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 86%|████████▌ | 4180/4848 [3:38:27<35:57,  3.23s/it]

💾 Saving progress at sample 4180

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 86%|████████▋ | 4190/4848 [3:38:59<34:19,  3.13s/it]

💾 Saving progress at sample 4190

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 87%|████████▋ | 4200/4848 [3:39:31<34:48,  3.22s/it]

💾 Saving progress at sample 4200

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 87%|████████▋ | 4210/4848 [3:40:01<32:38,  3.07s/it]

💾 Saving progress at sample 4210

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 87%|████████▋ | 4220/4848 [3:40:33<32:46,  3.13s/it]

💾 Saving progress at sample 4220

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 87%|████████▋ | 4230/4848 [3:41:04<32:42,  3.18s/it]

💾 Saving progress at sample 4230

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 87%|████████▋ | 4240/4848 [3:41:36<32:38,  3.22s/it]

💾 Saving progress at sample 4240

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 88%|████████▊ | 4250/4848 [3:42:08<31:37,  3.17s/it]

💾 Saving progress at sample 4250

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 88%|████████▊ | 4260/4848 [3:42:39<30:56,  3.16s/it]

💾 Saving progress at sample 4260

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 88%|████████▊ | 4270/4848 [3:43:11<30:43,  3.19s/it]

💾 Saving progress at sample 4270

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 88%|████████▊ | 4280/4848 [3:43:43<31:07,  3.29s/it]

💾 Saving progress at sample 4280

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 88%|████████▊ | 4290/4848 [3:44:14<29:18,  3.15s/it]

💾 Saving progress at sample 4290

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 89%|████████▊ | 4300/4848 [3:44:46<29:14,  3.20s/it]

💾 Saving progress at sample 4300

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 89%|████████▉ | 4310/4848 [3:45:18<29:22,  3.28s/it]

💾 Saving progress at sample 4310

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 89%|████████▉ | 4320/4848 [3:45:50<28:42,  3.26s/it]

💾 Saving progress at sample 4320

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 89%|████████▉ | 4330/4848 [3:46:22<28:18,  3.28s/it]

💾 Saving progress at sample 4330

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 90%|████████▉ | 4340/4848 [3:46:58<29:30,  3.49s/it]

💾 Saving progress at sample 4340

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 90%|████████▉ | 4350/4848 [3:47:31<27:43,  3.34s/it]

💾 Saving progress at sample 4350

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 90%|████████▉ | 4360/4848 [3:48:02<25:15,  3.10s/it]

💾 Saving progress at sample 4360

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 90%|█████████ | 4370/4848 [3:48:34<25:50,  3.24s/it]

💾 Saving progress at sample 4370

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 90%|█████████ | 4380/4848 [3:49:05<24:48,  3.18s/it]

💾 Saving progress at sample 4380

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 91%|█████████ | 4390/4848 [3:49:37<24:32,  3.22s/it]

💾 Saving progress at sample 4390

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 91%|█████████ | 4400/4848 [3:50:08<23:38,  3.17s/it]

💾 Saving progress at sample 4400

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 91%|█████████ | 4410/4848 [3:50:41<23:40,  3.24s/it]

💾 Saving progress at sample 4410

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 91%|█████████ | 4420/4848 [3:51:12<22:52,  3.21s/it]

💾 Saving progress at sample 4420

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 91%|█████████▏| 4430/4848 [3:51:44<22:36,  3.25s/it]

💾 Saving progress at sample 4430

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 92%|█████████▏| 4440/4848 [3:52:16<21:55,  3.22s/it]

💾 Saving progress at sample 4440

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 92%|█████████▏| 4450/4848 [3:52:47<21:08,  3.19s/it]

💾 Saving progress at sample 4450

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 92%|█████████▏| 4460/4848 [3:53:19<20:45,  3.21s/it]

💾 Saving progress at sample 4460

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 92%|█████████▏| 4470/4848 [3:53:51<19:35,  3.11s/it]

💾 Saving progress at sample 4470

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 92%|█████████▏| 4480/4848 [3:54:21<18:46,  3.06s/it]

💾 Saving progress at sample 4480

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 93%|█████████▎| 4490/4848 [3:54:52<18:44,  3.14s/it]

💾 Saving progress at sample 4490

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 93%|█████████▎| 4500/4848 [3:55:24<18:11,  3.14s/it]

💾 Saving progress at sample 4500

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 93%|█████████▎| 4510/4848 [3:55:56<18:10,  3.23s/it]

💾 Saving progress at sample 4510

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 93%|█████████▎| 4520/4848 [3:56:27<17:42,  3.24s/it]

💾 Saving progress at sample 4520

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 93%|█████████▎| 4530/4848 [3:56:59<16:55,  3.19s/it]

💾 Saving progress at sample 4530

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 94%|█████████▎| 4540/4848 [3:57:31<16:32,  3.22s/it]

💾 Saving progress at sample 4540

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 94%|█████████▍| 4550/4848 [3:58:05<18:30,  3.73s/it]

💾 Saving progress at sample 4550

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 94%|█████████▍| 4560/4848 [3:58:39<16:52,  3.52s/it]

💾 Saving progress at sample 4560

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 94%|█████████▍| 4570/4848 [3:59:11<14:38,  3.16s/it]

💾 Saving progress at sample 4570

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 94%|█████████▍| 4580/4848 [3:59:42<14:22,  3.22s/it]

💾 Saving progress at sample 4580

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 95%|█████████▍| 4590/4848 [4:00:14<13:30,  3.14s/it]

💾 Saving progress at sample 4590

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 95%|█████████▍| 4600/4848 [4:00:45<13:43,  3.32s/it]

💾 Saving progress at sample 4600

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 95%|█████████▌| 4610/4848 [4:01:16<12:28,  3.14s/it]

💾 Saving progress at sample 4610

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 95%|█████████▌| 4620/4848 [4:01:49<12:39,  3.33s/it]

💾 Saving progress at sample 4620

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 96%|█████████▌| 4630/4848 [4:02:20<11:32,  3.18s/it]

💾 Saving progress at sample 4630

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 96%|█████████▌| 4640/4848 [4:02:52<11:15,  3.25s/it]

💾 Saving progress at sample 4640

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 96%|█████████▌| 4650/4848 [4:03:24<10:40,  3.23s/it]

💾 Saving progress at sample 4650

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 96%|█████████▌| 4660/4848 [4:03:57<10:17,  3.29s/it]

💾 Saving progress at sample 4660

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 96%|█████████▋| 4670/4848 [4:04:28<09:26,  3.19s/it]

💾 Saving progress at sample 4670

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 97%|█████████▋| 4680/4848 [4:05:01<09:19,  3.33s/it]

💾 Saving progress at sample 4680

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 97%|█████████▋| 4690/4848 [4:05:32<08:24,  3.19s/it]

💾 Saving progress at sample 4690

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 97%|█████████▋| 4700/4848 [4:06:04<07:50,  3.18s/it]

💾 Saving progress at sample 4700

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 97%|█████████▋| 4710/4848 [4:06:35<07:21,  3.20s/it]

💾 Saving progress at sample 4710

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 97%|█████████▋| 4720/4848 [4:07:06<06:36,  3.10s/it]

💾 Saving progress at sample 4720

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 98%|█████████▊| 4730/4848 [4:07:37<06:14,  3.18s/it]

💾 Saving progress at sample 4730

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 98%|█████████▊| 4740/4848 [4:08:09<05:38,  3.14s/it]

💾 Saving progress at sample 4740

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 98%|█████████▊| 4750/4848 [4:08:41<05:10,  3.17s/it]

💾 Saving progress at sample 4750

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 98%|█████████▊| 4760/4848 [4:09:13<04:49,  3.29s/it]

💾 Saving progress at sample 4760

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 98%|█████████▊| 4770/4848 [4:09:45<04:10,  3.21s/it]

💾 Saving progress at sample 4770

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 99%|█████████▊| 4780/4848 [4:10:19<03:44,  3.30s/it]

💾 Saving progress at sample 4780

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 99%|█████████▉| 4790/4848 [4:10:51<03:09,  3.26s/it]

💾 Saving progress at sample 4790

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 99%|█████████▉| 4799/4848 [4:11:19<02:32,  3.12s/it]

💾 Saving progress at sample 4800

 99%|█████████▉| 4800/4848 [4:11:23<02:34,  3.21s/it]<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 99%|█████████▉| 4810/4848 [4:11:54<02:01,  3.19s/it]

💾 Saving progress at sample 4810

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
 99%|█████████▉| 4820/4848 [4:12:26<01:28,  3.17s/it]

💾 Saving progress at sample 4820

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
100%|█████████▉| 4830/4848 [4:12:58<01:01,  3.42s/it]

💾 Saving progress at sample 4830

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
100%|█████████▉| 4840/4848 [4:13:30<00:25,  3.22s/it]

💾 Saving progress at sample 4840

<ipython-input-27-84eef1b67573>:19: DeprecationWarning: The class ``qiskit.primitives.sampler.Sampler`` is deprecated as of qiskit 1.2. It will be removed no earlier than 3 months after the release date. All implementations of the `BaseSamplerV1` interface have been deprecated in favor of their V2 counterparts. The V2 alternative for the `Sampler` class is `StatevectorSampler`.
  sampler = Sampler()
100%|██████████| 4848/4848 [4:13:55<00:00,  3.14s/it]

💾 Saving progress at sample 4848
✅ Final full CSV saved: /content/drive/MyDrive/QML/parkinson_gait/parkinsons_features_quantum_hardware_please.csv

In [ ]:
df[gait_features]

,ForcePlate_2_mean,ForcePlate_2_std,ForcePlate_2_max,ForcePlate_2_range,ForcePlate_2_iqr,ForcePlate_2_energy,ForcePlate_2_rms,ForcePlate_2_skew,ForcePlate_2_kurtosis,ForcePlate_2_dominant_freq,...,ForcePlate_19_mean,ForcePlate_19_std,ForcePlate_19_max,ForcePlate_19_range,ForcePlate_19_iqr,ForcePlate_19_energy,ForcePlate_19_rms,ForcePlate_19_skew,ForcePlate_19_kurtosis,ForcePlate_19_dominant_freq
0,172.359367,143.888911,418.88,414.26,284.6800,1.512353e+07,224.525656,0.148185,-1.499030,0.006667,...,634.180433,422.240115,1131.79,1131.79,978.0650,1.741415e+08,761.886827,-0.449844,-1.370928,0.006667
1,145.777133,152.755170,432.41,432.41,274.0925,1.337553e+07,211.151876,0.515931,-1.335367,0.006667,...,491.962167,483.780238,1158.30,1158.30,1000.9450,1.428210e+08,689.978327,0.136567,-1.853274,0.006667
2,114.031500,136.622165,432.41,432.41,236.9400,9.500640e+06,177.957295,0.821438,-0.837736,0.006667,...,517.942333,492.622034,1220.45,1220.45,1012.1375,1.532822e+08,714.801181,0.071004,-1.834301,0.006667
3,101.729833,132.147795,368.17,368.17,231.7700,8.343600e+06,166.769298,0.869513,-0.937864,0.006667,...,575.117033,487.173268,1220.45,1220.45,1031.6075,1.704292e+08,753.722360,-0.172900,-1.820402,0.006667
4,96.336533,127.534214,376.09,376.09,213.6200,7.663711e+06,159.830233,0.911398,-0.770219,0.006667,...,623.639867,476.932279,1115.95,1115.95,1029.5450,1.849173e+08,785.105778,-0.413489,-1.718276,0.006667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5913,69.024633,86.291361,250.80,250.80,147.5100,3.663180e+06,110.501579,0.873116,-0.863150,0.010000,...,495.266933,423.163922,1065.68,1065.68,934.4500,1.273071e+08,651.426926,-0.035448,-1.715901,0.010000
5914,69.532833,90.676881,250.80,250.80,156.2275,3.917133e+06,114.267719,0.874999,-0.916010,0.006667,...,577.026633,399.735854,1059.30,1059.30,882.2550,1.478245e+08,701.960461,-0.432189,-1.472263,0.006667
5915,87.687233,93.763869,244.42,244.42,193.2700,4.944214e+06,128.377233,0.435041,-1.554129,0.010000,...,511.219500,405.442885,1058.86,1058.86,883.9600,1.277188e+08,652.479356,-0.109681,-1.654724,0.010000
5916,86.758467,90.207240,234.96,234.96,190.5200,4.699313e+06,125.157412,0.459379,-1.498940,0.006667,...,428.646167,409.161572,1058.86,1058.86,840.6200,1.053452e+08,592.579723,0.240478,-1.620321,0.006667
5917,64.051900,77.116660,228.58,228.58,125.8400,3.014888e+06,100.247819,0.894491,-0.753342,0.006667,...,454.414400,414.434802,1060.07,1060.07,865.3150,1.134746e+08,615.019229,0.137071,-1.647041,0.006667