In [ ]:
!pip install qiskit==0.43.1 qiskit-ibm-provider==0.5.0

Requirement already satisfied: qiskit==0.43.1 in /usr/local/lib/python3.11/dist-packages (0.43.1)
Requirement already satisfied: qiskit-ibm-provider==0.5.0 in /usr/local/lib/python3.11/dist-packages (0.5.0)
Requirement already satisfied: qiskit-terra==0.24.1 in /usr/local/lib/python3.11/dist-packages (from qiskit==0.43.1) (0.24.1)
Requirement already satisfied: qiskit-aer==0.12.0 in /usr/local/lib/python3.11/dist-packages (from qiskit==0.43.1) (0.12.0)
Requirement already satisfied: qiskit-ibmq-provider==0.20.2 in /usr/local/lib/python3.11/dist-packages (from qiskit==0.43.1) (0.20.2)
Requirement already satisfied: requests>=2.19 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider==0.5.0) (2.32.3)
Requirement already satisfied: requests-ntlm>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider==0.5.0) (1.1.0)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider==0.5.0) (1.23.5)
Requirement already satisfied: urllib3>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider==0.5.0) (2.3.0)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider==0.5.0) (2.8.2)
Requirement already satisfied: websocket-client>=1.5.1 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider==0.5.0) (1.8.0)
Requirement already satisfied: websockets>=10.0 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider==0.5.0) (15.0.1)
Requirement already satisfied: typing-extensions>=4.3 in /usr/local/lib/python3.11/dist-packages (from qiskit-ibm-provider==0.5.0) (4.13.2)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.11/dist-packages (from qiskit-aer==0.12.0->qiskit==0.43.1) (1.14.1)
Requirement already satisfied: rustworkx>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from qiskit-terra==0.24.1->qiskit==0.43.1) (0.16.0)
Requirement already satisfied: ply>=3.10 in /usr/local/lib/python3.11/dist-packages (from qiskit-terra==0.24.1->qiskit==0.43.1) (3.11)
Requirement already satisfied: psutil>=5 in /usr/local/lib/python3.11/dist-packages (from qiskit-terra==0.24.1->qiskit==0.43.1) (5.9.5)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.11/dist-packages (from qiskit-terra==0.24.1->qiskit==0.43.1) (1.13.1)
Requirement already satisfied: dill>=0.3 in /usr/local/lib/python3.11/dist-packages (from qiskit-terra==0.24.1->qiskit==0.43.1) (0.4.0)
Requirement already satisfied: stevedore>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from qiskit-terra==0.24.1->qiskit==0.43.1) (5.4.1)
Requirement already satisfied: symengine<0.10,>=0.9 in /usr/local/lib/python3.11/dist-packages (from qiskit-terra==0.24.1->qiskit==0.43.1) (0.9.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.0->qiskit-ibm-provider==0.5.0) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19->qiskit-ibm-provider==0.5.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19->qiskit-ibm-provider==0.5.0) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19->qiskit-ibm-provider==0.5.0) (2025.1.31)
Requirement already satisfied: ntlm-auth>=1.0.2 in /usr/local/lib/python3.11/dist-packages (from requests-ntlm>=1.1.0->qiskit-ibm-provider==0.5.0) (1.5.0)
Requirement already satisfied: cryptography>=1.3 in /usr/local/lib/python3.11/dist-packages (from requests-ntlm>=1.1.0->qiskit-ibm-provider==0.5.0) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibm-provider==0.5.0) (1.17.1)
Requirement already satisfied: pbr>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from stevedore>=3.0.0->qiskit-terra==0.24.1->qiskit==0.43.1) (6.1.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy>=1.3->qiskit-terra==0.24.1->qiskit==0.43.1) (1.3.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-ibm-provider==0.5.0) (2.22)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from pbr>=2.0.0->stevedore>=3.0.0->qiskit-terra==0.24.1->qiskit==0.43.1) (75.2.0)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 📌 Load Data
df = pd.read_csv("/content/drive/MyDrive/QML/validation/processed_gait_features.csv")

df.head()

,HipAngles_t0,KneeAngles_t0,AnkleAngles_t0,HipAngles_t1,KneeAngles_t1,AnkleAngles_t1,HipAngles_t2,KneeAngles_t2,AnkleAngles_t2,HipAngles_t3,...,HipAngles_t9,KneeAngles_t9,AnkleAngles_t9,HipAngles_t10,KneeAngles_t10,AnkleAngles_t10,HipAngles_t11,KneeAngles_t11,AnkleAngles_t11,Label
0,30.049283,11.570827,-2.482850,30.037282,11.714903,-2.519216,30.024681,11.858510,-2.555104,30.011461,...,29.917874,12.850300,-2.792050,29.899789,12.990142,-2.823833,29.881429,13.129831,-2.855325,0
1,29.967856,12.428170,-2.693670,29.951934,12.569373,-2.727010,29.935280,12.710084,-2.759807,29.917874,...,29.803088,13.684542,-2.976271,29.781543,13.821460,-3.004636,29.758920,13.957372,-3.032007,0
2,29.862726,13.269265,-2.886438,29.843533,13.408295,-2.917049,29.823703,13.546771,-2.947034,29.803088,...,29.655016,14.491002,-3.131655,29.625860,14.622537,-3.154451,29.595627,14.753186,-3.176210,0
3,29.735071,14.092141,-3.058261,29.709800,14.225834,-3.083470,29.683023,14.358725,-3.107948,29.655016,...,29.465393,15.264074,-3.250358,29.430696,15.388425,-3.265330,29.394712,15.511519,-3.279152,0
4,29.564392,14.882804,-3.196806,29.532227,15.011250,-3.216112,29.499206,15.138379,-3.234003,29.465393,...,29.231656,15.993528,-3.323775,29.186913,16.110906,-3.331378,29.140990,16.226755,-3.337219,0

# Step 1: Quantum Feature Extraction

In [ ]:
from google.colab import userdata
QIBM_API_KEY = userdata.get('QIBM_API_KEY')

In [ ]:
from qiskit_ibm_provider import IBMProvider

IBMProvider.save_account(QIBM_API_KEY, overwrite=True)
provider = IBMProvider()

In [ ]:
from qiskit_ibm_provider import least_busy

backend = least_busy(
    provider.backends(
        simulator=False,
        min_num_qubits=4,
        operational=True,
        dynamic_reprate_enabled=True
    )
)

print(f"Running on backend: {backend.name}")

Running on backend: ibm_brisbane

In [ ]:
from qiskit.primitives import Sampler
from qiskit import QuantumCircuit

# Define quantum circuit
num_qubits = 5
features = np.random.uniform(0, np.pi, num_qubits)

qc = QuantumCircuit(num_qubits, num_qubits)

for i in range(num_qubits):
    qc.ry(features[i], i)

for i in range(num_qubits - 1):
    qc.cx(i, i + 1)
qc.cx(num_qubits - 1, 0)

# ✅ Explicitly map qubit i → classical bit i
qc.measure(range(num_qubits), range(num_qubits))

sampler = Sampler()
job = sampler.run([qc])
result = job.result()

print("Quantum output:", result.quasi_dists[0])

Quantum output: {0: 5.2721406035e-05, 1: 4.09042347743e-05, 2: 2.37984375e-08, 3: 9.33445205e-08, 4: 6.7662778e-09, 5: 5.2496593e-09, 6: 2.9650312209e-06, 7: 1.1629730607e-05, 8: 0.0282758557475162, 9: 0.0219380006894219, 10: 1.27637185246e-05, 11: 5.00630843063e-05, 12: 0.0002269524793196, 13: 0.0001760825098359, 14: 0.0994521955002785, 15: 0.39008096568147, 16: 0.1734903052904498, 17: 0.2236113908206172, 18: 0.0003959093585167, 19: 0.0001009381599915, 20: 2.22657872191e-05, 21: 2.86983393075e-05, 22: 0.0493260789398215, 23: 0.012575817016386, 24: 5.1723762269e-06, 25: 6.6666678579e-06, 26: 1.18034962e-08, 27: 3.0093332e-09, 28: 4.15154052e-08, 29: 5.35091427e-08, 30: 9.19703459771e-05, 31: 2.34480880459e-05}

In [ ]:
def quantum_feature_vector(features, backend_name="ibm_brisbane", num_qubits=5):
    from qiskit_ibm_provider import IBMProvider
    from qiskit.primitives import Sampler
    from qiskit import QuantumCircuit
    import numpy as np

    provider = IBMProvider()
    qc = QuantumCircuit(num_qubits, num_qubits)

    for i in range(num_qubits):
        qc.ry(features[i], i)

    for i in range(num_qubits - 1):
        qc.cx(i, i + 1)
    qc.cx(num_qubits - 1, 0)

    qc.measure(range(num_qubits), range(num_qubits))

    sampler = Sampler()
    job = sampler.run([qc])
    result = job.result()

    vec = [float(result.quasi_dists[0].get(i, 0.0)) for i in range(2 ** num_qubits)]
    return vec

In [ ]:
import json

# --- CONFIG ---
CACHE_FILE = "/content/drive/MyDrive/QML/validation/stroke_quantum_cache.json"
num_qubits = 5

# --- Hashing utility ---
def hash_input(arr):
    return hashlib.md5(np.round(arr, 6).tobytes()).hexdigest()

# --- Load existing cache ---
if os.path.exists(CACHE_FILE):
    with open(CACHE_FILE, "r") as f:
        cache = json.load(f)
else:
    cache = {}

# --- Safe quantum feature wrapper ---
def cached_quantum_feature_vector(features):
    key = hash_input(features)
    if key in cache:
        return cache[key]

    try:
        vec = quantum_feature_vector(features, num_qubits=num_qubits)
        cache[key] = vec

        # Save after each success
        with open(CACHE_FILE, "w") as f:
            json.dump(cache, f)

        print(f"✅ Processed: {key}")
        return vec

    except Exception as e:
        print(f"❌ Error on input {key}: {e}")
        return [0.0] * (2 ** num_qubits)  # placeholder if fail

# Step 2: Apply Quantum Encoding to Entire Dataset

In [ ]:
def extract_quantum_features_deduplicated(
    df,
    gait_features,
    quantum_feature_fn,
    num_qubits=5,
    cache_file="/content/drive/MyDrive/QML/validation/stroke_quantum_cache.json",
    save_every=10,
    output_csv="/content/drive/MyDrive/QML/validation/quantum_features_partial_windowed.csv"
):
    import numpy as np
    import pandas as pd
    import os
    import json
    import hashlib
    from tqdm import tqdm

    # Step 1: Round + deduplicate
    X_classical = df[gait_features].values
    X_classical_rounded = np.round(X_classical, 6)
    X_unique, idx_unique, idx_inverse = np.unique(
        X_classical_rounded, axis=0, return_index=True, return_inverse=True
    )

    print(f"🔍 Unique samples: {len(X_unique)} / {len(X_classical)} total")

    # Step 2: Load or initialize cache
    if os.path.exists(cache_file):
        with open(cache_file, "r") as f:
            cache = json.load(f)
    else:
        cache = {}

    # Step 3: Hashing function
    def hash_input(arr):
        return hashlib.md5(np.round(arr, 6).tobytes()).hexdigest()

    # Step 4: Safe call with cache
    def cached_quantum_call(features):
        key = hash_input(features)
        if key in cache:
            return cache[key]
        try:
            vec = quantum_feature_fn(features)
            cache[key] = vec
            with open(cache_file, "w") as f:
                json.dump(cache, f)
            return vec
        except Exception as e:
            print(f"❌ Error processing {key}: {e}")
            return [0.0] * (2 ** num_qubits)

    # Step 5: Extract features with incremental saving
    X_quantum_unique = []
    for i, x in enumerate(tqdm(X_unique)):
        X_quantum_unique.append(cached_quantum_call(x))

        # Save progress every N samples
        if (i + 1) % save_every == 0 or (i + 1) == len(X_unique):
            print(f"💾 Saving progress at sample {i + 1}")
            # Get mask of which unique rows were processed
            processed_mask = np.isin(idx_inverse, range(i + 1))

            # Reconstruct those rows
            partial_full = np.array(X_quantum_unique)[idx_inverse[processed_mask]]

            partial_df = pd.DataFrame(
                partial_full,
                columns=[f"Quantum_Feature_{j}" for j in range(2 ** num_qubits)]
            )
            partial_df["Label"] = df["Label"].values[processed_mask]

            # Save it
            partial_df.to_csv(output_csv, index=False)


    # Step 6: Reconstruct full dataset
    X_quantum_full = np.array(X_quantum_unique)[idx_inverse]

    # Step 7: Final DataFrame
    df_quantum = pd.DataFrame(
        X_quantum_full, columns=[f"Quantum_Feature_{i}" for i in range(2 ** num_qubits)]
    )
    df_quantum["Label"] = df["Label"].values

    # Final save
    df_quantum.to_csv(output_csv, index=False)
    print(f"✅ Final full CSV saved: {output_csv}")

    return df_quantum

In [ ]:
gf = df.drop(columns=["Label"])

gait_features = gf.columns.tolist()

In [ ]:
gait_features

['HipAngles_t0',
 'KneeAngles_t0',
 'AnkleAngles_t0',
 'HipAngles_t1',
 'KneeAngles_t1',
 'AnkleAngles_t1',
 'HipAngles_t2',
 'KneeAngles_t2',
 'AnkleAngles_t2',
 'HipAngles_t3',
 'KneeAngles_t3',
 'AnkleAngles_t3',
 'HipAngles_t4',
 'KneeAngles_t4',
 'AnkleAngles_t4',
 'HipAngles_t5',
 'KneeAngles_t5',
 'AnkleAngles_t5',
 'HipAngles_t6',
 'KneeAngles_t6',
 'AnkleAngles_t6',
 'HipAngles_t7',
 'KneeAngles_t7',
 'AnkleAngles_t7',
 'HipAngles_t8',
 'KneeAngles_t8',
 'AnkleAngles_t8',
 'HipAngles_t9',
 'KneeAngles_t9',
 'AnkleAngles_t9',
 'HipAngles_t10',
 'KneeAngles_t10',
 'AnkleAngles_t10',
 'HipAngles_t11',
 'KneeAngles_t11',
 'AnkleAngles_t11']

In [ ]:
df_quantum = extract_quantum_features_deduplicated(
    df=df,
    gait_features=gait_features,
    quantum_feature_fn=quantum_feature_vector,
    num_qubits=5,
    cache_file = "/content/drive/MyDrive/QML/validation/stroke_quantum_cache.json",
    save_every=10,
    output_csv="/content/drive/MyDrive/QML/validation/stroke_quantum_features_partial_windowed.csv"
)

🔍 Unique samples: 16500 / 16500 total

  0%|          | 0/16500 [00:00<?, ?it/s]

💾 Saving progress at sample 10

  0%|          | 80/16500 [00:00<01:34, 173.15it/s]

💾 Saving progress at sample 20
💾 Saving progress at sample 30
💾 Saving progress at sample 40
💾 Saving progress at sample 50
💾 Saving progress at sample 60
💾 Saving progress at sample 70
💾 Saving progress at sample 80
💾 Saving progress at sample 90
💾 Saving progress at sample 100
💾 Saving progress at sample 110
💾 Saving progress at sample 120
💾 Saving progress at sample 130
💾 Saving progress at sample 140
💾 Saving progress at sample 150

  1%|▏         | 210/16500 [00:00<00:45, 358.83it/s]

💾 Saving progress at sample 160
💾 Saving progress at sample 170
💾 Saving progress at sample 180
💾 Saving progress at sample 190
💾 Saving progress at sample 200
💾 Saving progress at sample 210
💾 Saving progress at sample 220
💾 Saving progress at sample 230
💾 Saving progress at sample 240
💾 Saving progress at sample 250
💾 Saving progress at sample 260

  2%|▏         | 322/16500 [00:01<00:39, 408.49it/s]

💾 Saving progress at sample 270
💾 Saving progress at sample 280
💾 Saving progress at sample 290
💾 Saving progress at sample 300
💾 Saving progress at sample 310
💾 Saving progress at sample 320
💾 Saving progress at sample 330
💾 Saving progress at sample 340
💾 Saving progress at sample 350

  3%|▎         | 418/16500 [00:01<00:38, 421.81it/s]

💾 Saving progress at sample 360
💾 Saving progress at sample 370
💾 Saving progress at sample 380
💾 Saving progress at sample 390
💾 Saving progress at sample 400
💾 Saving progress at sample 410
💾 Saving progress at sample 420
💾 Saving progress at sample 430

  3%|▎         | 464/16500 [00:01<00:42, 373.14it/s]

💾 Saving progress at sample 440
💾 Saving progress at sample 450
💾 Saving progress at sample 460
💾 Saving progress at sample 470
💾 Saving progress at sample 480
💾 Saving progress at sample 490
💾 Saving progress at sample 500

  3%|▎         | 544/16500 [00:01<00:45, 347.20it/s]

💾 Saving progress at sample 510
💾 Saving progress at sample 520
💾 Saving progress at sample 530
💾 Saving progress at sample 540
💾 Saving progress at sample 550
💾 Saving progress at sample 560
💾 Saving progress at sample 570

  4%|▎         | 616/16500 [00:01<00:50, 316.56it/s]

💾 Saving progress at sample 580
💾 Saving progress at sample 590
💾 Saving progress at sample 600
💾 Saving progress at sample 610
💾 Saving progress at sample 620
💾 Saving progress at sample 630

  4%|▍         | 681/16500 [00:02<00:54, 292.26it/s]

💾 Saving progress at sample 640
💾 Saving progress at sample 650
💾 Saving progress at sample 660
💾 Saving progress at sample 670
💾 Saving progress at sample 680
💾 Saving progress at sample 690

  4%|▍         | 740/16500 [00:02<00:57, 275.53it/s]

💾 Saving progress at sample 700
💾 Saving progress at sample 710
💾 Saving progress at sample 720
💾 Saving progress at sample 730
💾 Saving progress at sample 740
💾 Saving progress at sample 750

  5%|▍         | 770/16500 [00:02<01:00, 257.90it/s]

💾 Saving progress at sample 760
💾 Saving progress at sample 770
💾 Saving progress at sample 780
💾 Saving progress at sample 790
💾 Saving progress at sample 800

  5%|▌         | 830/16500 [00:02<01:02, 248.94it/s]

💾 Saving progress at sample 810
💾 Saving progress at sample 820
💾 Saving progress at sample 830
💾 Saving progress at sample 840
💾 Saving progress at sample 850

  5%|▌         | 890/16500 [00:03<01:09, 226.07it/s]

💾 Saving progress at sample 860
💾 Saving progress at sample 870
💾 Saving progress at sample 880
💾 Saving progress at sample 890
💾 Saving progress at sample 900

  6%|▌         | 920/16500 [00:03<01:09, 224.79it/s]

💾 Saving progress at sample 910
💾 Saving progress at sample 920
💾 Saving progress at sample 930
💾 Saving progress at sample 940
💾 Saving progress at sample 950

  6%|▌         | 980/16500 [00:03<01:10, 220.80it/s]

💾 Saving progress at sample 960
💾 Saving progress at sample 970
💾 Saving progress at sample 980
💾 Saving progress at sample 990
💾 Saving progress at sample 1000

  6%|▋         | 1032/16500 [00:03<01:11, 214.88it/s]

💾 Saving progress at sample 1010
💾 Saving progress at sample 1020
💾 Saving progress at sample 1030
💾 Saving progress at sample 1040

  7%|▋         | 1080/16500 [00:03<01:17, 199.08it/s]

💾 Saving progress at sample 1050
💾 Saving progress at sample 1060
💾 Saving progress at sample 1070
💾 Saving progress at sample 1080
💾 Saving progress at sample 1090

  7%|▋         | 1130/16500 [00:04<01:17, 199.22it/s]

💾 Saving progress at sample 1100
💾 Saving progress at sample 1110
💾 Saving progress at sample 1120
💾 Saving progress at sample 1130
💾 Saving progress at sample 1140

  7%|▋         | 1170/16500 [00:04<01:20, 191.37it/s]

💾 Saving progress at sample 1150
💾 Saving progress at sample 1160
💾 Saving progress at sample 1170
💾 Saving progress at sample 1180

  7%|▋         | 1210/16500 [00:04<01:26, 177.61it/s]

💾 Saving progress at sample 1190
💾 Saving progress at sample 1200
💾 Saving progress at sample 1210
💾 Saving progress at sample 1220

  8%|▊         | 1250/16500 [00:04<01:28, 172.16it/s]

💾 Saving progress at sample 1230
💾 Saving progress at sample 1240
💾 Saving progress at sample 1250
💾 Saving progress at sample 1260

  8%|▊         | 1290/16500 [00:05<01:30, 169.00it/s]

💾 Saving progress at sample 1270
💾 Saving progress at sample 1280
💾 Saving progress at sample 1290
💾 Saving progress at sample 1300

  8%|▊         | 1310/16500 [00:05<01:30, 167.73it/s]

💾 Saving progress at sample 1310
💾 Saving progress at sample 1320
💾 Saving progress at sample 1330

  8%|▊         | 1350/16500 [00:05<01:35, 158.03it/s]

💾 Saving progress at sample 1340
💾 Saving progress at sample 1350
💾 Saving progress at sample 1360
💾 Saving progress at sample 1370

  8%|▊         | 1390/16500 [00:05<01:35, 157.51it/s]

💾 Saving progress at sample 1380
💾 Saving progress at sample 1390
💾 Saving progress at sample 1400
💾 Saving progress at sample 1410

  9%|▊         | 1430/16500 [00:06<01:36, 156.46it/s]

💾 Saving progress at sample 1420
💾 Saving progress at sample 1430
💾 Saving progress at sample 1440
💾 Saving progress at sample 1450

  9%|▉         | 1470/16500 [00:06<01:38, 152.94it/s]

💾 Saving progress at sample 1460
💾 Saving progress at sample 1470
💾 Saving progress at sample 1480
💾 Saving progress at sample 1490

  9%|▉         | 1510/16500 [00:06<01:40, 149.20it/s]

💾 Saving progress at sample 1500
💾 Saving progress at sample 1510
💾 Saving progress at sample 1520

  9%|▉         | 1530/16500 [00:06<01:42, 146.66it/s]

💾 Saving progress at sample 1530
💾 Saving progress at sample 1540
💾 Saving progress at sample 1550

 10%|▉         | 1570/16500 [00:07<01:41, 147.09it/s]

💾 Saving progress at sample 1560
💾 Saving progress at sample 1570
💾 Saving progress at sample 1580

 10%|▉         | 1590/16500 [00:07<01:41, 146.29it/s]

💾 Saving progress at sample 1590
💾 Saving progress at sample 1600
💾 Saving progress at sample 1610

 10%|▉         | 1630/16500 [00:07<01:46, 139.34it/s]

💾 Saving progress at sample 1620
💾 Saving progress at sample 1630
💾 Saving progress at sample 1640

 10%|█         | 1650/16500 [00:07<01:44, 141.53it/s]

💾 Saving progress at sample 1650
💾 Saving progress at sample 1660
💾 Saving progress at sample 1670

 10%|█         | 1690/16500 [00:07<01:44, 142.06it/s]

💾 Saving progress at sample 1680
💾 Saving progress at sample 1690
💾 Saving progress at sample 1700

 10%|█         | 1710/16500 [00:08<01:46, 138.92it/s]

💾 Saving progress at sample 1710
💾 Saving progress at sample 1720
💾 Saving progress at sample 1730

 11%|█         | 1750/16500 [00:08<01:53, 129.65it/s]

💾 Saving progress at sample 1740
💾 Saving progress at sample 1750
💾 Saving progress at sample 1760

 11%|█         | 1770/16500 [00:08<01:54, 128.98it/s]

💾 Saving progress at sample 1770
💾 Saving progress at sample 1780
💾 Saving progress at sample 1790

 11%|█         | 1810/16500 [00:08<01:52, 130.50it/s]

💾 Saving progress at sample 1800
💾 Saving progress at sample 1810
💾 Saving progress at sample 1820

 11%|█         | 1830/16500 [00:08<01:53, 128.81it/s]

💾 Saving progress at sample 1830
💾 Saving progress at sample 1840
💾 Saving progress at sample 1850

 11%|█▏        | 1870/16500 [00:09<01:53, 128.49it/s]

💾 Saving progress at sample 1860
💾 Saving progress at sample 1870
💾 Saving progress at sample 1880

 12%|█▏        | 1903/16500 [00:09<01:54, 127.30it/s]

💾 Saving progress at sample 1890
💾 Saving progress at sample 1900
💾 Saving progress at sample 1910

 12%|█▏        | 1920/16500 [00:09<02:00, 121.28it/s]

💾 Saving progress at sample 1920
💾 Saving progress at sample 1930
💾 Saving progress at sample 1940

 12%|█▏        | 1960/16500 [00:10<02:00, 120.89it/s]

💾 Saving progress at sample 1950
💾 Saving progress at sample 1960
💾 Saving progress at sample 1970

 12%|█▏        | 1980/16500 [00:10<02:01, 119.40it/s]

💾 Saving progress at sample 1980
💾 Saving progress at sample 1990
💾 Saving progress at sample 2000

 12%|█▏        | 2020/16500 [00:10<02:02, 118.36it/s]

💾 Saving progress at sample 2010
💾 Saving progress at sample 2020
💾 Saving progress at sample 2030

 12%|█▏        | 2040/16500 [00:10<02:05, 115.00it/s]

💾 Saving progress at sample 2040
💾 Saving progress at sample 2050
💾 Saving progress at sample 2060

 13%|█▎        | 2080/16500 [00:11<02:08, 112.42it/s]

💾 Saving progress at sample 2070
💾 Saving progress at sample 2080
💾 Saving progress at sample 2090

 13%|█▎        | 2100/16500 [00:11<02:06, 113.56it/s]

💾 Saving progress at sample 2100
💾 Saving progress at sample 2110
💾 Saving progress at sample 2120

 13%|█▎        | 2140/16500 [00:11<02:08, 111.95it/s]

💾 Saving progress at sample 2130
💾 Saving progress at sample 2140
💾 Saving progress at sample 2150

 13%|█▎        | 2160/16500 [00:11<02:07, 112.20it/s]

💾 Saving progress at sample 2160
💾 Saving progress at sample 2170
💾 Saving progress at sample 2180

 13%|█▎        | 2200/16500 [00:12<02:10, 109.19it/s]

💾 Saving progress at sample 2190
💾 Saving progress at sample 2200
💾 Saving progress at sample 2210

 13%|█▎        | 2220/16500 [00:12<02:10, 109.25it/s]

💾 Saving progress at sample 2220
💾 Saving progress at sample 2230
💾 Saving progress at sample 2240

 14%|█▎        | 2260/16500 [00:12<02:12, 107.84it/s]

💾 Saving progress at sample 2250
💾 Saving progress at sample 2260
💾 Saving progress at sample 2270

 14%|█▍        | 2282/16500 [00:12<02:11, 108.38it/s]

💾 Saving progress at sample 2280
💾 Saving progress at sample 2290

 14%|█▍        | 2310/16500 [00:13<02:20, 101.12it/s]

💾 Saving progress at sample 2300
💾 Saving progress at sample 2310
💾 Saving progress at sample 2320

 14%|█▍        | 2332/16500 [00:13<02:24, 97.87it/s]

💾 Saving progress at sample 2330
💾 Saving progress at sample 2340

 14%|█▍        | 2360/16500 [00:13<02:29, 94.32it/s]

💾 Saving progress at sample 2350
💾 Saving progress at sample 2360
💾 Saving progress at sample 2370

 14%|█▍        | 2380/16500 [00:13<02:26, 96.63it/s]

💾 Saving progress at sample 2380
💾 Saving progress at sample 2390

 15%|█▍        | 2400/16500 [00:14<02:24, 97.43it/s]

💾 Saving progress at sample 2400
💾 Saving progress at sample 2410
💾 Saving progress at sample 2420

 15%|█▍        | 2430/16500 [00:14<02:21, 99.21it/s]

💾 Saving progress at sample 2430
💾 Saving progress at sample 2440
💾 Saving progress at sample 2450

 15%|█▍        | 2461/16500 [00:14<02:18, 101.64it/s]

💾 Saving progress at sample 2460
💾 Saving progress at sample 2470

 15%|█▌        | 2482/16500 [00:15<02:24, 96.94it/s]

💾 Saving progress at sample 2480
💾 Saving progress at sample 2490
💾 Saving progress at sample 2500

 15%|█▌        | 2510/16500 [00:15<02:26, 95.30it/s]

💾 Saving progress at sample 2510
💾 Saving progress at sample 2520

 15%|█▌        | 2530/16500 [00:15<02:27, 94.41it/s]

💾 Saving progress at sample 2530
💾 Saving progress at sample 2540

 15%|█▌        | 2550/16500 [00:15<02:32, 91.27it/s]

💾 Saving progress at sample 2550
💾 Saving progress at sample 2560

 16%|█▌        | 2570/16500 [00:16<02:36, 88.74it/s]

💾 Saving progress at sample 2570
💾 Saving progress at sample 2580

 16%|█▌        | 2590/16500 [00:16<02:32, 91.19it/s]

💾 Saving progress at sample 2590
💾 Saving progress at sample 2600

 16%|█▌        | 2610/16500 [00:16<02:44, 84.34it/s]

💾 Saving progress at sample 2610
💾 Saving progress at sample 2620

 16%|█▌        | 2630/16500 [00:16<02:40, 86.44it/s]

💾 Saving progress at sample 2630
💾 Saving progress at sample 2640

 16%|█▌        | 2650/16500 [00:16<02:38, 87.52it/s]

💾 Saving progress at sample 2650
💾 Saving progress at sample 2660

 16%|█▌        | 2670/16500 [00:17<02:41, 85.48it/s]

💾 Saving progress at sample 2670
💾 Saving progress at sample 2680

 16%|█▋        | 2690/16500 [00:17<02:36, 88.30it/s]

💾 Saving progress at sample 2690
💾 Saving progress at sample 2700

 16%|█▋        | 2710/16500 [00:17<02:33, 90.01it/s]

💾 Saving progress at sample 2710
💾 Saving progress at sample 2720

 17%|█▋        | 2730/16500 [00:17<02:32, 90.56it/s]

💾 Saving progress at sample 2730
💾 Saving progress at sample 2740

 17%|█▋        | 2750/16500 [00:18<02:32, 90.05it/s]

💾 Saving progress at sample 2750
💾 Saving progress at sample 2760

 17%|█▋        | 2770/16500 [00:18<02:42, 84.35it/s]

💾 Saving progress at sample 2770
💾 Saving progress at sample 2780

 17%|█▋        | 2790/16500 [00:18<02:43, 83.73it/s]

💾 Saving progress at sample 2790
💾 Saving progress at sample 2800

 17%|█▋        | 2810/16500 [00:18<02:47, 81.56it/s]

💾 Saving progress at sample 2810
💾 Saving progress at sample 2820

 17%|█▋        | 2830/16500 [00:19<02:42, 84.11it/s]

💾 Saving progress at sample 2830
💾 Saving progress at sample 2840

 17%|█▋        | 2850/16500 [00:19<02:41, 84.41it/s]

💾 Saving progress at sample 2850
💾 Saving progress at sample 2860

 17%|█▋        | 2870/16500 [00:19<02:42, 83.99it/s]

💾 Saving progress at sample 2870
💾 Saving progress at sample 2880

 18%|█▊        | 2890/16500 [00:19<02:42, 83.58it/s]

💾 Saving progress at sample 2890
💾 Saving progress at sample 2900

 18%|█▊        | 2910/16500 [00:20<02:52, 78.57it/s]

💾 Saving progress at sample 2910
💾 Saving progress at sample 2920

 18%|█▊        | 2930/16500 [00:20<02:48, 80.49it/s]

💾 Saving progress at sample 2930
💾 Saving progress at sample 2940

 18%|█▊        | 2950/16500 [00:20<02:47, 81.12it/s]

💾 Saving progress at sample 2950
💾 Saving progress at sample 2960

 18%|█▊        | 2970/16500 [00:20<02:50, 79.16it/s]

💾 Saving progress at sample 2970
💾 Saving progress at sample 2980

 18%|█▊        | 2990/16500 [00:21<02:47, 80.47it/s]

💾 Saving progress at sample 2990
💾 Saving progress at sample 3000

 18%|█▊        | 3010/16500 [00:21<02:52, 78.42it/s]

💾 Saving progress at sample 3010
💾 Saving progress at sample 3020

 18%|█▊        | 3030/16500 [00:21<02:54, 76.99it/s]

💾 Saving progress at sample 3030
💾 Saving progress at sample 3040

 18%|█▊        | 3050/16500 [00:21<02:58, 75.50it/s]

💾 Saving progress at sample 3050
💾 Saving progress at sample 3060

 19%|█▊        | 3070/16500 [00:22<02:49, 79.21it/s]

💾 Saving progress at sample 3070
💾 Saving progress at sample 3080

 19%|█▊        | 3090/16500 [00:22<02:44, 81.44it/s]

💾 Saving progress at sample 3090
💾 Saving progress at sample 3100

 19%|█▉        | 3110/16500 [00:22<02:49, 79.11it/s]

💾 Saving progress at sample 3110
💾 Saving progress at sample 3120

 19%|█▉        | 3130/16500 [00:22<02:50, 78.40it/s]

💾 Saving progress at sample 3130
💾 Saving progress at sample 3140

 19%|█▉        | 3150/16500 [00:23<02:53, 76.75it/s]

💾 Saving progress at sample 3150
💾 Saving progress at sample 3160

 19%|█▉        | 3170/16500 [00:23<02:50, 78.13it/s]

💾 Saving progress at sample 3170
💾 Saving progress at sample 3180

 19%|█▉        | 3190/16500 [00:23<03:16, 67.84it/s]

💾 Saving progress at sample 3190
💾 Saving progress at sample 3200

 19%|█▉        | 3210/16500 [00:23<03:07, 71.04it/s]

💾 Saving progress at sample 3210
💾 Saving progress at sample 3220

 20%|█▉        | 3230/16500 [00:24<03:03, 72.22it/s]

💾 Saving progress at sample 3230
💾 Saving progress at sample 3240

 20%|█▉        | 3250/16500 [00:24<03:01, 72.90it/s]

💾 Saving progress at sample 3250
💾 Saving progress at sample 3260

 20%|█▉        | 3270/16500 [00:24<03:01, 72.82it/s]

💾 Saving progress at sample 3270
💾 Saving progress at sample 3280

 20%|█▉        | 3290/16500 [00:25<03:03, 72.15it/s]

💾 Saving progress at sample 3290
💾 Saving progress at sample 3300

 20%|██        | 3310/16500 [00:25<02:56, 74.55it/s]

💾 Saving progress at sample 3310
💾 Saving progress at sample 3320

 20%|██        | 3330/16500 [00:25<03:11, 68.71it/s]

💾 Saving progress at sample 3330
💾 Saving progress at sample 3340

 20%|██        | 3350/16500 [00:25<02:59, 73.25it/s]

💾 Saving progress at sample 3350
💾 Saving progress at sample 3360

 20%|██        | 3370/16500 [00:26<02:58, 73.38it/s]

💾 Saving progress at sample 3370
💾 Saving progress at sample 3380

 21%|██        | 3390/16500 [00:26<02:59, 73.17it/s]

💾 Saving progress at sample 3390
💾 Saving progress at sample 3400

 21%|██        | 3410/16500 [00:26<02:56, 74.12it/s]

💾 Saving progress at sample 3410
💾 Saving progress at sample 3420

 21%|██        | 3430/16500 [00:26<03:05, 70.28it/s]

💾 Saving progress at sample 3430
💾 Saving progress at sample 3440

 21%|██        | 3450/16500 [00:27<03:07, 69.46it/s]

💾 Saving progress at sample 3450
💾 Saving progress at sample 3460

 21%|██        | 3470/16500 [00:27<03:20, 65.15it/s]

💾 Saving progress at sample 3470
💾 Saving progress at sample 3480

 21%|██        | 3490/16500 [00:27<03:22, 64.14it/s]

💾 Saving progress at sample 3490
💾 Saving progress at sample 3500

 21%|██▏       | 3510/16500 [00:28<03:15, 66.36it/s]

💾 Saving progress at sample 3510
💾 Saving progress at sample 3520

 21%|██▏       | 3530/16500 [00:28<03:12, 67.23it/s]

💾 Saving progress at sample 3530
💾 Saving progress at sample 3540

 22%|██▏       | 3550/16500 [00:28<03:13, 66.79it/s]

💾 Saving progress at sample 3550
💾 Saving progress at sample 3560

 22%|██▏       | 3570/16500 [00:29<03:13, 66.77it/s]

💾 Saving progress at sample 3570
💾 Saving progress at sample 3580

 22%|██▏       | 3590/16500 [00:29<03:13, 66.68it/s]

💾 Saving progress at sample 3590
💾 Saving progress at sample 3600

 22%|██▏       | 3610/16500 [00:29<03:16, 65.75it/s]

💾 Saving progress at sample 3610
💾 Saving progress at sample 3620

 22%|██▏       | 3630/16500 [00:30<03:29, 61.49it/s]

💾 Saving progress at sample 3630
💾 Saving progress at sample 3640

 22%|██▏       | 3650/16500 [00:30<03:20, 64.14it/s]

💾 Saving progress at sample 3650
💾 Saving progress at sample 3660

 22%|██▏       | 3670/16500 [00:30<03:18, 64.66it/s]

💾 Saving progress at sample 3670
💾 Saving progress at sample 3680

 22%|██▏       | 3690/16500 [00:30<03:18, 64.55it/s]

💾 Saving progress at sample 3690
💾 Saving progress at sample 3700

 22%|██▏       | 3710/16500 [00:31<03:12, 66.28it/s]

💾 Saving progress at sample 3710
💾 Saving progress at sample 3720

 23%|██▎       | 3730/16500 [00:31<03:09, 67.24it/s]

💾 Saving progress at sample 3730
💾 Saving progress at sample 3740

 23%|██▎       | 3750/16500 [00:31<03:09, 67.15it/s]

💾 Saving progress at sample 3750
💾 Saving progress at sample 3760

 23%|██▎       | 3770/16500 [00:32<03:21, 63.31it/s]

💾 Saving progress at sample 3770
💾 Saving progress at sample 3780

 23%|██▎       | 3790/16500 [00:32<03:14, 65.21it/s]

💾 Saving progress at sample 3790
💾 Saving progress at sample 3800

 23%|██▎       | 3810/16500 [00:32<03:19, 63.53it/s]

💾 Saving progress at sample 3810
💾 Saving progress at sample 3820

 23%|██▎       | 3830/16500 [00:33<03:16, 64.38it/s]

💾 Saving progress at sample 3830
💾 Saving progress at sample 3840

 23%|██▎       | 3850/16500 [00:33<03:14, 64.98it/s]

💾 Saving progress at sample 3850
💾 Saving progress at sample 3860

 23%|██▎       | 3870/16500 [00:33<03:21, 62.84it/s]

💾 Saving progress at sample 3870
💾 Saving progress at sample 3880

 24%|██▎       | 3890/16500 [00:34<03:22, 62.32it/s]

💾 Saving progress at sample 3890
💾 Saving progress at sample 3900

 24%|██▎       | 3910/16500 [00:34<03:29, 60.07it/s]

💾 Saving progress at sample 3910
💾 Saving progress at sample 3920

 24%|██▍       | 3930/16500 [00:34<03:21, 62.50it/s]

💾 Saving progress at sample 3930
💾 Saving progress at sample 3940

 24%|██▍       | 3950/16500 [00:35<03:16, 63.99it/s]

💾 Saving progress at sample 3950
💾 Saving progress at sample 3960

 24%|██▍       | 3970/16500 [00:35<03:15, 64.14it/s]

💾 Saving progress at sample 3970
💾 Saving progress at sample 3980

 24%|██▍       | 3990/16500 [00:35<03:15, 63.88it/s]

💾 Saving progress at sample 3990
💾 Saving progress at sample 4000

 24%|██▍       | 4010/16500 [00:35<03:15, 63.75it/s]

💾 Saving progress at sample 4010
💾 Saving progress at sample 4020

 24%|██▍       | 4030/16500 [00:36<03:22, 61.57it/s]

💾 Saving progress at sample 4030
💾 Saving progress at sample 4040

 25%|██▍       | 4050/16500 [00:36<03:29, 59.40it/s]

💾 Saving progress at sample 4050
💾 Saving progress at sample 4060

 25%|██▍       | 4070/16500 [00:36<03:28, 59.54it/s]

💾 Saving progress at sample 4070
💾 Saving progress at sample 4080

 25%|██▍       | 4090/16500 [00:37<03:21, 61.45it/s]

💾 Saving progress at sample 4090
💾 Saving progress at sample 4100

 25%|██▍       | 4110/16500 [00:37<03:26, 59.88it/s]

💾 Saving progress at sample 4110
💾 Saving progress at sample 4120

 25%|██▌       | 4130/16500 [00:37<03:29, 58.98it/s]

💾 Saving progress at sample 4130
💾 Saving progress at sample 4140

 25%|██▌       | 4150/16500 [00:38<03:25, 60.08it/s]

💾 Saving progress at sample 4150
💾 Saving progress at sample 4160

 25%|██▌       | 4170/16500 [00:38<03:22, 60.75it/s]

💾 Saving progress at sample 4170
💾 Saving progress at sample 4180

 25%|██▌       | 4190/16500 [00:38<03:35, 57.07it/s]

💾 Saving progress at sample 4190
💾 Saving progress at sample 4200

 26%|██▌       | 4210/16500 [00:39<03:28, 59.08it/s]

💾 Saving progress at sample 4210
💾 Saving progress at sample 4220

 26%|██▌       | 4230/16500 [00:39<03:29, 58.50it/s]

💾 Saving progress at sample 4230
💾 Saving progress at sample 4240

 26%|██▌       | 4250/16500 [00:40<03:27, 58.99it/s]

💾 Saving progress at sample 4250
💾 Saving progress at sample 4260

 26%|██▌       | 4270/16500 [00:40<03:30, 58.13it/s]

💾 Saving progress at sample 4270
💾 Saving progress at sample 4280

 26%|██▌       | 4290/16500 [00:40<03:35, 56.74it/s]

💾 Saving progress at sample 4290
💾 Saving progress at sample 4300

 26%|██▌       | 4310/16500 [00:41<03:35, 56.48it/s]

💾 Saving progress at sample 4310
💾 Saving progress at sample 4320

 26%|██▌       | 4330/16500 [00:41<03:42, 54.82it/s]

💾 Saving progress at sample 4330
💾 Saving progress at sample 4340

 26%|██▋       | 4350/16500 [00:41<03:40, 55.12it/s]

💾 Saving progress at sample 4350
💾 Saving progress at sample 4360

 26%|██▋       | 4370/16500 [00:42<03:34, 56.66it/s]

💾 Saving progress at sample 4370
💾 Saving progress at sample 4380

 27%|██▋       | 4390/16500 [00:42<03:27, 58.48it/s]

💾 Saving progress at sample 4390
💾 Saving progress at sample 4400

 27%|██▋       | 4410/16500 [00:42<03:31, 57.27it/s]

💾 Saving progress at sample 4410
💾 Saving progress at sample 4420

 27%|██▋       | 4430/16500 [00:43<03:31, 57.19it/s]

💾 Saving progress at sample 4430
💾 Saving progress at sample 4440

 27%|██▋       | 4450/16500 [00:43<03:29, 57.38it/s]

💾 Saving progress at sample 4450
💾 Saving progress at sample 4460

 27%|██▋       | 4470/16500 [00:43<03:26, 58.21it/s]

💾 Saving progress at sample 4470
💾 Saving progress at sample 4480

 27%|██▋       | 4490/16500 [00:44<03:50, 52.18it/s]

💾 Saving progress at sample 4490
💾 Saving progress at sample 4500

 27%|██▋       | 4510/16500 [00:44<03:48, 52.59it/s]

💾 Saving progress at sample 4510
💾 Saving progress at sample 4520

 27%|██▋       | 4530/16500 [00:45<03:43, 53.60it/s]

💾 Saving progress at sample 4530
💾 Saving progress at sample 4540

 28%|██▊       | 4550/16500 [00:45<03:39, 54.49it/s]

💾 Saving progress at sample 4550
💾 Saving progress at sample 4560

 28%|██▊       | 4570/16500 [00:45<03:46, 52.62it/s]

💾 Saving progress at sample 4570
💾 Saving progress at sample 4580

 28%|██▊       | 4590/16500 [00:46<03:42, 53.54it/s]

💾 Saving progress at sample 4590
💾 Saving progress at sample 4600

 28%|██▊       | 4610/16500 [00:46<03:40, 53.85it/s]

💾 Saving progress at sample 4610
💾 Saving progress at sample 4620

 28%|██▊       | 4630/16500 [00:46<03:48, 52.06it/s]

💾 Saving progress at sample 4630
💾 Saving progress at sample 4640

 28%|██▊       | 4650/16500 [00:47<03:44, 52.79it/s]

💾 Saving progress at sample 4650
💾 Saving progress at sample 4660

 28%|██▊       | 4670/16500 [00:47<03:39, 53.96it/s]

💾 Saving progress at sample 4670
💾 Saving progress at sample 4680

 28%|██▊       | 4690/16500 [00:48<03:37, 54.36it/s]

💾 Saving progress at sample 4690
💾 Saving progress at sample 4700

 29%|██▊       | 4710/16500 [00:48<03:42, 52.95it/s]

💾 Saving progress at sample 4710
💾 Saving progress at sample 4720

 29%|██▊       | 4730/16500 [00:48<03:47, 51.82it/s]

💾 Saving progress at sample 4730
💾 Saving progress at sample 4740

 29%|██▉       | 4750/16500 [00:49<03:44, 52.28it/s]

💾 Saving progress at sample 4750
💾 Saving progress at sample 4760

 29%|██▉       | 4770/16500 [00:49<04:03, 48.11it/s]

💾 Saving progress at sample 4770
💾 Saving progress at sample 4780

 29%|██▉       | 4790/16500 [00:50<03:58, 49.18it/s]

💾 Saving progress at sample 4790
💾 Saving progress at sample 4800

 29%|██▉       | 4810/16500 [00:50<03:50, 50.70it/s]

💾 Saving progress at sample 4810
💾 Saving progress at sample 4820

 29%|██▉       | 4830/16500 [00:50<03:45, 51.67it/s]

💾 Saving progress at sample 4830
💾 Saving progress at sample 4840

 29%|██▉       | 4850/16500 [00:51<03:41, 52.63it/s]

💾 Saving progress at sample 4850
💾 Saving progress at sample 4860

 30%|██▉       | 4870/16500 [00:51<03:46, 51.33it/s]

💾 Saving progress at sample 4870
💾 Saving progress at sample 4880

 30%|██▉       | 4880/16500 [00:51<03:46, 51.40it/s]

💾 Saving progress at sample 4890

 30%|██▉       | 4900/16500 [00:52<03:54, 49.47it/s]

💾 Saving progress at sample 4900
💾 Saving progress at sample 4910

 30%|██▉       | 4910/16500 [00:52<04:06, 47.02it/s]

💾 Saving progress at sample 4920

 30%|██▉       | 4930/16500 [00:52<04:00, 48.19it/s]

💾 Saving progress at sample 4930
💾 Saving progress at sample 4940

 30%|███       | 4950/16500 [00:53<03:55, 49.10it/s]

💾 Saving progress at sample 4950
💾 Saving progress at sample 4960

 30%|███       | 4960/16500 [00:53<03:54, 49.31it/s]

💾 Saving progress at sample 4970

 30%|███       | 4980/16500 [00:53<03:52, 49.63it/s]

💾 Saving progress at sample 4980
💾 Saving progress at sample 4990

 30%|███       | 4990/16500 [00:54<03:51, 49.71it/s]

💾 Saving progress at sample 5000

 30%|███       | 5000/16500 [00:54<03:53, 49.18it/s]

💾 Saving progress at sample 5010

 30%|███       | 5020/16500 [00:54<03:54, 48.90it/s]

💾 Saving progress at sample 5020

 30%|███       | 5030/16500 [00:54<03:51, 49.46it/s]

💾 Saving progress at sample 5030
💾 Saving progress at sample 5040

 31%|███       | 5040/16500 [00:55<03:54, 48.85it/s]

💾 Saving progress at sample 5050

 31%|███       | 5050/16500 [00:55<04:21, 43.79it/s]

💾 Saving progress at sample 5060

 31%|███       | 5060/16500 [00:55<04:16, 44.61it/s]

💾 Saving progress at sample 5070

 31%|███       | 5070/16500 [00:55<04:11, 45.49it/s]

💾 Saving progress at sample 5080

 31%|███       | 5080/16500 [00:56<04:07, 46.18it/s]

💾 Saving progress at sample 5090

 31%|███       | 5100/16500 [00:56<04:00, 47.43it/s]

💾 Saving progress at sample 5100
💾 Saving progress at sample 5110

 31%|███       | 5110/16500 [00:56<04:02, 47.06it/s]

💾 Saving progress at sample 5120

 31%|███       | 5120/16500 [00:56<03:59, 47.43it/s]

💾 Saving progress at sample 5130

 31%|███       | 5140/16500 [00:57<03:56, 48.02it/s]

💾 Saving progress at sample 5140
💾 Saving progress at sample 5150

 31%|███       | 5150/16500 [00:57<03:51, 49.06it/s]

💾 Saving progress at sample 5160

 31%|███▏      | 5170/16500 [00:57<03:47, 49.70it/s]

💾 Saving progress at sample 5170
💾 Saving progress at sample 5180

 31%|███▏      | 5180/16500 [00:58<03:46, 49.91it/s]

💾 Saving progress at sample 5190

 32%|███▏      | 5200/16500 [00:58<03:48, 49.40it/s]

💾 Saving progress at sample 5200
💾 Saving progress at sample 5210

 32%|███▏      | 5210/16500 [00:58<03:53, 48.29it/s]

💾 Saving progress at sample 5220

 32%|███▏      | 5220/16500 [00:58<03:56, 47.79it/s]

💾 Saving progress at sample 5230

 32%|███▏      | 5230/16500 [00:59<03:59, 47.00it/s]

💾 Saving progress at sample 5240

 32%|███▏      | 5240/16500 [00:59<04:02, 46.37it/s]

💾 Saving progress at sample 5250

 32%|███▏      | 5250/16500 [00:59<04:02, 46.47it/s]

💾 Saving progress at sample 5260

 32%|███▏      | 5260/16500 [00:59<04:00, 46.65it/s]

💾 Saving progress at sample 5270

 32%|███▏      | 5280/16500 [01:00<03:57, 47.20it/s]

💾 Saving progress at sample 5280
💾 Saving progress at sample 5290

 32%|███▏      | 5290/16500 [01:00<03:57, 47.16it/s]

💾 Saving progress at sample 5300

 32%|███▏      | 5300/16500 [01:00<03:56, 47.26it/s]

💾 Saving progress at sample 5310

 32%|███▏      | 5310/16500 [01:00<04:00, 46.57it/s]

💾 Saving progress at sample 5320

 32%|███▏      | 5320/16500 [01:01<04:03, 45.89it/s]

💾 Saving progress at sample 5330

 32%|███▏      | 5330/16500 [01:01<04:03, 45.84it/s]

💾 Saving progress at sample 5340

 32%|███▏      | 5340/16500 [01:01<04:11, 44.31it/s]

💾 Saving progress at sample 5350

 32%|███▏      | 5350/16500 [01:01<04:10, 44.59it/s]

💾 Saving progress at sample 5360

 32%|███▏      | 5360/16500 [01:01<04:08, 44.82it/s]

💾 Saving progress at sample 5370

 33%|███▎      | 5370/16500 [01:02<04:07, 44.89it/s]

💾 Saving progress at sample 5380

 33%|███▎      | 5380/16500 [01:02<04:05, 45.22it/s]

💾 Saving progress at sample 5390

 33%|███▎      | 5390/16500 [01:02<04:05, 45.25it/s]

💾 Saving progress at sample 5400

 33%|███▎      | 5400/16500 [01:02<04:04, 45.35it/s]

💾 Saving progress at sample 5410

 33%|███▎      | 5410/16500 [01:03<04:07, 44.84it/s]

💾 Saving progress at sample 5420

 33%|███▎      | 5420/16500 [01:03<04:05, 45.07it/s]

💾 Saving progress at sample 5430

 33%|███▎      | 5430/16500 [01:03<04:10, 44.26it/s]

💾 Saving progress at sample 5440

 33%|███▎      | 5440/16500 [01:03<04:11, 44.01it/s]

💾 Saving progress at sample 5450

 33%|███▎      | 5450/16500 [01:03<04:10, 44.11it/s]

💾 Saving progress at sample 5460

 33%|███▎      | 5460/16500 [01:04<04:05, 44.98it/s]

💾 Saving progress at sample 5470

 33%|███▎      | 5470/16500 [01:04<04:04, 45.13it/s]

💾 Saving progress at sample 5480

 33%|███▎      | 5480/16500 [01:04<04:30, 40.79it/s]

💾 Saving progress at sample 5490

 33%|███▎      | 5490/16500 [01:04<04:17, 42.79it/s]

💾 Saving progress at sample 5500

 33%|███▎      | 5500/16500 [01:05<04:13, 43.39it/s]

💾 Saving progress at sample 5510

 33%|███▎      | 5510/16500 [01:05<04:10, 43.90it/s]

💾 Saving progress at sample 5520

 33%|███▎      | 5520/16500 [01:05<04:08, 44.20it/s]

💾 Saving progress at sample 5530

 34%|███▎      | 5530/16500 [01:05<04:06, 44.59it/s]

💾 Saving progress at sample 5540

 34%|███▎      | 5540/16500 [01:06<04:09, 43.98it/s]

💾 Saving progress at sample 5550

 34%|███▎      | 5550/16500 [01:06<04:05, 44.60it/s]

💾 Saving progress at sample 5560

 34%|███▎      | 5560/16500 [01:06<04:05, 44.65it/s]

💾 Saving progress at sample 5570

 34%|███▍      | 5570/16500 [01:06<04:05, 44.44it/s]

💾 Saving progress at sample 5580

 34%|███▍      | 5580/16500 [01:06<04:06, 44.38it/s]

💾 Saving progress at sample 5590

 34%|███▍      | 5590/16500 [01:07<04:07, 44.14it/s]

💾 Saving progress at sample 5600

 34%|███▍      | 5600/16500 [01:07<04:05, 44.34it/s]

💾 Saving progress at sample 5610

 34%|███▍      | 5610/16500 [01:07<04:05, 44.36it/s]

💾 Saving progress at sample 5620

 34%|███▍      | 5620/16500 [01:07<04:15, 42.51it/s]

💾 Saving progress at sample 5630

 34%|███▍      | 5630/16500 [01:08<04:13, 42.88it/s]

💾 Saving progress at sample 5640

 34%|███▍      | 5640/16500 [01:08<04:10, 43.29it/s]

💾 Saving progress at sample 5650

 34%|███▍      | 5650/16500 [01:08<04:09, 43.57it/s]

💾 Saving progress at sample 5660

 34%|███▍      | 5660/16500 [01:08<04:09, 43.53it/s]

💾 Saving progress at sample 5670

 34%|███▍      | 5670/16500 [01:09<04:09, 43.45it/s]

💾 Saving progress at sample 5680

 34%|███▍      | 5680/16500 [01:09<04:05, 44.14it/s]

💾 Saving progress at sample 5690

 34%|███▍      | 5690/16500 [01:09<04:02, 44.52it/s]

💾 Saving progress at sample 5700

 35%|███▍      | 5700/16500 [01:09<04:06, 43.84it/s]

💾 Saving progress at sample 5710

 35%|███▍      | 5710/16500 [01:09<04:04, 44.10it/s]

💾 Saving progress at sample 5720

 35%|███▍      | 5720/16500 [01:10<04:04, 44.04it/s]

💾 Saving progress at sample 5730

 35%|███▍      | 5730/16500 [01:10<04:04, 44.00it/s]

💾 Saving progress at sample 5740

 35%|███▍      | 5740/16500 [01:10<04:05, 43.78it/s]

💾 Saving progress at sample 5750

 35%|███▍      | 5750/16500 [01:10<04:08, 43.31it/s]

💾 Saving progress at sample 5760

 35%|███▍      | 5760/16500 [01:11<04:06, 43.63it/s]

💾 Saving progress at sample 5770

 35%|███▍      | 5770/16500 [01:11<04:08, 43.10it/s]

💾 Saving progress at sample 5780

 35%|███▌      | 5780/16500 [01:11<04:05, 43.59it/s]

💾 Saving progress at sample 5790

 35%|███▌      | 5790/16500 [01:11<04:08, 43.06it/s]

💾 Saving progress at sample 5800

 35%|███▌      | 5800/16500 [01:11<04:09, 42.97it/s]

💾 Saving progress at sample 5810

 35%|███▌      | 5810/16500 [01:12<04:10, 42.60it/s]

💾 Saving progress at sample 5820

 35%|███▌      | 5820/16500 [01:12<04:10, 42.59it/s]

💾 Saving progress at sample 5830

 35%|███▌      | 5830/16500 [01:12<04:11, 42.49it/s]

💾 Saving progress at sample 5840

 35%|███▌      | 5840/16500 [01:12<04:11, 42.37it/s]

💾 Saving progress at sample 5850

 35%|███▌      | 5850/16500 [01:13<04:13, 42.02it/s]

💾 Saving progress at sample 5860

 36%|███▌      | 5860/16500 [01:13<04:14, 41.76it/s]

💾 Saving progress at sample 5870

 36%|███▌      | 5870/16500 [01:13<04:16, 41.50it/s]

💾 Saving progress at sample 5880

 36%|███▌      | 5880/16500 [01:13<04:15, 41.60it/s]

💾 Saving progress at sample 5890

 36%|███▌      | 5890/16500 [01:14<04:16, 41.44it/s]

💾 Saving progress at sample 5900

 36%|███▌      | 5900/16500 [01:14<04:13, 41.75it/s]

💾 Saving progress at sample 5910

 36%|███▌      | 5910/16500 [01:14<04:45, 37.03it/s]

💾 Saving progress at sample 5920

 36%|███▌      | 5920/16500 [01:14<04:35, 38.41it/s]

💾 Saving progress at sample 5930

 36%|███▌      | 5930/16500 [01:15<04:28, 39.42it/s]

💾 Saving progress at sample 5940

 36%|███▌      | 5940/16500 [01:15<04:20, 40.54it/s]

💾 Saving progress at sample 5950

 36%|███▌      | 5950/16500 [01:15<04:18, 40.74it/s]

💾 Saving progress at sample 5960

 36%|███▌      | 5960/16500 [01:15<04:18, 40.73it/s]

💾 Saving progress at sample 5970

 36%|███▌      | 5970/16500 [01:16<04:19, 40.66it/s]

💾 Saving progress at sample 5980

 36%|███▌      | 5980/16500 [01:16<04:13, 41.51it/s]

💾 Saving progress at sample 5990

 36%|███▋      | 5990/16500 [01:16<04:11, 41.86it/s]

💾 Saving progress at sample 6000

 36%|███▋      | 6000/16500 [01:16<04:10, 41.87it/s]

💾 Saving progress at sample 6010

 36%|███▋      | 6010/16500 [01:17<04:10, 41.93it/s]

💾 Saving progress at sample 6020

 36%|███▋      | 6020/16500 [01:17<04:10, 41.92it/s]

💾 Saving progress at sample 6030

 37%|███▋      | 6030/16500 [01:17<04:08, 42.16it/s]

💾 Saving progress at sample 6040

 37%|███▋      | 6040/16500 [01:17<04:09, 42.00it/s]

💾 Saving progress at sample 6050

 37%|███▋      | 6050/16500 [01:18<04:23, 39.65it/s]

💾 Saving progress at sample 6060

 37%|███▋      | 6060/16500 [01:18<04:16, 40.73it/s]

💾 Saving progress at sample 6070

 37%|███▋      | 6070/16500 [01:18<04:13, 41.20it/s]

💾 Saving progress at sample 6080

 37%|███▋      | 6080/16500 [01:18<04:09, 41.77it/s]

💾 Saving progress at sample 6090

 37%|███▋      | 6090/16500 [01:19<04:12, 41.31it/s]

💾 Saving progress at sample 6100

 37%|███▋      | 6100/16500 [01:19<04:09, 41.62it/s]

💾 Saving progress at sample 6110

 37%|███▋      | 6110/16500 [01:19<04:08, 41.79it/s]

💾 Saving progress at sample 6120

 37%|███▋      | 6120/16500 [01:19<04:05, 42.22it/s]

💾 Saving progress at sample 6130

 37%|███▋      | 6130/16500 [01:19<04:03, 42.61it/s]

💾 Saving progress at sample 6140

 37%|███▋      | 6140/16500 [01:20<04:03, 42.61it/s]

💾 Saving progress at sample 6150

 37%|███▋      | 6150/16500 [01:20<04:03, 42.44it/s]

💾 Saving progress at sample 6160

 37%|███▋      | 6160/16500 [01:20<04:05, 42.13it/s]

💾 Saving progress at sample 6170

 37%|███▋      | 6170/16500 [01:20<04:07, 41.80it/s]

💾 Saving progress at sample 6180

 37%|███▋      | 6180/16500 [01:21<04:03, 42.38it/s]

💾 Saving progress at sample 6190

 38%|███▊      | 6190/16500 [01:21<04:04, 42.15it/s]

💾 Saving progress at sample 6200

 38%|███▊      | 6200/16500 [01:21<04:14, 40.53it/s]

💾 Saving progress at sample 6210

 38%|███▊      | 6210/16500 [01:21<04:14, 40.40it/s]

💾 Saving progress at sample 6220

 38%|███▊      | 6220/16500 [01:22<04:12, 40.65it/s]

💾 Saving progress at sample 6230

 38%|███▊      | 6230/16500 [01:22<04:10, 41.02it/s]

💾 Saving progress at sample 6240

 38%|███▊      | 6240/16500 [01:22<04:11, 40.77it/s]

💾 Saving progress at sample 6250

 38%|███▊      | 6250/16500 [01:22<04:14, 40.35it/s]

💾 Saving progress at sample 6260

 38%|███▊      | 6260/16500 [01:23<04:12, 40.54it/s]

💾 Saving progress at sample 6270

 38%|███▊      | 6270/16500 [01:23<04:11, 40.74it/s]

💾 Saving progress at sample 6280

 38%|███▊      | 6280/16500 [01:23<04:06, 41.45it/s]

💾 Saving progress at sample 6290

 38%|███▊      | 6290/16500 [01:23<04:10, 40.79it/s]

💾 Saving progress at sample 6300

 38%|███▊      | 6300/16500 [01:24<04:06, 41.32it/s]

💾 Saving progress at sample 6310

 38%|███▊      | 6310/16500 [01:24<04:04, 41.75it/s]

💾 Saving progress at sample 6320

 38%|███▊      | 6320/16500 [01:24<04:05, 41.40it/s]

💾 Saving progress at sample 6330

 38%|███▊      | 6330/16500 [01:24<04:07, 41.09it/s]

💾 Saving progress at sample 6340

 38%|███▊      | 6340/16500 [01:25<04:45, 35.57it/s]

💾 Saving progress at sample 6350

 38%|███▊      | 6350/16500 [01:25<04:38, 36.50it/s]

💾 Saving progress at sample 6360

 39%|███▊      | 6360/16500 [01:25<04:31, 37.37it/s]

💾 Saving progress at sample 6370

 39%|███▊      | 6370/16500 [01:26<04:30, 37.47it/s]

💾 Saving progress at sample 6380

 39%|███▊      | 6380/16500 [01:26<04:28, 37.69it/s]

💾 Saving progress at sample 6390

 39%|███▊      | 6390/16500 [01:26<04:33, 37.01it/s]

💾 Saving progress at sample 6400

 39%|███▉      | 6400/16500 [01:26<04:33, 36.89it/s]

💾 Saving progress at sample 6410

 39%|███▉      | 6410/16500 [01:27<04:29, 37.39it/s]

💾 Saving progress at sample 6420

 39%|███▉      | 6420/16500 [01:27<04:27, 37.72it/s]

💾 Saving progress at sample 6430

 39%|███▉      | 6430/16500 [01:27<04:22, 38.37it/s]

💾 Saving progress at sample 6440

 39%|███▉      | 6440/16500 [01:27<04:18, 38.99it/s]

💾 Saving progress at sample 6450

 39%|███▉      | 6450/16500 [01:28<04:13, 39.70it/s]

💾 Saving progress at sample 6460

 39%|███▉      | 6460/16500 [01:28<04:12, 39.70it/s]

💾 Saving progress at sample 6470

 39%|███▉      | 6470/16500 [01:28<04:16, 39.17it/s]

💾 Saving progress at sample 6480

 39%|███▉      | 6480/16500 [01:28<04:22, 38.11it/s]

💾 Saving progress at sample 6490

 39%|███▉      | 6490/16500 [01:29<04:23, 38.06it/s]

💾 Saving progress at sample 6500

 39%|███▉      | 6500/16500 [01:29<04:21, 38.31it/s]

💾 Saving progress at sample 6510

 39%|███▉      | 6510/16500 [01:29<04:23, 37.86it/s]

💾 Saving progress at sample 6520

 40%|███▉      | 6520/16500 [01:29<04:20, 38.36it/s]

💾 Saving progress at sample 6530

 40%|███▉      | 6530/16500 [01:30<04:20, 38.24it/s]

💾 Saving progress at sample 6540

 40%|███▉      | 6540/16500 [01:30<04:21, 38.06it/s]

💾 Saving progress at sample 6550

 40%|███▉      | 6550/16500 [01:30<04:20, 38.22it/s]

💾 Saving progress at sample 6560

 40%|███▉      | 6560/16500 [01:30<04:16, 38.68it/s]

💾 Saving progress at sample 6570

 40%|███▉      | 6570/16500 [01:31<04:13, 39.24it/s]

💾 Saving progress at sample 6580

 40%|███▉      | 6580/16500 [01:31<04:11, 39.40it/s]

💾 Saving progress at sample 6590

 40%|███▉      | 6590/16500 [01:31<04:11, 39.43it/s]

💾 Saving progress at sample 6600

 40%|████      | 6600/16500 [01:31<04:12, 39.18it/s]

💾 Saving progress at sample 6610

 40%|████      | 6610/16500 [01:32<04:19, 38.09it/s]

💾 Saving progress at sample 6620

 40%|████      | 6620/16500 [01:32<04:19, 38.03it/s]

💾 Saving progress at sample 6630

 40%|████      | 6630/16500 [01:32<04:25, 37.24it/s]

💾 Saving progress at sample 6640

 40%|████      | 6640/16500 [01:33<04:23, 37.38it/s]

💾 Saving progress at sample 6650

 40%|████      | 6650/16500 [01:33<04:19, 37.97it/s]

💾 Saving progress at sample 6660

 40%|████      | 6660/16500 [01:33<04:20, 37.84it/s]

💾 Saving progress at sample 6670

 40%|████      | 6670/16500 [01:33<04:21, 37.59it/s]

💾 Saving progress at sample 6680

 40%|████      | 6680/16500 [01:34<04:22, 37.43it/s]

💾 Saving progress at sample 6690

 41%|████      | 6690/16500 [01:34<04:19, 37.81it/s]

💾 Saving progress at sample 6700

 41%|████      | 6700/16500 [01:34<04:18, 37.87it/s]

💾 Saving progress at sample 6710

 41%|████      | 6710/16500 [01:34<04:23, 37.13it/s]

💾 Saving progress at sample 6720

 41%|████      | 6720/16500 [01:35<04:21, 37.46it/s]

💾 Saving progress at sample 6730

 41%|████      | 6730/16500 [01:35<04:19, 37.66it/s]

💾 Saving progress at sample 6740

 41%|████      | 6740/16500 [01:35<04:17, 37.91it/s]

💾 Saving progress at sample 6750

 41%|████      | 6750/16500 [01:35<04:18, 37.66it/s]

💾 Saving progress at sample 6760

 41%|████      | 6760/16500 [01:36<04:21, 37.31it/s]

💾 Saving progress at sample 6770

 41%|████      | 6770/16500 [01:36<04:30, 35.94it/s]

💾 Saving progress at sample 6780

 41%|████      | 6780/16500 [01:36<04:30, 35.94it/s]

💾 Saving progress at sample 6790

 41%|████      | 6790/16500 [01:37<04:26, 36.46it/s]

💾 Saving progress at sample 6800

 41%|████      | 6800/16500 [01:37<04:24, 36.69it/s]

💾 Saving progress at sample 6810

 41%|████▏     | 6810/16500 [01:37<04:26, 36.39it/s]

💾 Saving progress at sample 6820

 41%|████▏     | 6820/16500 [01:37<04:29, 35.95it/s]

💾 Saving progress at sample 6830

 41%|████▏     | 6830/16500 [01:38<04:27, 36.11it/s]

💾 Saving progress at sample 6840

 41%|████▏     | 6840/16500 [01:38<04:22, 36.76it/s]

💾 Saving progress at sample 6850

 42%|████▏     | 6850/16500 [01:38<04:24, 36.54it/s]

💾 Saving progress at sample 6860

 42%|████▏     | 6860/16500 [01:39<04:23, 36.61it/s]

💾 Saving progress at sample 6870

 42%|████▏     | 6870/16500 [01:39<04:19, 37.07it/s]

💾 Saving progress at sample 6880

 42%|████▏     | 6880/16500 [01:39<04:21, 36.81it/s]

💾 Saving progress at sample 6890

 42%|████▏     | 6890/16500 [01:39<04:20, 36.88it/s]

💾 Saving progress at sample 6900

 42%|████▏     | 6900/16500 [01:40<04:18, 37.15it/s]

💾 Saving progress at sample 6910

 42%|████▏     | 6910/16500 [01:40<04:27, 35.82it/s]

💾 Saving progress at sample 6920

 42%|████▏     | 6920/16500 [01:40<04:25, 36.06it/s]

💾 Saving progress at sample 6930

 42%|████▏     | 6930/16500 [01:40<04:24, 36.22it/s]

💾 Saving progress at sample 6940

 42%|████▏     | 6940/16500 [01:41<04:25, 35.96it/s]

💾 Saving progress at sample 6950

 42%|████▏     | 6950/16500 [01:41<04:27, 35.73it/s]

💾 Saving progress at sample 6960

 42%|████▏     | 6960/16500 [01:41<04:25, 35.94it/s]

💾 Saving progress at sample 6970

 42%|████▏     | 6970/16500 [01:42<04:22, 36.25it/s]

💾 Saving progress at sample 6980

 42%|████▏     | 6980/16500 [01:42<04:22, 36.28it/s]

💾 Saving progress at sample 6990

 42%|████▏     | 6990/16500 [01:42<04:25, 35.78it/s]

💾 Saving progress at sample 7000

 42%|████▏     | 7000/16500 [01:42<04:22, 36.23it/s]

💾 Saving progress at sample 7010

 42%|████▏     | 7010/16500 [01:43<04:22, 36.16it/s]

💾 Saving progress at sample 7020

 43%|████▎     | 7020/16500 [01:43<04:18, 36.68it/s]

💾 Saving progress at sample 7030

 43%|████▎     | 7030/16500 [01:43<04:25, 35.63it/s]

💾 Saving progress at sample 7040

 43%|████▎     | 7040/16500 [01:43<04:27, 35.41it/s]

💾 Saving progress at sample 7050

 43%|████▎     | 7050/16500 [01:44<04:27, 35.37it/s]

💾 Saving progress at sample 7060

 43%|████▎     | 7060/16500 [01:44<04:48, 32.67it/s]

💾 Saving progress at sample 7070

 43%|████▎     | 7070/16500 [01:44<04:43, 33.30it/s]

💾 Saving progress at sample 7080

 43%|████▎     | 7080/16500 [01:45<04:34, 34.32it/s]

💾 Saving progress at sample 7090

 43%|████▎     | 7090/16500 [01:45<04:29, 34.97it/s]

💾 Saving progress at sample 7100

 43%|████▎     | 7100/16500 [01:45<04:28, 35.00it/s]

💾 Saving progress at sample 7110

 43%|████▎     | 7110/16500 [01:46<04:29, 34.90it/s]

💾 Saving progress at sample 7120

 43%|████▎     | 7120/16500 [01:46<04:26, 35.17it/s]

💾 Saving progress at sample 7130

 43%|████▎     | 7130/16500 [01:46<04:26, 35.18it/s]

💾 Saving progress at sample 7140

 43%|████▎     | 7140/16500 [01:46<04:27, 34.96it/s]

💾 Saving progress at sample 7150

 43%|████▎     | 7150/16500 [01:47<04:30, 34.59it/s]

💾 Saving progress at sample 7160

 43%|████▎     | 7160/16500 [01:47<04:29, 34.62it/s]

💾 Saving progress at sample 7170

 43%|████▎     | 7170/16500 [01:47<04:27, 34.84it/s]

💾 Saving progress at sample 7180

 44%|████▎     | 7180/16500 [01:48<04:28, 34.65it/s]

💾 Saving progress at sample 7190

 44%|████▎     | 7190/16500 [01:48<04:25, 35.07it/s]

💾 Saving progress at sample 7200

 44%|████▎     | 7200/16500 [01:48<04:44, 32.74it/s]

💾 Saving progress at sample 7210

 44%|████▎     | 7210/16500 [01:48<04:35, 33.75it/s]

💾 Saving progress at sample 7220

 44%|████▍     | 7220/16500 [01:49<04:32, 34.06it/s]

💾 Saving progress at sample 7230

 44%|████▍     | 7230/16500 [01:49<04:29, 34.45it/s]

💾 Saving progress at sample 7240

 44%|████▍     | 7240/16500 [01:49<04:32, 33.99it/s]

💾 Saving progress at sample 7250

 44%|████▍     | 7250/16500 [01:50<04:32, 33.97it/s]

💾 Saving progress at sample 7260

 44%|████▍     | 7260/16500 [01:50<04:27, 34.52it/s]

💾 Saving progress at sample 7270

 44%|████▍     | 7270/16500 [01:50<04:29, 34.29it/s]

💾 Saving progress at sample 7280

 44%|████▍     | 7280/16500 [01:51<04:32, 33.89it/s]

💾 Saving progress at sample 7290

 44%|████▍     | 7290/16500 [01:51<04:33, 33.71it/s]

💾 Saving progress at sample 7300

 44%|████▍     | 7300/16500 [01:51<04:28, 34.22it/s]

💾 Saving progress at sample 7310

 44%|████▍     | 7310/16500 [01:51<04:32, 33.78it/s]

💾 Saving progress at sample 7320

 44%|████▍     | 7320/16500 [01:52<04:29, 34.08it/s]

💾 Saving progress at sample 7330

 44%|████▍     | 7330/16500 [01:52<04:26, 34.47it/s]

💾 Saving progress at sample 7340

 44%|████▍     | 7340/16500 [01:52<04:35, 33.27it/s]

💾 Saving progress at sample 7350

 45%|████▍     | 7350/16500 [01:53<04:34, 33.34it/s]

💾 Saving progress at sample 7360

 45%|████▍     | 7360/16500 [01:53<04:31, 33.61it/s]

💾 Saving progress at sample 7370

 45%|████▍     | 7370/16500 [01:53<04:28, 33.97it/s]

💾 Saving progress at sample 7380

 45%|████▍     | 7380/16500 [01:53<04:28, 34.02it/s]

💾 Saving progress at sample 7390

 45%|████▍     | 7390/16500 [01:54<04:27, 34.08it/s]

💾 Saving progress at sample 7400

 45%|████▍     | 7400/16500 [01:54<04:27, 34.00it/s]

💾 Saving progress at sample 7410

 45%|████▍     | 7410/16500 [01:54<04:28, 33.82it/s]

💾 Saving progress at sample 7420

 45%|████▍     | 7420/16500 [01:55<04:28, 33.77it/s]

💾 Saving progress at sample 7430

 45%|████▌     | 7430/16500 [01:55<04:27, 33.95it/s]

💾 Saving progress at sample 7440

 45%|████▌     | 7440/16500 [01:55<04:28, 33.80it/s]

💾 Saving progress at sample 7450

 45%|████▌     | 7450/16500 [01:56<04:28, 33.67it/s]

💾 Saving progress at sample 7460

 45%|████▌     | 7460/16500 [01:56<04:24, 34.17it/s]

💾 Saving progress at sample 7470

 45%|████▌     | 7470/16500 [01:56<04:26, 33.93it/s]

💾 Saving progress at sample 7480

 45%|████▌     | 7480/16500 [01:56<04:26, 33.82it/s]

💾 Saving progress at sample 7490

 45%|████▌     | 7490/16500 [01:57<04:24, 34.03it/s]

💾 Saving progress at sample 7500

 45%|████▌     | 7500/16500 [01:57<04:20, 34.59it/s]

💾 Saving progress at sample 7510

 46%|████▌     | 7510/16500 [01:57<04:21, 34.34it/s]

💾 Saving progress at sample 7520

 46%|████▌     | 7520/16500 [01:58<04:17, 34.85it/s]

💾 Saving progress at sample 7530

 46%|████▌     | 7530/16500 [01:58<04:15, 35.13it/s]

💾 Saving progress at sample 7540

 46%|████▌     | 7540/16500 [01:58<04:20, 34.42it/s]

💾 Saving progress at sample 7550

 46%|████▌     | 7550/16500 [01:58<04:20, 34.40it/s]

💾 Saving progress at sample 7560

 46%|████▌     | 7560/16500 [01:59<04:21, 34.23it/s]

💾 Saving progress at sample 7570

 46%|████▌     | 7570/16500 [01:59<04:27, 33.32it/s]

💾 Saving progress at sample 7580

 46%|████▌     | 7580/16500 [01:59<04:30, 33.02it/s]

💾 Saving progress at sample 7590

 46%|████▌     | 7590/16500 [02:00<04:36, 32.25it/s]

💾 Saving progress at sample 7600

 46%|████▌     | 7600/16500 [02:00<04:32, 32.60it/s]

💾 Saving progress at sample 7610

 46%|████▌     | 7610/16500 [02:00<04:39, 31.77it/s]

💾 Saving progress at sample 7620

 46%|████▌     | 7620/16500 [02:01<04:42, 31.41it/s]

💾 Saving progress at sample 7630

 46%|████▌     | 7630/16500 [02:01<04:42, 31.35it/s]

💾 Saving progress at sample 7640

 46%|████▋     | 7640/16500 [02:01<04:41, 31.48it/s]

💾 Saving progress at sample 7650

 46%|████▋     | 7650/16500 [02:02<04:39, 31.69it/s]

💾 Saving progress at sample 7660

 46%|████▋     | 7660/16500 [02:02<04:37, 31.81it/s]

💾 Saving progress at sample 7670

 46%|████▋     | 7670/16500 [02:02<04:31, 32.50it/s]

💾 Saving progress at sample 7680

 47%|████▋     | 7680/16500 [02:02<04:25, 33.18it/s]

💾 Saving progress at sample 7690

 47%|████▋     | 7690/16500 [02:03<04:25, 33.20it/s]

💾 Saving progress at sample 7700

 47%|████▋     | 7700/16500 [02:03<04:24, 33.32it/s]

💾 Saving progress at sample 7710

 47%|████▋     | 7710/16500 [02:03<04:23, 33.38it/s]

💾 Saving progress at sample 7720

 47%|████▋     | 7720/16500 [02:04<04:23, 33.35it/s]

💾 Saving progress at sample 7730

 47%|████▋     | 7730/16500 [02:04<04:21, 33.58it/s]

💾 Saving progress at sample 7740

 47%|████▋     | 7740/16500 [02:04<04:22, 33.37it/s]

💾 Saving progress at sample 7750

 47%|████▋     | 7750/16500 [02:05<04:23, 33.15it/s]

💾 Saving progress at sample 7760

 47%|████▋     | 7760/16500 [02:05<04:23, 33.19it/s]

💾 Saving progress at sample 7770

 47%|████▋     | 7770/16500 [02:05<04:32, 32.03it/s]

💾 Saving progress at sample 7780

 47%|████▋     | 7780/16500 [02:06<04:29, 32.38it/s]

💾 Saving progress at sample 7790

 47%|████▋     | 7790/16500 [02:06<04:28, 32.49it/s]

💾 Saving progress at sample 7800

 47%|████▋     | 7800/16500 [02:06<04:30, 32.11it/s]

💾 Saving progress at sample 7810

 47%|████▋     | 7810/16500 [02:06<04:32, 31.86it/s]

💾 Saving progress at sample 7820

 47%|████▋     | 7820/16500 [02:07<04:30, 32.08it/s]

💾 Saving progress at sample 7830

 47%|████▋     | 7830/16500 [02:07<04:29, 32.18it/s]

💾 Saving progress at sample 7840

 48%|████▊     | 7840/16500 [02:07<04:28, 32.31it/s]

💾 Saving progress at sample 7850

 48%|████▊     | 7850/16500 [02:08<04:23, 32.81it/s]

💾 Saving progress at sample 7860

 48%|████▊     | 7860/16500 [02:08<04:25, 32.60it/s]

💾 Saving progress at sample 7870

 48%|████▊     | 7870/16500 [02:08<04:24, 32.64it/s]

💾 Saving progress at sample 7880

 48%|████▊     | 7880/16500 [02:09<04:31, 31.76it/s]

💾 Saving progress at sample 7890

 48%|████▊     | 7890/16500 [02:09<04:29, 31.90it/s]

💾 Saving progress at sample 7900

 48%|████▊     | 7900/16500 [02:09<04:28, 32.04it/s]

💾 Saving progress at sample 7910

 48%|████▊     | 7910/16500 [02:10<04:26, 32.24it/s]

💾 Saving progress at sample 7920

 48%|████▊     | 7920/16500 [02:10<04:29, 31.81it/s]

💾 Saving progress at sample 7930

 48%|████▊     | 7930/16500 [02:10<04:27, 32.08it/s]

💾 Saving progress at sample 7940

 48%|████▊     | 7940/16500 [02:11<04:29, 31.78it/s]

💾 Saving progress at sample 7950

 48%|████▊     | 7950/16500 [02:11<04:32, 31.38it/s]

💾 Saving progress at sample 7960

 48%|████▊     | 7960/16500 [02:11<04:26, 32.04it/s]

💾 Saving progress at sample 7970

 48%|████▊     | 7970/16500 [02:11<04:23, 32.39it/s]

💾 Saving progress at sample 7980

 48%|████▊     | 7980/16500 [02:12<04:26, 31.91it/s]

💾 Saving progress at sample 7990

 48%|████▊     | 7990/16500 [02:12<04:26, 31.90it/s]

💾 Saving progress at sample 8000

 48%|████▊     | 8000/16500 [02:12<04:24, 32.17it/s]

💾 Saving progress at sample 8010

 49%|████▊     | 8010/16500 [02:13<04:24, 32.08it/s]

💾 Saving progress at sample 8020

 49%|████▊     | 8020/16500 [02:13<04:27, 31.74it/s]

💾 Saving progress at sample 8030

 49%|████▊     | 8030/16500 [02:13<04:30, 31.35it/s]

💾 Saving progress at sample 8040

 49%|████▊     | 8040/16500 [02:14<04:31, 31.17it/s]

💾 Saving progress at sample 8050

 49%|████▉     | 8050/16500 [02:14<04:30, 31.23it/s]

💾 Saving progress at sample 8060

 49%|████▉     | 8060/16500 [02:14<04:48, 29.21it/s]

💾 Saving progress at sample 8070

 49%|████▉     | 8070/16500 [02:15<04:41, 29.90it/s]

💾 Saving progress at sample 8080

 49%|████▉     | 8080/16500 [02:15<04:35, 30.51it/s]

💾 Saving progress at sample 8090

 49%|████▉     | 8090/16500 [02:15<04:36, 30.38it/s]

💾 Saving progress at sample 8100

 49%|████▉     | 8100/16500 [02:16<04:35, 30.52it/s]

💾 Saving progress at sample 8110

 49%|████▉     | 8110/16500 [02:16<04:31, 30.86it/s]

💾 Saving progress at sample 8120

 49%|████▉     | 8120/16500 [02:16<04:30, 30.98it/s]

💾 Saving progress at sample 8130

 49%|████▉     | 8130/16500 [02:17<04:31, 30.88it/s]

💾 Saving progress at sample 8140

 49%|████▉     | 8140/16500 [02:17<04:29, 30.99it/s]

💾 Saving progress at sample 8150

 49%|████▉     | 8150/16500 [02:17<04:29, 30.95it/s]

💾 Saving progress at sample 8160

 49%|████▉     | 8160/16500 [02:18<04:29, 30.95it/s]

💾 Saving progress at sample 8170

 50%|████▉     | 8170/16500 [02:18<04:28, 31.06it/s]

💾 Saving progress at sample 8180

 50%|████▉     | 8180/16500 [02:18<04:24, 31.43it/s]

💾 Saving progress at sample 8190

 50%|████▉     | 8190/16500 [02:19<04:22, 31.63it/s]

💾 Saving progress at sample 8200

 50%|████▉     | 8200/16500 [02:19<04:47, 28.87it/s]

💾 Saving progress at sample 8210

 50%|████▉     | 8210/16500 [02:19<04:40, 29.54it/s]

💾 Saving progress at sample 8220

 50%|████▉     | 8220/16500 [02:20<04:35, 30.03it/s]

💾 Saving progress at sample 8230

 50%|████▉     | 8230/16500 [02:20<04:30, 30.58it/s]

💾 Saving progress at sample 8240

 50%|████▉     | 8240/16500 [02:20<04:26, 30.95it/s]

💾 Saving progress at sample 8250

 50%|█████     | 8250/16500 [02:21<04:25, 31.11it/s]

💾 Saving progress at sample 8260

 50%|█████     | 8260/16500 [02:21<04:26, 30.95it/s]

💾 Saving progress at sample 8270

 50%|█████     | 8270/16500 [02:21<04:26, 30.88it/s]

💾 Saving progress at sample 8280

 50%|█████     | 8280/16500 [02:22<04:24, 31.02it/s]

💾 Saving progress at sample 8290

 50%|█████     | 8290/16500 [02:22<04:24, 30.98it/s]

💾 Saving progress at sample 8300

 50%|█████     | 8300/16500 [02:22<04:28, 30.53it/s]

💾 Saving progress at sample 8310

 50%|█████     | 8310/16500 [02:22<04:27, 30.64it/s]

💾 Saving progress at sample 8320

 50%|█████     | 8320/16500 [02:23<04:28, 30.50it/s]

💾 Saving progress at sample 8330

 50%|█████     | 8330/16500 [02:23<04:27, 30.59it/s]

💾 Saving progress at sample 8340

 51%|█████     | 8340/16500 [02:23<04:22, 31.04it/s]

💾 Saving progress at sample 8350

 51%|█████     | 8350/16500 [02:24<04:41, 28.95it/s]

💾 Saving progress at sample 8360

 51%|█████     | 8360/16500 [02:24<04:33, 29.74it/s]

💾 Saving progress at sample 8370

 51%|█████     | 8370/16500 [02:24<04:29, 30.14it/s]

💾 Saving progress at sample 8380

 51%|█████     | 8380/16500 [02:25<04:28, 30.22it/s]

💾 Saving progress at sample 8390

 51%|█████     | 8390/16500 [02:25<04:29, 30.09it/s]

💾 Saving progress at sample 8400

 51%|█████     | 8400/16500 [02:25<04:27, 30.24it/s]

💾 Saving progress at sample 8410

 51%|█████     | 8410/16500 [02:26<04:26, 30.30it/s]

💾 Saving progress at sample 8420

 51%|█████     | 8420/16500 [02:26<04:29, 30.03it/s]

💾 Saving progress at sample 8430

 51%|█████     | 8430/16500 [02:26<04:29, 29.90it/s]

💾 Saving progress at sample 8440

 51%|█████     | 8440/16500 [02:27<04:30, 29.82it/s]

💾 Saving progress at sample 8450

 51%|█████     | 8450/16500 [02:27<04:35, 29.17it/s]

💾 Saving progress at sample 8460

 51%|█████▏    | 8460/16500 [02:28<04:37, 28.95it/s]

💾 Saving progress at sample 8470

 51%|█████▏    | 8470/16500 [02:28<04:36, 29.05it/s]

💾 Saving progress at sample 8480

 51%|█████▏    | 8480/16500 [02:28<04:34, 29.19it/s]

💾 Saving progress at sample 8490

 51%|█████▏    | 8490/16500 [02:29<04:40, 28.51it/s]

💾 Saving progress at sample 8500

 52%|█████▏    | 8500/16500 [02:29<04:37, 28.86it/s]

💾 Saving progress at sample 8510

 52%|█████▏    | 8510/16500 [02:29<04:34, 29.07it/s]

💾 Saving progress at sample 8520

 52%|█████▏    | 8520/16500 [02:30<04:32, 29.33it/s]

💾 Saving progress at sample 8530

 52%|█████▏    | 8530/16500 [02:30<04:31, 29.40it/s]

💾 Saving progress at sample 8540

 52%|█████▏    | 8540/16500 [02:30<04:30, 29.44it/s]

💾 Saving progress at sample 8550

 52%|█████▏    | 8550/16500 [02:31<04:29, 29.53it/s]

💾 Saving progress at sample 8560

 52%|█████▏    | 8560/16500 [02:31<04:33, 28.99it/s]

💾 Saving progress at sample 8570

 52%|█████▏    | 8570/16500 [02:31<04:37, 28.61it/s]

💾 Saving progress at sample 8580

 52%|█████▏    | 8580/16500 [02:32<04:38, 28.46it/s]

💾 Saving progress at sample 8590

 52%|█████▏    | 8590/16500 [02:32<04:39, 28.33it/s]

💾 Saving progress at sample 8600

 52%|█████▏    | 8600/16500 [02:32<04:36, 28.54it/s]

💾 Saving progress at sample 8610

 52%|█████▏    | 8610/16500 [02:33<04:35, 28.65it/s]

💾 Saving progress at sample 8620

 52%|█████▏    | 8620/16500 [02:33<04:37, 28.40it/s]

💾 Saving progress at sample 8630

 52%|█████▏    | 8630/16500 [02:34<04:57, 26.47it/s]

💾 Saving progress at sample 8640

 52%|█████▏    | 8640/16500 [02:34<04:51, 27.00it/s]

💾 Saving progress at sample 8650

 52%|█████▏    | 8650/16500 [02:34<04:45, 27.48it/s]

💾 Saving progress at sample 8660

 52%|█████▏    | 8660/16500 [02:35<04:46, 27.33it/s]

💾 Saving progress at sample 8670

 53%|█████▎    | 8670/16500 [02:35<04:48, 27.13it/s]

💾 Saving progress at sample 8680

 53%|█████▎    | 8680/16500 [02:35<04:45, 27.41it/s]

💾 Saving progress at sample 8690

 53%|█████▎    | 8690/16500 [02:36<04:42, 27.64it/s]

💾 Saving progress at sample 8700

 53%|█████▎    | 8700/16500 [02:36<04:40, 27.83it/s]

💾 Saving progress at sample 8710

 53%|█████▎    | 8710/16500 [02:36<04:41, 27.69it/s]

💾 Saving progress at sample 8720

 53%|█████▎    | 8720/16500 [02:37<04:40, 27.72it/s]

💾 Saving progress at sample 8730

 53%|█████▎    | 8730/16500 [02:37<04:46, 27.12it/s]

💾 Saving progress at sample 8740

 53%|█████▎    | 8740/16500 [02:38<04:45, 27.20it/s]

💾 Saving progress at sample 8750

 53%|█████▎    | 8750/16500 [02:38<04:40, 27.65it/s]

💾 Saving progress at sample 8760

 53%|█████▎    | 8760/16500 [02:38<04:40, 27.61it/s]

💾 Saving progress at sample 8770

 53%|█████▎    | 8770/16500 [02:39<04:41, 27.48it/s]

💾 Saving progress at sample 8780

 53%|█████▎    | 8780/16500 [02:39<04:37, 27.80it/s]

💾 Saving progress at sample 8790

 53%|█████▎    | 8790/16500 [02:39<04:36, 27.88it/s]

💾 Saving progress at sample 8800

 53%|█████▎    | 8800/16500 [02:40<04:36, 27.80it/s]

💾 Saving progress at sample 8810

 53%|█████▎    | 8810/16500 [02:40<04:36, 27.80it/s]

💾 Saving progress at sample 8820

 53%|█████▎    | 8820/16500 [02:40<04:37, 27.63it/s]

💾 Saving progress at sample 8830

 54%|█████▎    | 8830/16500 [02:41<04:40, 27.31it/s]

💾 Saving progress at sample 8840

 54%|█████▎    | 8840/16500 [02:41<04:39, 27.38it/s]

💾 Saving progress at sample 8850

 54%|█████▎    | 8850/16500 [02:41<04:37, 27.52it/s]

💾 Saving progress at sample 8860

 54%|█████▎    | 8860/16500 [02:42<04:36, 27.65it/s]

💾 Saving progress at sample 8870

 54%|█████▍    | 8870/16500 [02:42<04:35, 27.69it/s]

💾 Saving progress at sample 8880

 54%|█████▍    | 8880/16500 [02:43<04:35, 27.69it/s]

💾 Saving progress at sample 8890

 54%|█████▍    | 8890/16500 [02:43<04:33, 27.80it/s]

💾 Saving progress at sample 8900

 54%|█████▍    | 8900/16500 [02:43<04:34, 27.69it/s]

💾 Saving progress at sample 8910

 54%|█████▍    | 8910/16500 [02:44<04:33, 27.75it/s]

💾 Saving progress at sample 8920

 54%|█████▍    | 8920/16500 [02:44<04:52, 25.91it/s]

💾 Saving progress at sample 8930

 54%|█████▍    | 8930/16500 [02:44<04:43, 26.73it/s]

💾 Saving progress at sample 8940

 54%|█████▍    | 8940/16500 [02:45<04:40, 26.99it/s]

💾 Saving progress at sample 8950

 54%|█████▍    | 8950/16500 [02:45<04:36, 27.30it/s]

💾 Saving progress at sample 8960

 54%|█████▍    | 8960/16500 [02:46<04:31, 27.79it/s]

💾 Saving progress at sample 8970

 54%|█████▍    | 8970/16500 [02:46<04:34, 27.41it/s]

💾 Saving progress at sample 8980

 54%|█████▍    | 8980/16500 [02:46<04:36, 27.24it/s]

💾 Saving progress at sample 8990

 54%|█████▍    | 8990/16500 [02:47<04:36, 27.12it/s]

💾 Saving progress at sample 9000

 55%|█████▍    | 9000/16500 [02:47<04:35, 27.25it/s]

💾 Saving progress at sample 9010

 55%|█████▍    | 9010/16500 [02:47<04:36, 27.07it/s]

💾 Saving progress at sample 9020

 55%|█████▍    | 9020/16500 [02:48<04:31, 27.54it/s]

💾 Saving progress at sample 9030

 55%|█████▍    | 9030/16500 [02:48<04:22, 28.41it/s]

💾 Saving progress at sample 9040

 55%|█████▍    | 9040/16500 [02:48<04:23, 28.34it/s]

💾 Saving progress at sample 9050

 55%|█████▍    | 9050/16500 [02:49<04:23, 28.32it/s]

💾 Saving progress at sample 9060

 55%|█████▍    | 9060/16500 [02:49<04:45, 26.09it/s]

💾 Saving progress at sample 9070

 55%|█████▍    | 9070/16500 [02:50<04:44, 26.11it/s]

💾 Saving progress at sample 9080

 55%|█████▌    | 9080/16500 [02:50<04:37, 26.78it/s]

💾 Saving progress at sample 9090

 55%|█████▌    | 9090/16500 [02:50<04:37, 26.70it/s]

💾 Saving progress at sample 9100

 55%|█████▌    | 9100/16500 [02:51<04:35, 26.84it/s]

💾 Saving progress at sample 9110

 55%|█████▌    | 9110/16500 [02:51<04:35, 26.86it/s]

💾 Saving progress at sample 9120

 55%|█████▌    | 9120/16500 [02:51<04:35, 26.81it/s]

💾 Saving progress at sample 9130

 55%|█████▌    | 9130/16500 [02:52<04:31, 27.18it/s]

💾 Saving progress at sample 9140

 55%|█████▌    | 9140/16500 [02:52<04:29, 27.33it/s]

💾 Saving progress at sample 9150

 55%|█████▌    | 9150/16500 [02:53<04:27, 27.51it/s]

💾 Saving progress at sample 9160

 56%|█████▌    | 9160/16500 [02:53<04:24, 27.73it/s]

💾 Saving progress at sample 9170

 56%|█████▌    | 9170/16500 [02:53<04:26, 27.46it/s]

💾 Saving progress at sample 9180

 56%|█████▌    | 9180/16500 [02:54<04:26, 27.42it/s]

💾 Saving progress at sample 9190

 56%|█████▌    | 9190/16500 [02:54<04:28, 27.26it/s]

💾 Saving progress at sample 9200

 56%|█████▌    | 9200/16500 [02:54<04:25, 27.46it/s]

💾 Saving progress at sample 9210

 56%|█████▌    | 9210/16500 [02:55<04:52, 24.90it/s]

💾 Saving progress at sample 9220

 56%|█████▌    | 9220/16500 [02:55<04:47, 25.33it/s]

💾 Saving progress at sample 9230

 56%|█████▌    | 9230/16500 [02:56<04:39, 26.06it/s]

💾 Saving progress at sample 9240

 56%|█████▌    | 9240/16500 [02:56<04:30, 26.81it/s]

💾 Saving progress at sample 9250

 56%|█████▌    | 9250/16500 [02:56<04:29, 26.94it/s]

💾 Saving progress at sample 9260

 56%|█████▌    | 9260/16500 [02:57<04:27, 27.02it/s]

💾 Saving progress at sample 9270

 56%|█████▌    | 9270/16500 [02:57<04:28, 26.95it/s]

💾 Saving progress at sample 9280

 56%|█████▌    | 9280/16500 [02:57<04:28, 26.85it/s]

💾 Saving progress at sample 9290

 56%|█████▋    | 9290/16500 [02:58<04:31, 26.60it/s]

💾 Saving progress at sample 9300

 56%|█████▋    | 9300/16500 [02:58<04:29, 26.74it/s]

💾 Saving progress at sample 9310

 56%|█████▋    | 9310/16500 [02:58<04:26, 26.99it/s]

💾 Saving progress at sample 9320

 56%|█████▋    | 9320/16500 [02:59<04:24, 27.12it/s]

💾 Saving progress at sample 9330

 57%|█████▋    | 9330/16500 [02:59<04:25, 27.02it/s]

💾 Saving progress at sample 9340

 57%|█████▋    | 9340/16500 [03:00<04:25, 26.93it/s]

💾 Saving progress at sample 9350

 57%|█████▋    | 9350/16500 [03:00<04:42, 25.35it/s]

💾 Saving progress at sample 9360

 57%|█████▋    | 9360/16500 [03:00<04:35, 25.94it/s]

💾 Saving progress at sample 9370

 57%|█████▋    | 9370/16500 [03:01<04:31, 26.29it/s]

💾 Saving progress at sample 9380

 57%|█████▋    | 9380/16500 [03:01<04:32, 26.10it/s]

💾 Saving progress at sample 9390

 57%|█████▋    | 9390/16500 [03:02<04:35, 25.84it/s]

💾 Saving progress at sample 9400

 57%|█████▋    | 9400/16500 [03:02<04:33, 26.00it/s]

💾 Saving progress at sample 9410

 57%|█████▋    | 9410/16500 [03:02<04:33, 25.89it/s]

💾 Saving progress at sample 9420

 57%|█████▋    | 9420/16500 [03:03<04:34, 25.80it/s]

💾 Saving progress at sample 9430

 57%|█████▋    | 9430/16500 [03:03<04:28, 26.33it/s]

💾 Saving progress at sample 9440

 57%|█████▋    | 9440/16500 [03:03<04:26, 26.46it/s]

💾 Saving progress at sample 9450

 57%|█████▋    | 9450/16500 [03:04<04:26, 26.44it/s]

💾 Saving progress at sample 9460

 57%|█████▋    | 9460/16500 [03:04<04:26, 26.41it/s]

💾 Saving progress at sample 9470

 57%|█████▋    | 9470/16500 [03:05<04:27, 26.32it/s]

💾 Saving progress at sample 9480

 57%|█████▋    | 9480/16500 [03:05<04:26, 26.35it/s]

💾 Saving progress at sample 9490

 58%|█████▊    | 9490/16500 [03:05<04:32, 25.73it/s]

💾 Saving progress at sample 9500

 58%|█████▊    | 9500/16500 [03:06<04:28, 26.10it/s]

💾 Saving progress at sample 9510

 58%|█████▊    | 9510/16500 [03:06<04:27, 26.17it/s]

💾 Saving progress at sample 9520

 58%|█████▊    | 9520/16500 [03:07<04:28, 25.99it/s]

💾 Saving progress at sample 9530

 58%|█████▊    | 9530/16500 [03:07<04:25, 26.23it/s]

💾 Saving progress at sample 9540

 58%|█████▊    | 9540/16500 [03:07<04:22, 26.50it/s]

💾 Saving progress at sample 9550

 58%|█████▊    | 9550/16500 [03:08<04:21, 26.60it/s]

💾 Saving progress at sample 9560

 58%|█████▊    | 9560/16500 [03:08<04:22, 26.39it/s]

💾 Saving progress at sample 9570

 58%|█████▊    | 9570/16500 [03:08<04:27, 25.91it/s]

💾 Saving progress at sample 9580

 58%|█████▊    | 9580/16500 [03:09<04:25, 26.09it/s]

💾 Saving progress at sample 9590

 58%|█████▊    | 9590/16500 [03:09<04:28, 25.74it/s]

💾 Saving progress at sample 9600

 58%|█████▊    | 9600/16500 [03:10<04:24, 26.06it/s]

💾 Saving progress at sample 9610

 58%|█████▊    | 9610/16500 [03:10<04:23, 26.16it/s]

💾 Saving progress at sample 9620

 58%|█████▊    | 9620/16500 [03:10<04:26, 25.81it/s]

💾 Saving progress at sample 9630

 58%|█████▊    | 9630/16500 [03:11<04:24, 25.97it/s]

💾 Saving progress at sample 9640

 58%|█████▊    | 9640/16500 [03:11<04:33, 25.04it/s]

💾 Saving progress at sample 9650

 58%|█████▊    | 9650/16500 [03:12<04:29, 25.39it/s]

💾 Saving progress at sample 9660

 59%|█████▊    | 9660/16500 [03:12<04:26, 25.65it/s]

💾 Saving progress at sample 9670

 59%|█████▊    | 9670/16500 [03:12<04:26, 25.61it/s]

💾 Saving progress at sample 9680

 59%|█████▊    | 9680/16500 [03:13<04:24, 25.80it/s]

💾 Saving progress at sample 9690

 59%|█████▊    | 9690/16500 [03:13<04:23, 25.85it/s]

💾 Saving progress at sample 9700

 59%|█████▉    | 9700/16500 [03:13<04:22, 25.87it/s]

💾 Saving progress at sample 9710

 59%|█████▉    | 9710/16500 [03:14<04:24, 25.66it/s]

💾 Saving progress at sample 9720

 59%|█████▉    | 9720/16500 [03:14<04:20, 26.00it/s]

💾 Saving progress at sample 9730

 59%|█████▉    | 9730/16500 [03:15<04:17, 26.26it/s]

💾 Saving progress at sample 9740

 59%|█████▉    | 9740/16500 [03:15<04:18, 26.11it/s]

💾 Saving progress at sample 9750

 59%|█████▉    | 9750/16500 [03:15<04:21, 25.79it/s]

💾 Saving progress at sample 9760

 59%|█████▉    | 9760/16500 [03:16<04:20, 25.83it/s]

💾 Saving progress at sample 9770

 59%|█████▉    | 9770/16500 [03:16<04:20, 25.87it/s]

💾 Saving progress at sample 9780

 59%|█████▉    | 9780/16500 [03:17<04:23, 25.51it/s]

💾 Saving progress at sample 9790

 59%|█████▉    | 9790/16500 [03:17<04:23, 25.49it/s]

💾 Saving progress at sample 9800

 59%|█████▉    | 9800/16500 [03:17<04:22, 25.48it/s]

💾 Saving progress at sample 9810

 59%|█████▉    | 9810/16500 [03:18<04:22, 25.52it/s]

💾 Saving progress at sample 9820

 60%|█████▉    | 9820/16500 [03:18<04:22, 25.42it/s]

💾 Saving progress at sample 9830

 60%|█████▉    | 9830/16500 [03:19<04:23, 25.32it/s]

💾 Saving progress at sample 9840

 60%|█████▉    | 9840/16500 [03:19<04:22, 25.33it/s]

💾 Saving progress at sample 9850

 60%|█████▉    | 9850/16500 [03:19<04:21, 25.39it/s]

💾 Saving progress at sample 9860

 60%|█████▉    | 9860/16500 [03:20<04:20, 25.48it/s]

💾 Saving progress at sample 9870

 60%|█████▉    | 9870/16500 [03:20<04:24, 25.11it/s]

💾 Saving progress at sample 9880

 60%|█████▉    | 9880/16500 [03:21<04:21, 25.33it/s]

💾 Saving progress at sample 9890

 60%|█████▉    | 9890/16500 [03:21<04:18, 25.59it/s]

💾 Saving progress at sample 9900

 60%|██████    | 9900/16500 [03:21<04:22, 25.19it/s]

💾 Saving progress at sample 9910

 60%|██████    | 9910/16500 [03:22<04:19, 25.39it/s]

💾 Saving progress at sample 9920

 60%|██████    | 9920/16500 [03:22<04:23, 24.95it/s]

💾 Saving progress at sample 9930

 60%|██████    | 9930/16500 [03:23<04:24, 24.87it/s]

💾 Saving progress at sample 9940

 60%|██████    | 9940/16500 [03:23<04:21, 25.08it/s]

💾 Saving progress at sample 9950

 60%|██████    | 9950/16500 [03:23<04:16, 25.49it/s]

💾 Saving progress at sample 9960

 60%|██████    | 9960/16500 [03:24<04:16, 25.45it/s]

💾 Saving progress at sample 9970

 60%|██████    | 9970/16500 [03:24<04:14, 25.69it/s]

💾 Saving progress at sample 9980

 60%|██████    | 9980/16500 [03:24<04:13, 25.74it/s]

💾 Saving progress at sample 9990

 61%|██████    | 9990/16500 [03:25<04:11, 25.92it/s]

💾 Saving progress at sample 10000

 61%|██████    | 10000/16500 [03:25<04:11, 25.87it/s]

💾 Saving progress at sample 10010

 61%|██████    | 10010/16500 [03:26<04:15, 25.37it/s]

💾 Saving progress at sample 10020

 61%|██████    | 10020/16500 [03:26<04:18, 25.05it/s]

💾 Saving progress at sample 10030

 61%|██████    | 10030/16500 [03:26<04:20, 24.85it/s]

💾 Saving progress at sample 10040

 61%|██████    | 10040/16500 [03:27<04:21, 24.73it/s]

💾 Saving progress at sample 10050

 61%|██████    | 10050/16500 [03:27<04:22, 24.58it/s]

💾 Saving progress at sample 10060

 61%|██████    | 10060/16500 [03:28<04:18, 24.90it/s]

💾 Saving progress at sample 10070

 61%|██████    | 10070/16500 [03:28<04:21, 24.62it/s]

💾 Saving progress at sample 10080

 61%|██████    | 10080/16500 [03:28<04:16, 25.02it/s]

💾 Saving progress at sample 10090

 61%|██████    | 10090/16500 [03:29<04:16, 25.04it/s]

💾 Saving progress at sample 10100

 61%|██████    | 10100/16500 [03:29<04:15, 25.03it/s]

💾 Saving progress at sample 10110

 61%|██████▏   | 10110/16500 [03:30<04:14, 25.09it/s]

💾 Saving progress at sample 10120

 61%|██████▏   | 10120/16500 [03:30<04:11, 25.38it/s]

💾 Saving progress at sample 10130

 61%|██████▏   | 10130/16500 [03:30<04:13, 25.17it/s]

💾 Saving progress at sample 10140

 61%|██████▏   | 10140/16500 [03:31<04:13, 25.12it/s]

💾 Saving progress at sample 10150

 62%|██████▏   | 10150/16500 [03:31<04:11, 25.24it/s]

💾 Saving progress at sample 10160

 62%|██████▏   | 10160/16500 [03:32<04:11, 25.19it/s]

💾 Saving progress at sample 10170

 62%|██████▏   | 10170/16500 [03:32<04:14, 24.89it/s]

💾 Saving progress at sample 10180

 62%|██████▏   | 10180/16500 [03:32<04:15, 24.74it/s]

💾 Saving progress at sample 10190

 62%|██████▏   | 10190/16500 [03:33<04:18, 24.38it/s]

💾 Saving progress at sample 10200

 62%|██████▏   | 10200/16500 [03:33<04:13, 24.82it/s]

💾 Saving progress at sample 10210

 62%|██████▏   | 10210/16500 [03:34<04:22, 23.93it/s]

💾 Saving progress at sample 10220

 62%|██████▏   | 10220/16500 [03:34<04:18, 24.30it/s]

💾 Saving progress at sample 10230

 62%|██████▏   | 10230/16500 [03:35<04:14, 24.62it/s]

💾 Saving progress at sample 10240

 62%|██████▏   | 10240/16500 [03:35<04:13, 24.72it/s]

💾 Saving progress at sample 10250

 62%|██████▏   | 10250/16500 [03:35<04:10, 24.92it/s]

💾 Saving progress at sample 10260

 62%|██████▏   | 10260/16500 [03:36<04:11, 24.77it/s]

💾 Saving progress at sample 10270

 62%|██████▏   | 10270/16500 [03:36<04:13, 24.59it/s]

💾 Saving progress at sample 10280

 62%|██████▏   | 10289/16500 [04:26<4:16:44,  2.48s/it]

💾 Saving progress at sample 10290

 62%|██████▏   | 10299/16500 [05:21<9:01:11,  5.24s/it]

💾 Saving progress at sample 10300

 62%|██████▏   | 10309/16500 [06:17<9:29:35,  5.52s/it]

💾 Saving progress at sample 10310

 63%|██████▎   | 10319/16500 [07:12<9:14:45,  5.39s/it]

💾 Saving progress at sample 10320

 63%|██████▎   | 10329/16500 [09:45<34:11:55, 19.95s/it]

💾 Saving progress at sample 10330

 63%|██████▎   | 10339/16500 [10:39<10:03:21,  5.88s/it]

💾 Saving progress at sample 10340

 63%|██████▎   | 10349/16500 [11:34<9:24:21,  5.50s/it]

💾 Saving progress at sample 10350

 63%|██████▎   | 10359/16500 [12:29<9:16:21,  5.44s/it]

💾 Saving progress at sample 10360

 63%|██████▎   | 10369/16500 [13:25<9:31:23,  5.59s/it]

💾 Saving progress at sample 10370

 63%|██████▎   | 10379/16500 [14:19<9:03:02,  5.32s/it]

💾 Saving progress at sample 10380

 63%|██████▎   | 10389/16500 [15:13<9:00:27,  5.31s/it]

💾 Saving progress at sample 10390

 63%|██████▎   | 10399/16500 [16:08<9:07:00,  5.38s/it]

💾 Saving progress at sample 10400

 63%|██████▎   | 10409/16500 [17:03<9:18:52,  5.51s/it]

💾 Saving progress at sample 10410

 63%|██████▎   | 10419/16500 [17:58<9:16:05,  5.49s/it]

💾 Saving progress at sample 10420

 63%|██████▎   | 10429/16500 [18:54<9:26:48,  5.60s/it]

💾 Saving progress at sample 10430

 63%|██████▎   | 10439/16500 [19:48<9:10:01,  5.44s/it]

💾 Saving progress at sample 10440

 63%|██████▎   | 10449/16500 [20:42<8:52:35,  5.28s/it]

💾 Saving progress at sample 10450

 63%|██████▎   | 10459/16500 [21:37<9:17:03,  5.53s/it]

💾 Saving progress at sample 10460

 63%|██████▎   | 10469/16500 [22:33<9:16:41,  5.54s/it]

💾 Saving progress at sample 10470

 64%|██████▎   | 10479/16500 [23:28<9:22:15,  5.60s/it]

💾 Saving progress at sample 10480

 64%|██████▎   | 10489/16500 [24:22<9:08:19,  5.47s/it]

💾 Saving progress at sample 10490

 64%|██████▎   | 10499/16500 [25:17<8:58:49,  5.39s/it]

💾 Saving progress at sample 10500

 64%|██████▎   | 10509/16500 [26:11<8:52:05,  5.33s/it]

💾 Saving progress at sample 10510

 64%|██████▍   | 10519/16500 [27:05<8:56:34,  5.38s/it]

💾 Saving progress at sample 10520

 64%|██████▍   | 10529/16500 [28:02<9:21:46,  5.64s/it]

💾 Saving progress at sample 10530

 64%|██████▍   | 10539/16500 [28:57<9:13:42,  5.57s/it]

💾 Saving progress at sample 10540

 64%|██████▍   | 10549/16500 [29:53<9:01:08,  5.46s/it]

💾 Saving progress at sample 10550

 64%|██████▍   | 10559/16500 [30:49<9:06:58,  5.52s/it]

💾 Saving progress at sample 10560

 64%|██████▍   | 10569/16500 [31:44<8:58:55,  5.45s/it]

💾 Saving progress at sample 10570

 64%|██████▍   | 10579/16500 [32:40<9:10:29,  5.58s/it]

💾 Saving progress at sample 10580

 64%|██████▍   | 10589/16500 [33:35<9:03:45,  5.52s/it]

💾 Saving progress at sample 10590

 64%|██████▍   | 10599/16500 [34:29<8:35:28,  5.24s/it]

💾 Saving progress at sample 10600

 64%|██████▍   | 10609/16500 [35:24<8:53:56,  5.44s/it]

💾 Saving progress at sample 10610

 64%|██████▍   | 10619/16500 [36:18<8:50:02,  5.41s/it]

💾 Saving progress at sample 10620

 64%|██████▍   | 10629/16500 [37:12<8:48:33,  5.40s/it]

💾 Saving progress at sample 10630

 64%|██████▍   | 10639/16500 [38:08<8:59:09,  5.52s/it]

💾 Saving progress at sample 10640

 65%|██████▍   | 10649/16500 [39:03<8:45:29,  5.39s/it]

💾 Saving progress at sample 10650

 65%|██████▍   | 10659/16500 [39:59<8:50:29,  5.45s/it]

💾 Saving progress at sample 10660

 65%|██████▍   | 10669/16500 [40:55<8:52:34,  5.48s/it]

💾 Saving progress at sample 10670

 65%|██████▍   | 10679/16500 [41:49<8:38:08,  5.34s/it]

💾 Saving progress at sample 10680

 65%|██████▍   | 10689/16500 [42:43<8:52:19,  5.50s/it]

💾 Saving progress at sample 10690

 65%|██████▍   | 10699/16500 [43:38<8:57:14,  5.56s/it]

💾 Saving progress at sample 10700

 65%|██████▍   | 10709/16500 [44:32<8:44:46,  5.44s/it]

💾 Saving progress at sample 10710

 65%|██████▍   | 10719/16500 [45:26<8:41:54,  5.42s/it]

💾 Saving progress at sample 10720

 65%|██████▌   | 10729/16500 [46:21<8:40:37,  5.41s/it]

💾 Saving progress at sample 10730

 65%|██████▌   | 10739/16500 [47:17<8:55:42,  5.58s/it]

💾 Saving progress at sample 10740

 65%|██████▌   | 10749/16500 [48:11<8:42:48,  5.45s/it]

💾 Saving progress at sample 10750

 65%|██████▌   | 10759/16500 [49:07<9:00:55,  5.65s/it]

💾 Saving progress at sample 10760

 65%|██████▌   | 10769/16500 [50:01<8:43:45,  5.48s/it]

💾 Saving progress at sample 10770

 65%|██████▌   | 10779/16500 [50:57<8:47:44,  5.53s/it]

💾 Saving progress at sample 10780

 65%|██████▌   | 10789/16500 [51:52<8:43:26,  5.50s/it]

💾 Saving progress at sample 10790

 65%|██████▌   | 10799/16500 [52:46<8:21:44,  5.28s/it]

💾 Saving progress at sample 10800

 66%|██████▌   | 10809/16500 [53:41<8:33:10,  5.41s/it]

💾 Saving progress at sample 10810

 66%|██████▌   | 10819/16500 [54:35<8:32:53,  5.42s/it]

💾 Saving progress at sample 10820

 66%|██████▌   | 10829/16500 [55:30<8:24:38,  5.34s/it]

💾 Saving progress at sample 10830

 66%|██████▌   | 10839/16500 [56:24<8:25:32,  5.36s/it]

💾 Saving progress at sample 10840

 66%|██████▌   | 10849/16500 [57:18<8:41:40,  5.54s/it]

💾 Saving progress at sample 10850

 66%|██████▌   | 10859/16500 [58:14<8:47:38,  5.61s/it]

💾 Saving progress at sample 10860

 66%|██████▌   | 10869/16500 [59:10<8:45:30,  5.60s/it]

💾 Saving progress at sample 10870

 66%|██████▌   | 10879/16500 [1:00:05<8:26:39,  5.41s/it]

💾 Saving progress at sample 10880

 66%|██████▌   | 10889/16500 [1:00:59<8:31:05,  5.47s/it]

💾 Saving progress at sample 10890

 66%|██████▌   | 10899/16500 [1:01:52<8:08:49,  5.24s/it]

💾 Saving progress at sample 10900

 66%|██████▌   | 10909/16500 [1:02:47<8:22:20,  5.39s/it]

💾 Saving progress at sample 10910

 66%|██████▌   | 10919/16500 [1:03:41<8:23:39,  5.41s/it]

💾 Saving progress at sample 10920

 66%|██████▌   | 10929/16500 [1:04:36<8:29:48,  5.49s/it]

💾 Saving progress at sample 10930

 66%|██████▋   | 10939/16500 [1:05:32<8:42:33,  5.64s/it]

💾 Saving progress at sample 10940

 66%|██████▋   | 10949/16500 [1:06:26<8:29:38,  5.51s/it]

💾 Saving progress at sample 10950

 66%|██████▋   | 10959/16500 [1:07:21<8:26:25,  5.48s/it]

💾 Saving progress at sample 10960

 66%|██████▋   | 10969/16500 [1:08:17<8:34:07,  5.58s/it]

💾 Saving progress at sample 10970

 67%|██████▋   | 10979/16500 [1:09:13<8:25:15,  5.49s/it]

💾 Saving progress at sample 10980

 67%|██████▋   | 10989/16500 [1:10:06<8:15:43,  5.40s/it]

💾 Saving progress at sample 10990

 67%|██████▋   | 10999/16500 [1:11:02<8:38:01,  5.65s/it]

💾 Saving progress at sample 11000

 67%|██████▋   | 11009/16500 [1:11:56<8:11:19,  5.37s/it]

💾 Saving progress at sample 11010

 67%|██████▋   | 11019/16500 [1:12:53<8:19:29,  5.47s/it]

💾 Saving progress at sample 11020

 67%|██████▋   | 11029/16500 [1:13:48<8:25:21,  5.54s/it]

💾 Saving progress at sample 11030

 67%|██████▋   | 11039/16500 [1:14:42<8:13:24,  5.42s/it]

💾 Saving progress at sample 11040

 67%|██████▋   | 11049/16500 [1:15:37<8:27:27,  5.59s/it]

💾 Saving progress at sample 11050

 67%|██████▋   | 11059/16500 [1:16:32<8:10:38,  5.41s/it]

💾 Saving progress at sample 11060

 67%|██████▋   | 11069/16500 [1:17:27<8:17:05,  5.49s/it]

💾 Saving progress at sample 11070

 67%|██████▋   | 11079/16500 [1:18:23<8:11:38,  5.44s/it]

💾 Saving progress at sample 11080

 67%|██████▋   | 11089/16500 [1:19:18<8:08:57,  5.42s/it]

💾 Saving progress at sample 11090

 67%|██████▋   | 11099/16500 [1:20:13<8:13:32,  5.48s/it]

💾 Saving progress at sample 11100

 67%|██████▋   | 11109/16500 [1:21:08<7:57:16,  5.31s/it]

💾 Saving progress at sample 11110

 67%|██████▋   | 11119/16500 [1:22:03<8:13:53,  5.51s/it]

💾 Saving progress at sample 11120

 67%|██████▋   | 11129/16500 [1:22:57<8:08:58,  5.46s/it]

💾 Saving progress at sample 11130

 68%|██████▊   | 11139/16500 [1:23:53<8:26:21,  5.67s/it]

💾 Saving progress at sample 11140

 68%|██████▊   | 11149/16500 [1:24:48<7:54:24,  5.32s/it]WARNING:urllib3.connectionpool:Retrying (PostForcelistRetry(total=4, connect=3, read=None, redirect=None, status=None)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /runtime/backends/ibm_sherbrooke/configuration

💾 Saving progress at sample 11150

 68%|██████▊   | 11159/16500 [1:25:42<7:57:22,  5.36s/it]

💾 Saving progress at sample 11160

 68%|██████▊   | 11169/16500 [1:26:38<8:06:28,  5.48s/it]

💾 Saving progress at sample 11170

 68%|██████▊   | 11179/16500 [1:27:34<8:08:24,  5.51s/it]

💾 Saving progress at sample 11180

 68%|██████▊   | 11189/16500 [1:28:29<8:10:12,  5.54s/it]

💾 Saving progress at sample 11190

 68%|██████▊   | 11199/16500 [1:29:25<8:00:29,  5.44s/it]

💾 Saving progress at sample 11200

 68%|██████▊   | 11209/16500 [1:30:20<8:04:34,  5.50s/it]

💾 Saving progress at sample 11210

 68%|██████▊   | 11219/16500 [1:31:15<8:06:23,  5.53s/it]

💾 Saving progress at sample 11220

 68%|██████▊   | 11229/16500 [1:32:11<8:09:27,  5.57s/it]

💾 Saving progress at sample 11230

 68%|██████▊   | 11239/16500 [1:33:07<8:05:15,  5.53s/it]

💾 Saving progress at sample 11240

 68%|██████▊   | 11249/16500 [1:34:01<7:51:55,  5.39s/it]

💾 Saving progress at sample 11250

 68%|██████▊   | 11259/16500 [1:34:57<8:03:01,  5.53s/it]

💾 Saving progress at sample 11260

 68%|██████▊   | 11269/16500 [1:35:53<8:01:34,  5.52s/it]

💾 Saving progress at sample 11270

 68%|██████▊   | 11279/16500 [1:36:49<7:50:41,  5.41s/it]

💾 Saving progress at sample 11280

 68%|██████▊   | 11289/16500 [1:37:44<7:57:44,  5.50s/it]

💾 Saving progress at sample 11290

 68%|██████▊   | 11299/16500 [1:38:39<7:57:19,  5.51s/it]

💾 Saving progress at sample 11300

 69%|██████▊   | 11309/16500 [1:39:35<7:54:09,  5.48s/it]

💾 Saving progress at sample 11310

 69%|██████▊   | 11319/16500 [1:40:31<8:06:02,  5.63s/it]

💾 Saving progress at sample 11320

 69%|██████▊   | 11329/16500 [1:41:27<7:59:01,  5.56s/it]

💾 Saving progress at sample 11330

 69%|██████▊   | 11339/16500 [1:42:23<8:10:59,  5.71s/it]

💾 Saving progress at sample 11340

 69%|██████▉   | 11349/16500 [1:43:19<8:02:03,  5.62s/it]

💾 Saving progress at sample 11350

 69%|██████▉   | 11359/16500 [1:44:15<7:46:46,  5.45s/it]

💾 Saving progress at sample 11360

 69%|██████▉   | 11369/16500 [1:45:10<7:51:51,  5.52s/it]

💾 Saving progress at sample 11370

 69%|██████▉   | 11379/16500 [1:46:05<7:36:37,  5.35s/it]

💾 Saving progress at sample 11380

 69%|██████▉   | 11389/16500 [1:47:01<7:45:08,  5.46s/it]

💾 Saving progress at sample 11390

 69%|██████▉   | 11399/16500 [1:47:56<7:42:50,  5.44s/it]

💾 Saving progress at sample 11400

 69%|██████▉   | 11409/16500 [1:48:51<7:46:40,  5.50s/it]

💾 Saving progress at sample 11410

 69%|██████▉   | 11419/16500 [1:49:45<7:36:56,  5.40s/it]

💾 Saving progress at sample 11420

 69%|██████▉   | 11429/16500 [1:50:40<7:39:44,  5.44s/it]

💾 Saving progress at sample 11430

 69%|██████▉   | 11439/16500 [1:51:34<7:35:35,  5.40s/it]

💾 Saving progress at sample 11440

 69%|██████▉   | 11449/16500 [1:52:30<7:49:21,  5.58s/it]

💾 Saving progress at sample 11450

 69%|██████▉   | 11459/16500 [1:53:25<7:41:33,  5.49s/it]

💾 Saving progress at sample 11460

 70%|██████▉   | 11469/16500 [1:54:21<7:37:42,  5.46s/it]

💾 Saving progress at sample 11470

 70%|██████▉   | 11479/16500 [1:55:17<7:50:21,  5.62s/it]

💾 Saving progress at sample 11480

 70%|██████▉   | 11489/16500 [1:56:12<7:42:53,  5.54s/it]

💾 Saving progress at sample 11490

 70%|██████▉   | 11499/16500 [1:57:06<7:20:18,  5.28s/it]

💾 Saving progress at sample 11500

 70%|██████▉   | 11509/16500 [1:58:02<7:45:32,  5.60s/it]

💾 Saving progress at sample 11510

 70%|██████▉   | 11519/16500 [1:58:58<7:45:09,  5.60s/it]

💾 Saving progress at sample 11520

 70%|██████▉   | 11529/16500 [1:59:55<7:50:08,  5.67s/it]

💾 Saving progress at sample 11530

 70%|██████▉   | 11539/16500 [2:00:51<7:49:52,  5.68s/it]

💾 Saving progress at sample 11540

 70%|██████▉   | 11549/16500 [2:01:46<7:32:09,  5.48s/it]

💾 Saving progress at sample 11550

 70%|███████   | 11559/16500 [2:02:42<7:27:08,  5.43s/it]

💾 Saving progress at sample 11560

 70%|███████   | 11569/16500 [2:03:37<7:19:59,  5.35s/it]

💾 Saving progress at sample 11570

 70%|███████   | 11579/16500 [2:04:33<7:26:52,  5.45s/it]

💾 Saving progress at sample 11580

 70%|███████   | 11589/16500 [2:05:30<7:44:53,  5.68s/it]

💾 Saving progress at sample 11590

 70%|███████   | 11599/16500 [2:06:26<7:26:21,  5.46s/it]

💾 Saving progress at sample 11600

 70%|███████   | 11609/16500 [2:07:22<7:35:44,  5.59s/it]

💾 Saving progress at sample 11610

 70%|███████   | 11619/16500 [2:08:17<7:16:53,  5.37s/it]

💾 Saving progress at sample 11620

 70%|███████   | 11629/16500 [2:09:13<7:45:40,  5.74s/it]

💾 Saving progress at sample 11630

 71%|███████   | 11639/16500 [2:10:07<7:25:47,  5.50s/it]

💾 Saving progress at sample 11640

 71%|███████   | 11649/16500 [2:11:03<7:22:00,  5.47s/it]

💾 Saving progress at sample 11650

 71%|███████   | 11659/16500 [2:11:59<7:27:05,  5.54s/it]

💾 Saving progress at sample 11660

 71%|███████   | 11669/16500 [2:12:54<7:27:21,  5.56s/it]

💾 Saving progress at sample 11670

 71%|███████   | 11679/16500 [2:13:50<7:23:56,  5.53s/it]

💾 Saving progress at sample 11680

 71%|███████   | 11689/16500 [2:14:47<7:28:33,  5.59s/it]

💾 Saving progress at sample 11690

 71%|███████   | 11699/16500 [2:15:43<7:21:22,  5.52s/it]

💾 Saving progress at sample 11700

 71%|███████   | 11709/16500 [2:16:39<7:30:25,  5.64s/it]

💾 Saving progress at sample 11710

 71%|███████   | 11719/16500 [2:17:34<7:22:35,  5.55s/it]

💾 Saving progress at sample 11720

 71%|███████   | 11729/16500 [2:18:30<7:20:42,  5.54s/it]

💾 Saving progress at sample 11730

 71%|███████   | 11739/16500 [2:19:27<7:25:46,  5.62s/it]

💾 Saving progress at sample 11740

 71%|███████   | 11749/16500 [2:20:23<7:29:52,  5.68s/it]

💾 Saving progress at sample 11750

 71%|███████▏  | 11759/16500 [2:21:18<7:21:29,  5.59s/it]

💾 Saving progress at sample 11760

 71%|███████▏  | 11769/16500 [2:22:12<7:14:06,  5.51s/it]

💾 Saving progress at sample 11770

 71%|███████▏  | 11779/16500 [2:23:08<7:12:56,  5.50s/it]

💾 Saving progress at sample 11780

 71%|███████▏  | 11789/16500 [2:24:03<6:58:59,  5.34s/it]

💾 Saving progress at sample 11790

 72%|███████▏  | 11799/16500 [2:24:59<7:02:21,  5.39s/it]

💾 Saving progress at sample 11800

 72%|███████▏  | 11809/16500 [2:25:54<7:09:09,  5.49s/it]

💾 Saving progress at sample 11810

 72%|███████▏  | 11819/16500 [2:26:51<7:14:17,  5.57s/it]

💾 Saving progress at sample 11820

 72%|███████▏  | 11829/16500 [2:27:47<7:14:22,  5.58s/it]

💾 Saving progress at sample 11830

 72%|███████▏  | 11839/16500 [2:28:42<7:06:28,  5.49s/it]

💾 Saving progress at sample 11840

 72%|███████▏  | 11849/16500 [2:29:37<7:01:04,  5.43s/it]

💾 Saving progress at sample 11850

 72%|███████▏  | 11859/16500 [2:30:33<7:08:18,  5.54s/it]

💾 Saving progress at sample 11860

 72%|███████▏  | 11869/16500 [2:31:27<7:04:17,  5.50s/it]

💾 Saving progress at sample 11870

 72%|███████▏  | 11879/16500 [2:32:25<7:12:54,  5.62s/it]

💾 Saving progress at sample 11880

 72%|███████▏  | 11889/16500 [2:33:22<7:08:36,  5.58s/it]

💾 Saving progress at sample 11890

 72%|███████▏  | 11899/16500 [2:34:18<7:05:39,  5.55s/it]

💾 Saving progress at sample 11900

 72%|███████▏  | 11909/16500 [2:35:14<7:09:26,  5.61s/it]

💾 Saving progress at sample 11910

 72%|███████▏  | 11919/16500 [2:36:09<7:03:35,  5.55s/it]

💾 Saving progress at sample 11920

 72%|███████▏  | 11929/16500 [2:37:05<6:59:48,  5.51s/it]

💾 Saving progress at sample 11930

 72%|███████▏  | 11939/16500 [2:38:00<6:57:23,  5.49s/it]

💾 Saving progress at sample 11940

 72%|███████▏  | 11949/16500 [2:39:11<8:53:09,  7.03s/it]

💾 Saving progress at sample 11950

 72%|███████▏  | 11959/16500 [2:40:06<6:54:40,  5.48s/it]

💾 Saving progress at sample 11960

 73%|███████▎  | 11969/16500 [2:41:03<7:11:55,  5.72s/it]

💾 Saving progress at sample 11970

 73%|███████▎  | 11979/16500 [2:41:59<7:02:22,  5.61s/it]

💾 Saving progress at sample 11980

 73%|███████▎  | 11989/16500 [2:42:55<6:49:39,  5.45s/it]

💾 Saving progress at sample 11990

 73%|███████▎  | 11999/16500 [2:43:50<6:55:07,  5.53s/it]

💾 Saving progress at sample 12000

 73%|███████▎  | 12009/16500 [2:44:46<6:58:08,  5.59s/it]

💾 Saving progress at sample 12010

 73%|███████▎  | 12019/16500 [2:45:41<6:45:46,  5.43s/it]

💾 Saving progress at sample 12020

 73%|███████▎  | 12029/16500 [2:46:37<6:52:30,  5.54s/it]

💾 Saving progress at sample 12030

 73%|███████▎  | 12039/16500 [2:47:32<6:47:11,  5.48s/it]

💾 Saving progress at sample 12040

 73%|███████▎  | 12049/16500 [2:48:27<6:35:45,  5.33s/it]

💾 Saving progress at sample 12050

 73%|███████▎  | 12059/16500 [2:49:24<6:52:47,  5.58s/it]

💾 Saving progress at sample 12060

 73%|███████▎  | 12069/16500 [2:50:19<6:51:34,  5.57s/it]

💾 Saving progress at sample 12070

 73%|███████▎  | 12079/16500 [2:51:15<6:40:47,  5.44s/it]

💾 Saving progress at sample 12080

 73%|███████▎  | 12089/16500 [2:52:12<7:03:38,  5.76s/it]

💾 Saving progress at sample 12090

 73%|███████▎  | 12099/16500 [2:53:08<6:42:36,  5.49s/it]

💾 Saving progress at sample 12100

 73%|███████▎  | 12109/16500 [2:54:05<6:46:58,  5.56s/it]

💾 Saving progress at sample 12110

 73%|███████▎  | 12119/16500 [2:55:01<6:40:59,  5.49s/it]

💾 Saving progress at sample 12120

 74%|███████▎  | 12129/16500 [2:55:57<6:48:27,  5.61s/it]

💾 Saving progress at sample 12130

 74%|███████▎  | 12139/16500 [2:56:53<6:20:43,  5.24s/it]

💾 Saving progress at sample 12140

 74%|███████▎  | 12149/16500 [2:57:51<6:50:24,  5.66s/it]

💾 Saving progress at sample 12150

 74%|███████▎  | 12159/16500 [2:58:46<6:40:00,  5.53s/it]

💾 Saving progress at sample 12160

 74%|███████▍  | 12169/16500 [2:59:43<6:43:29,  5.59s/it]

💾 Saving progress at sample 12170

 74%|███████▍  | 12179/16500 [3:00:38<6:35:06,  5.49s/it]

💾 Saving progress at sample 12180

 74%|███████▍  | 12189/16500 [3:01:37<7:08:21,  5.96s/it]

💾 Saving progress at sample 12190

 74%|███████▍  | 12199/16500 [3:02:36<7:07:56,  5.97s/it]

💾 Saving progress at sample 12200

 74%|███████▍  | 12209/16500 [3:03:36<7:17:33,  6.12s/it]

💾 Saving progress at sample 12210

 74%|███████▍  | 12219/16500 [3:04:37<7:27:10,  6.27s/it]

💾 Saving progress at sample 12220

 74%|███████▍  | 12229/16500 [3:05:36<6:52:09,  5.79s/it]

💾 Saving progress at sample 12230

 74%|███████▍  | 12239/16500 [3:06:36<6:53:08,  5.82s/it]

💾 Saving progress at sample 12240

 74%|███████▍  | 12249/16500 [3:07:38<7:06:46,  6.02s/it]

💾 Saving progress at sample 12250

 74%|███████▍  | 12259/16500 [3:08:37<6:44:29,  5.72s/it]

💾 Saving progress at sample 12260

 74%|███████▍  | 12269/16500 [3:09:33<6:49:15,  5.80s/it]

💾 Saving progress at sample 12270

 74%|███████▍  | 12279/16500 [3:10:30<6:33:20,  5.59s/it]

💾 Saving progress at sample 12280

 74%|███████▍  | 12289/16500 [3:11:26<6:27:50,  5.53s/it]

💾 Saving progress at sample 12290

 75%|███████▍  | 12299/16500 [3:12:23<6:36:31,  5.66s/it]

💾 Saving progress at sample 12300

 75%|███████▍  | 12309/16500 [3:13:20<6:29:21,  5.57s/it]

💾 Saving progress at sample 12310

 75%|███████▍  | 12319/16500 [3:14:18<6:35:47,  5.68s/it]

💾 Saving progress at sample 12320

 75%|███████▍  | 12329/16500 [3:15:16<6:55:34,  5.98s/it]

💾 Saving progress at sample 12330

 75%|███████▍  | 12339/16500 [3:16:15<6:46:55,  5.87s/it]

💾 Saving progress at sample 12340

 75%|███████▍  | 12349/16500 [3:17:12<6:27:47,  5.61s/it]

💾 Saving progress at sample 12350

 75%|███████▍  | 12359/16500 [3:18:09<6:29:35,  5.64s/it]

💾 Saving progress at sample 12360

 75%|███████▍  | 12369/16500 [3:19:05<6:30:26,  5.67s/it]

💾 Saving progress at sample 12370

 75%|███████▌  | 12379/16500 [3:20:03<6:27:25,  5.64s/it]

💾 Saving progress at sample 12380

 75%|███████▌  | 12389/16500 [3:20:59<6:22:13,  5.58s/it]

💾 Saving progress at sample 12390

 75%|███████▌  | 12399/16500 [3:21:54<6:13:49,  5.47s/it]

💾 Saving progress at sample 12400

 75%|███████▌  | 12409/16500 [3:22:49<6:13:14,  5.47s/it]

💾 Saving progress at sample 12410

 75%|███████▌  | 12419/16500 [3:23:45<6:09:26,  5.43s/it]

💾 Saving progress at sample 12420

 75%|███████▌  | 12429/16500 [3:24:41<6:19:23,  5.59s/it]

💾 Saving progress at sample 12430

 75%|███████▌  | 12439/16500 [3:25:37<6:16:31,  5.56s/it]

💾 Saving progress at sample 12440

 75%|███████▌  | 12449/16500 [3:26:32<6:16:04,  5.57s/it]

💾 Saving progress at sample 12450

 76%|███████▌  | 12459/16500 [3:27:29<6:16:36,  5.59s/it]

💾 Saving progress at sample 12460

 76%|███████▌  | 12469/16500 [3:28:26<6:33:03,  5.85s/it]

💾 Saving progress at sample 12470

 76%|███████▌  | 12479/16500 [3:29:20<6:11:09,  5.54s/it]

💾 Saving progress at sample 12480

 76%|███████▌  | 12489/16500 [3:30:17<6:13:01,  5.58s/it]

💾 Saving progress at sample 12490

 76%|███████▌  | 12499/16500 [3:31:14<6:08:32,  5.53s/it]

💾 Saving progress at sample 12500

 76%|███████▌  | 12509/16500 [3:32:10<6:07:25,  5.52s/it]

💾 Saving progress at sample 12510

 76%|███████▌  | 12519/16500 [3:33:07<6:12:06,  5.61s/it]

💾 Saving progress at sample 12520

 76%|███████▌  | 12529/16500 [3:34:03<6:14:05,  5.65s/it]

💾 Saving progress at sample 12530

 76%|███████▌  | 12539/16500 [3:34:59<5:53:05,  5.35s/it]

💾 Saving progress at sample 12540

 76%|███████▌  | 12549/16500 [3:35:57<6:17:47,  5.74s/it]

💾 Saving progress at sample 12550

 76%|███████▌  | 12559/16500 [3:36:53<6:07:45,  5.60s/it]

💾 Saving progress at sample 12560

 76%|███████▌  | 12569/16500 [3:37:49<5:57:38,  5.46s/it]

💾 Saving progress at sample 12570

 76%|███████▌  | 12579/16500 [3:38:45<6:08:20,  5.64s/it]

💾 Saving progress at sample 12580

 76%|███████▋  | 12589/16500 [3:39:43<6:08:08,  5.65s/it]

💾 Saving progress at sample 12590

 76%|███████▋  | 12599/16500 [3:40:42<6:18:27,  5.82s/it]

💾 Saving progress at sample 12600

 76%|███████▋  | 12609/16500 [3:41:39<6:09:17,  5.69s/it]

💾 Saving progress at sample 12610

 76%|███████▋  | 12619/16500 [3:42:35<5:55:30,  5.50s/it]

💾 Saving progress at sample 12620

 77%|███████▋  | 12629/16500 [3:43:31<6:02:30,  5.62s/it]

💾 Saving progress at sample 12630

 77%|███████▋  | 12639/16500 [3:44:27<6:00:24,  5.60s/it]

💾 Saving progress at sample 12640

 77%|███████▋  | 12649/16500 [3:45:23<5:57:10,  5.56s/it]

💾 Saving progress at sample 12650

 77%|███████▋  | 12659/16500 [3:46:19<5:55:50,  5.56s/it]

💾 Saving progress at sample 12660

 77%|███████▋  | 12669/16500 [3:47:16<6:05:33,  5.73s/it]

💾 Saving progress at sample 12670

 77%|███████▋  | 12679/16500 [3:48:12<5:52:53,  5.54s/it]

💾 Saving progress at sample 12680

 77%|███████▋  | 12689/16500 [3:49:08<5:57:00,  5.62s/it]

💾 Saving progress at sample 12690

 77%|███████▋  | 12699/16500 [3:50:02<5:28:25,  5.18s/it]

💾 Saving progress at sample 12700

 77%|███████▋  | 12709/16500 [3:50:58<5:40:43,  5.39s/it]

💾 Saving progress at sample 12710

 77%|███████▋  | 12719/16500 [3:51:53<5:37:05,  5.35s/it]

💾 Saving progress at sample 12720

 77%|███████▋  | 12729/16500 [3:52:48<5:44:38,  5.48s/it]

💾 Saving progress at sample 12730

 77%|███████▋  | 12739/16500 [3:53:45<5:53:41,  5.64s/it]

💾 Saving progress at sample 12740

 77%|███████▋  | 12749/16500 [3:54:41<5:44:41,  5.51s/it]

💾 Saving progress at sample 12750

 77%|███████▋  | 12759/16500 [3:55:37<5:42:09,  5.49s/it]

💾 Saving progress at sample 12760

 77%|███████▋  | 12769/16500 [3:56:32<5:31:19,  5.33s/it]

💾 Saving progress at sample 12770

 77%|███████▋  | 12779/16500 [3:57:28<5:53:11,  5.70s/it]

💾 Saving progress at sample 12780

 78%|███████▊  | 12789/16500 [3:58:25<5:53:52,  5.72s/it]

💾 Saving progress at sample 12790

 78%|███████▊  | 12799/16500 [3:59:20<5:49:23,  5.66s/it]

💾 Saving progress at sample 12800

 78%|███████▊  | 12809/16500 [4:00:16<5:44:43,  5.60s/it]

💾 Saving progress at sample 12810

 78%|███████▊  | 12819/16500 [4:01:12<5:43:34,  5.60s/it]

💾 Saving progress at sample 12820

 78%|███████▊  | 12829/16500 [4:02:08<5:39:32,  5.55s/it]

💾 Saving progress at sample 12830

 78%|███████▊  | 12839/16500 [4:03:03<5:38:23,  5.55s/it]

💾 Saving progress at sample 12840

 78%|███████▊  | 12849/16500 [4:03:59<5:39:11,  5.57s/it]

💾 Saving progress at sample 12850

 78%|███████▊  | 12859/16500 [4:04:55<5:31:07,  5.46s/it]

💾 Saving progress at sample 12860

 78%|███████▊  | 12869/16500 [4:05:51<5:30:58,  5.47s/it]

💾 Saving progress at sample 12870

 78%|███████▊  | 12879/16500 [4:06:46<5:30:06,  5.47s/it]

💾 Saving progress at sample 12880

 78%|███████▊  | 12889/16500 [4:07:41<5:35:04,  5.57s/it]

💾 Saving progress at sample 12890

 78%|███████▊  | 12899/16500 [4:08:37<5:36:08,  5.60s/it]

💾 Saving progress at sample 12900

 78%|███████▊  | 12909/16500 [4:09:33<5:35:10,  5.60s/it]

💾 Saving progress at sample 12910

 78%|███████▊  | 12919/16500 [4:10:29<5:37:03,  5.65s/it]

💾 Saving progress at sample 12920

 78%|███████▊  | 12929/16500 [4:11:26<5:32:11,  5.58s/it]

💾 Saving progress at sample 12930

 78%|███████▊  | 12939/16500 [4:12:21<5:28:27,  5.53s/it]

💾 Saving progress at sample 12940

 78%|███████▊  | 12949/16500 [4:13:17<5:29:00,  5.56s/it]

💾 Saving progress at sample 12950

 79%|███████▊  | 12959/16500 [4:14:12<5:14:31,  5.33s/it]

💾 Saving progress at sample 12960

 79%|███████▊  | 12969/16500 [4:15:09<5:34:24,  5.68s/it]

💾 Saving progress at sample 12970

 79%|███████▊  | 12979/16500 [4:16:05<5:26:58,  5.57s/it]

💾 Saving progress at sample 12980

 79%|███████▊  | 12989/16500 [4:17:01<5:30:22,  5.65s/it]

💾 Saving progress at sample 12990

 79%|███████▉  | 12999/16500 [4:17:58<5:27:31,  5.61s/it]

💾 Saving progress at sample 13000

 79%|███████▉  | 13009/16500 [4:18:53<5:23:28,  5.56s/it]

💾 Saving progress at sample 13010

 79%|███████▉  | 13019/16500 [4:19:50<5:40:27,  5.87s/it]

💾 Saving progress at sample 13020

 79%|███████▉  | 13029/16500 [4:20:46<5:25:13,  5.62s/it]

💾 Saving progress at sample 13030

 79%|███████▉  | 13039/16500 [4:21:42<5:20:04,  5.55s/it]

💾 Saving progress at sample 13040

 79%|███████▉  | 13049/16500 [4:22:39<5:18:14,  5.53s/it]

💾 Saving progress at sample 13050

 79%|███████▉  | 13059/16500 [4:23:34<5:14:35,  5.49s/it]

💾 Saving progress at sample 13060

 79%|███████▉  | 13069/16500 [4:24:30<5:16:31,  5.54s/it]

💾 Saving progress at sample 13070

 79%|███████▉  | 13079/16500 [4:25:26<5:19:02,  5.60s/it]

💾 Saving progress at sample 13080

 79%|███████▉  | 13089/16500 [4:26:23<5:24:46,  5.71s/it]

💾 Saving progress at sample 13090

 79%|███████▉  | 13099/16500 [4:27:18<5:17:11,  5.60s/it]

💾 Saving progress at sample 13100

 79%|███████▉  | 13109/16500 [4:28:14<5:06:37,  5.43s/it]

💾 Saving progress at sample 13110

 80%|███████▉  | 13119/16500 [4:29:10<5:15:54,  5.61s/it]

💾 Saving progress at sample 13120

 80%|███████▉  | 13129/16500 [4:30:06<5:15:47,  5.62s/it]

💾 Saving progress at sample 13130

 80%|███████▉  | 13139/16500 [4:31:02<5:12:20,  5.58s/it]

💾 Saving progress at sample 13140

 80%|███████▉  | 13149/16500 [4:31:58<5:05:18,  5.47s/it]

💾 Saving progress at sample 13150

 80%|███████▉  | 13159/16500 [4:32:54<5:08:53,  5.55s/it]

💾 Saving progress at sample 13160

 80%|███████▉  | 13169/16500 [4:33:49<5:08:52,  5.56s/it]

💾 Saving progress at sample 13170

 80%|███████▉  | 13179/16500 [4:34:45<5:02:11,  5.46s/it]

💾 Saving progress at sample 13180

 80%|███████▉  | 13189/16500 [4:35:42<5:16:19,  5.73s/it]

💾 Saving progress at sample 13190

 80%|███████▉  | 13199/16500 [4:36:38<5:05:23,  5.55s/it]

💾 Saving progress at sample 13200

 80%|████████  | 13209/16500 [4:37:34<4:56:44,  5.41s/it]

💾 Saving progress at sample 13210

 80%|████████  | 13219/16500 [4:38:30<5:00:53,  5.50s/it]

💾 Saving progress at sample 13220

 80%|████████  | 13229/16500 [4:39:27<5:13:14,  5.75s/it]

💾 Saving progress at sample 13230

 80%|████████  | 13239/16500 [4:40:23<5:09:08,  5.69s/it]

💾 Saving progress at sample 13240

 80%|████████  | 13249/16500 [4:41:18<4:59:22,  5.53s/it]

💾 Saving progress at sample 13250

 80%|████████  | 13259/16500 [4:42:15<5:02:33,  5.60s/it]

💾 Saving progress at sample 13260

 80%|████████  | 13269/16500 [4:43:11<4:56:25,  5.50s/it]

💾 Saving progress at sample 13270

 80%|████████  | 13279/16500 [4:44:08<4:51:49,  5.44s/it]

💾 Saving progress at sample 13280

 81%|████████  | 13289/16500 [4:45:06<5:01:53,  5.64s/it]

💾 Saving progress at sample 13290

 81%|████████  | 13299/16500 [4:46:01<4:58:16,  5.59s/it]

💾 Saving progress at sample 13300

 81%|████████  | 13309/16500 [4:46:57<4:48:02,  5.42s/it]

💾 Saving progress at sample 13310

 81%|████████  | 13319/16500 [4:47:53<4:57:07,  5.60s/it]

💾 Saving progress at sample 13320

 81%|████████  | 13329/16500 [4:48:47<4:38:50,  5.28s/it]

💾 Saving progress at sample 13330

 81%|████████  | 13339/16500 [4:49:44<4:59:39,  5.69s/it]

💾 Saving progress at sample 13340

 81%|████████  | 13349/16500 [4:50:40<4:52:56,  5.58s/it]

💾 Saving progress at sample 13350

 81%|████████  | 13359/16500 [4:51:35<4:49:28,  5.53s/it]

💾 Saving progress at sample 13360

 81%|████████  | 13369/16500 [4:52:32<4:47:10,  5.50s/it]

💾 Saving progress at sample 13370

 81%|████████  | 13379/16500 [4:53:28<4:44:04,  5.46s/it]

💾 Saving progress at sample 13380

 81%|████████  | 13389/16500 [4:54:25<4:49:10,  5.58s/it]

💾 Saving progress at sample 13390

 81%|████████  | 13399/16500 [4:55:22<4:45:41,  5.53s/it]

💾 Saving progress at sample 13400

 81%|████████▏ | 13409/16500 [4:56:18<4:48:39,  5.60s/it]

💾 Saving progress at sample 13410

 81%|████████▏ | 13419/16500 [4:57:16<4:48:48,  5.62s/it]

💾 Saving progress at sample 13420

 81%|████████▏ | 13429/16500 [4:58:12<4:48:48,  5.64s/it]

💾 Saving progress at sample 13430

 81%|████████▏ | 13439/16500 [4:59:08<4:41:18,  5.51s/it]

💾 Saving progress at sample 13440

 82%|████████▏ | 13449/16500 [5:00:05<4:48:09,  5.67s/it]

💾 Saving progress at sample 13450

 82%|████████▏ | 13459/16500 [5:01:00<4:40:36,  5.54s/it]

💾 Saving progress at sample 13460

 82%|████████▏ | 13469/16500 [5:01:57<4:41:50,  5.58s/it]

💾 Saving progress at sample 13470

 82%|████████▏ | 13479/16500 [5:02:54<4:40:36,  5.57s/it]

💾 Saving progress at sample 13480

 82%|████████▏ | 13489/16500 [5:03:49<4:26:18,  5.31s/it]

💾 Saving progress at sample 13490

 82%|████████▏ | 13499/16500 [5:04:46<4:41:51,  5.64s/it]

💾 Saving progress at sample 13500

 82%|████████▏ | 13509/16500 [5:05:44<4:39:38,  5.61s/it]

💾 Saving progress at sample 13510

 82%|████████▏ | 13519/16500 [5:06:41<4:43:43,  5.71s/it]

💾 Saving progress at sample 13520

 82%|████████▏ | 13529/16500 [5:07:37<4:32:49,  5.51s/it]

💾 Saving progress at sample 13530

 82%|████████▏ | 13539/16500 [5:08:33<4:36:49,  5.61s/it]

💾 Saving progress at sample 13540

 82%|████████▏ | 13549/16500 [5:09:31<4:41:59,  5.73s/it]

💾 Saving progress at sample 13550

 82%|████████▏ | 13559/16500 [5:10:27<4:34:32,  5.60s/it]

💾 Saving progress at sample 13560

 82%|████████▏ | 13569/16500 [5:11:22<4:33:31,  5.60s/it]

💾 Saving progress at sample 13570

 82%|████████▏ | 13579/16500 [5:12:17<4:18:33,  5.31s/it]

💾 Saving progress at sample 13580

 82%|████████▏ | 13589/16500 [5:13:14<4:23:59,  5.44s/it]

💾 Saving progress at sample 13590

 82%|████████▏ | 13599/16500 [5:14:12<4:34:26,  5.68s/it]

💾 Saving progress at sample 13600

 82%|████████▏ | 13609/16500 [5:15:08<4:23:08,  5.46s/it]

💾 Saving progress at sample 13610

 83%|████████▎ | 13619/16500 [5:16:05<4:27:05,  5.56s/it]

💾 Saving progress at sample 13620

 83%|████████▎ | 13629/16500 [5:17:02<4:23:18,  5.50s/it]

💾 Saving progress at sample 13630

 83%|████████▎ | 13639/16500 [5:17:58<4:25:17,  5.56s/it]

💾 Saving progress at sample 13640

 83%|████████▎ | 13649/16500 [5:18:58<4:40:55,  5.91s/it]

💾 Saving progress at sample 13650

 83%|████████▎ | 13659/16500 [5:19:53<4:26:32,  5.63s/it]

💾 Saving progress at sample 13660

 83%|████████▎ | 13669/16500 [5:20:50<4:25:38,  5.63s/it]

💾 Saving progress at sample 13670

 83%|████████▎ | 13679/16500 [5:21:46<4:21:20,  5.56s/it]

💾 Saving progress at sample 13680

 83%|████████▎ | 13689/16500 [5:22:42<4:20:27,  5.56s/it]

💾 Saving progress at sample 13690

 83%|████████▎ | 13699/16500 [5:23:37<4:10:29,  5.37s/it]

💾 Saving progress at sample 13700

 83%|████████▎ | 13709/16500 [5:24:34<4:22:20,  5.64s/it]

💾 Saving progress at sample 13710

 83%|████████▎ | 13719/16500 [5:25:30<4:14:04,  5.48s/it]

💾 Saving progress at sample 13720

 83%|████████▎ | 13729/16500 [5:26:26<4:17:46,  5.58s/it]

💾 Saving progress at sample 13730

 83%|████████▎ | 13739/16500 [5:27:23<4:17:41,  5.60s/it]

💾 Saving progress at sample 13740

 83%|████████▎ | 13749/16500 [5:28:19<4:11:18,  5.48s/it]

💾 Saving progress at sample 13750

 83%|████████▎ | 13759/16500 [5:29:16<4:19:43,  5.69s/it]

💾 Saving progress at sample 13760

 83%|████████▎ | 13769/16500 [5:30:11<4:06:01,  5.41s/it]

💾 Saving progress at sample 13770

 84%|████████▎ | 13779/16500 [5:31:06<4:04:11,  5.38s/it]

💾 Saving progress at sample 13780

 84%|████████▎ | 13789/16500 [5:32:05<4:23:59,  5.84s/it]

💾 Saving progress at sample 13790

 84%|████████▎ | 13799/16500 [5:33:01<4:15:38,  5.68s/it]

💾 Saving progress at sample 13800

 84%|████████▎ | 13809/16500 [5:33:57<4:06:13,  5.49s/it]

💾 Saving progress at sample 13810

 84%|████████▍ | 13819/16500 [5:34:53<4:02:11,  5.42s/it]

💾 Saving progress at sample 13820

 84%|████████▍ | 13829/16500 [5:35:50<4:13:07,  5.69s/it]

💾 Saving progress at sample 13830

 84%|████████▍ | 13839/16500 [5:36:47<4:13:12,  5.71s/it]

💾 Saving progress at sample 13840

 84%|████████▍ | 13849/16500 [5:37:44<4:05:51,  5.56s/it]

💾 Saving progress at sample 13850

 84%|████████▍ | 13859/16500 [5:38:41<4:09:41,  5.67s/it]

💾 Saving progress at sample 13860

 84%|████████▍ | 13869/16500 [5:39:37<4:00:19,  5.48s/it]

💾 Saving progress at sample 13870

 84%|████████▍ | 13879/16500 [5:40:35<4:09:48,  5.72s/it]

💾 Saving progress at sample 13880

 84%|████████▍ | 13889/16500 [5:41:32<4:04:52,  5.63s/it]

💾 Saving progress at sample 13890

 84%|████████▍ | 13899/16500 [5:42:30<4:19:27,  5.99s/it]

💾 Saving progress at sample 13900

 84%|████████▍ | 13909/16500 [5:43:26<4:02:57,  5.63s/it]

💾 Saving progress at sample 13910

 84%|████████▍ | 13919/16500 [5:44:23<4:00:30,  5.59s/it]

💾 Saving progress at sample 13920

 84%|████████▍ | 13929/16500 [5:45:20<4:00:58,  5.62s/it]

💾 Saving progress at sample 13930

 84%|████████▍ | 13939/16500 [5:46:17<4:02:03,  5.67s/it]

💾 Saving progress at sample 13940

 85%|████████▍ | 13949/16500 [5:47:14<3:57:30,  5.59s/it]

💾 Saving progress at sample 13950

 85%|████████▍ | 13959/16500 [5:48:11<4:03:23,  5.75s/it]

💾 Saving progress at sample 13960

 85%|████████▍ | 13969/16500 [5:49:07<3:53:53,  5.54s/it]

💾 Saving progress at sample 13970

 85%|████████▍ | 13979/16500 [5:50:03<3:51:04,  5.50s/it]

💾 Saving progress at sample 13980

 85%|████████▍ | 13989/16500 [5:50:59<3:48:40,  5.46s/it]

💾 Saving progress at sample 13990

 85%|████████▍ | 13999/16500 [5:51:54<3:48:29,  5.48s/it]

💾 Saving progress at sample 14000

 85%|████████▍ | 14009/16500 [5:52:51<3:55:33,  5.67s/it]

💾 Saving progress at sample 14010

 85%|████████▍ | 14019/16500 [5:53:47<3:49:31,  5.55s/it]

💾 Saving progress at sample 14020

 85%|████████▌ | 14029/16500 [5:54:45<3:56:15,  5.74s/it]

💾 Saving progress at sample 14030

 85%|████████▌ | 14039/16500 [5:55:42<3:48:54,  5.58s/it]

💾 Saving progress at sample 14040

 85%|████████▌ | 14049/16500 [5:56:39<3:54:58,  5.75s/it]

💾 Saving progress at sample 14050

 85%|████████▌ | 14059/16500 [5:57:36<3:49:50,  5.65s/it]

💾 Saving progress at sample 14060

 85%|████████▌ | 14069/16500 [5:58:33<3:51:20,  5.71s/it]

💾 Saving progress at sample 14070

 85%|████████▌ | 14079/16500 [5:59:29<3:45:29,  5.59s/it]

💾 Saving progress at sample 14080

 85%|████████▌ | 14089/16500 [6:00:26<3:44:36,  5.59s/it]

💾 Saving progress at sample 14090

 85%|████████▌ | 14099/16500 [6:01:27<3:58:46,  5.97s/it]

💾 Saving progress at sample 14100

 86%|████████▌ | 14109/16500 [6:02:24<3:46:46,  5.69s/it]

💾 Saving progress at sample 14110

 86%|████████▌ | 14119/16500 [6:03:22<3:54:48,  5.92s/it]

💾 Saving progress at sample 14120

 86%|████████▌ | 14129/16500 [6:04:19<3:43:36,  5.66s/it]

💾 Saving progress at sample 14130

 86%|████████▌ | 14139/16500 [6:05:16<3:45:53,  5.74s/it]

💾 Saving progress at sample 14140

 86%|████████▌ | 14149/16500 [6:06:13<3:38:34,  5.58s/it]

💾 Saving progress at sample 14150

 86%|████████▌ | 14159/16500 [6:07:09<3:41:06,  5.67s/it]

💾 Saving progress at sample 14160

 86%|████████▌ | 14169/16500 [6:08:06<3:43:23,  5.75s/it]

💾 Saving progress at sample 14170

 86%|████████▌ | 14179/16500 [6:09:01<3:30:24,  5.44s/it]

💾 Saving progress at sample 14180

 86%|████████▌ | 14189/16500 [6:09:58<3:38:52,  5.68s/it]

💾 Saving progress at sample 14190

 86%|████████▌ | 14199/16500 [6:10:55<3:32:06,  5.53s/it]

💾 Saving progress at sample 14200

 86%|████████▌ | 14209/16500 [6:11:52<3:35:37,  5.65s/it]

💾 Saving progress at sample 14210

 86%|████████▌ | 14219/16500 [6:12:48<3:30:16,  5.53s/it]

💾 Saving progress at sample 14220

 86%|████████▌ | 14229/16500 [6:13:43<3:25:14,  5.42s/it]

💾 Saving progress at sample 14230

 86%|████████▋ | 14239/16500 [6:14:40<3:33:09,  5.66s/it]

💾 Saving progress at sample 14240

 86%|████████▋ | 14249/16500 [6:15:38<3:32:22,  5.66s/it]

💾 Saving progress at sample 14250

 86%|████████▋ | 14259/16500 [6:16:35<3:30:10,  5.63s/it]

💾 Saving progress at sample 14260

 86%|████████▋ | 14269/16500 [6:17:31<3:34:10,  5.76s/it]

💾 Saving progress at sample 14270

 87%|████████▋ | 14279/16500 [6:18:29<3:27:12,  5.60s/it]

💾 Saving progress at sample 14280

 87%|████████▋ | 14289/16500 [6:19:24<3:22:32,  5.50s/it]

💾 Saving progress at sample 14290

 87%|████████▋ | 14299/16500 [6:20:22<3:28:26,  5.68s/it]

💾 Saving progress at sample 14300

 87%|████████▋ | 14309/16500 [6:21:19<3:29:35,  5.74s/it]

💾 Saving progress at sample 14310

 87%|████████▋ | 14319/16500 [6:22:14<3:19:36,  5.49s/it]

💾 Saving progress at sample 14320

 87%|████████▋ | 14329/16500 [6:23:11<3:19:52,  5.52s/it]

💾 Saving progress at sample 14330

 87%|████████▋ | 14339/16500 [6:24:08<3:24:08,  5.67s/it]

💾 Saving progress at sample 14340

 87%|████████▋ | 14349/16500 [6:25:06<3:26:58,  5.77s/it]

💾 Saving progress at sample 14350

 87%|████████▋ | 14359/16500 [6:26:03<3:24:05,  5.72s/it]

💾 Saving progress at sample 14360

 87%|████████▋ | 14369/16500 [6:27:00<3:21:44,  5.68s/it]

💾 Saving progress at sample 14370

 87%|████████▋ | 14379/16500 [6:27:57<3:18:09,  5.61s/it]

💾 Saving progress at sample 14380

 87%|████████▋ | 14389/16500 [6:28:54<3:17:06,  5.60s/it]

💾 Saving progress at sample 14390

 87%|████████▋ | 14399/16500 [6:29:51<3:20:14,  5.72s/it]

💾 Saving progress at sample 14400

 87%|████████▋ | 14409/16500 [6:30:48<3:16:44,  5.65s/it]

💾 Saving progress at sample 14410

 87%|████████▋ | 14419/16500 [6:31:45<3:17:31,  5.69s/it]

💾 Saving progress at sample 14420

 87%|████████▋ | 14429/16500 [6:32:40<3:08:59,  5.48s/it]

💾 Saving progress at sample 14430

 88%|████████▊ | 14439/16500 [6:33:36<3:06:42,  5.44s/it]

💾 Saving progress at sample 14440

 88%|████████▊ | 14449/16500 [6:34:35<3:16:38,  5.75s/it]

💾 Saving progress at sample 14450

 88%|████████▊ | 14459/16500 [6:35:31<3:14:04,  5.71s/it]

💾 Saving progress at sample 14460

 88%|████████▊ | 14469/16500 [6:36:28<3:10:43,  5.63s/it]

💾 Saving progress at sample 14470

 88%|████████▊ | 14479/16500 [6:37:25<3:08:59,  5.61s/it]

💾 Saving progress at sample 14480

 88%|████████▊ | 14489/16500 [6:38:22<3:09:06,  5.64s/it]

💾 Saving progress at sample 14490

 88%|████████▊ | 14499/16500 [6:39:18<3:04:01,  5.52s/it]

💾 Saving progress at sample 14500

 88%|████████▊ | 14509/16500 [6:40:16<3:12:43,  5.81s/it]

💾 Saving progress at sample 14510

 88%|████████▊ | 14519/16500 [6:41:12<3:05:57,  5.63s/it]

💾 Saving progress at sample 14520

 88%|████████▊ | 14529/16500 [6:42:08<3:03:16,  5.58s/it]

💾 Saving progress at sample 14530

 88%|████████▊ | 14539/16500 [6:43:06<3:07:07,  5.73s/it]

💾 Saving progress at sample 14540

 88%|████████▊ | 14549/16500 [6:44:02<3:01:04,  5.57s/it]

💾 Saving progress at sample 14550

 88%|████████▊ | 14559/16500 [6:44:59<3:03:17,  5.67s/it]

💾 Saving progress at sample 14560

 88%|████████▊ | 14569/16500 [6:45:54<3:01:59,  5.65s/it]

💾 Saving progress at sample 14570

 88%|████████▊ | 14579/16500 [6:46:51<3:04:04,  5.75s/it]

💾 Saving progress at sample 14580

 88%|████████▊ | 14589/16500 [6:47:49<3:00:59,  5.68s/it]

💾 Saving progress at sample 14590

 88%|████████▊ | 14599/16500 [6:48:45<2:54:37,  5.51s/it]

💾 Saving progress at sample 14600

 89%|████████▊ | 14609/16500 [6:49:41<2:56:41,  5.61s/it]

💾 Saving progress at sample 14610

 89%|████████▊ | 14619/16500 [6:50:39<2:54:40,  5.57s/it]

💾 Saving progress at sample 14620

 89%|████████▊ | 14629/16500 [6:51:35<2:54:50,  5.61s/it]

💾 Saving progress at sample 14630

 89%|████████▊ | 14639/16500 [6:52:32<2:52:52,  5.57s/it]

💾 Saving progress at sample 14640

 89%|████████▉ | 14649/16500 [6:53:29<2:57:35,  5.76s/it]

💾 Saving progress at sample 14650

 89%|████████▉ | 14659/16500 [6:54:27<2:52:09,  5.61s/it]

💾 Saving progress at sample 14660

 89%|████████▉ | 14669/16500 [6:55:24<2:54:18,  5.71s/it]

💾 Saving progress at sample 14670

 89%|████████▉ | 14679/16500 [6:56:21<2:56:16,  5.81s/it]

💾 Saving progress at sample 14680

 89%|████████▉ | 14689/16500 [6:57:18<2:46:00,  5.50s/it]

💾 Saving progress at sample 14690

 89%|████████▉ | 14699/16500 [6:58:15<2:47:40,  5.59s/it]

💾 Saving progress at sample 14700

 89%|████████▉ | 14709/16500 [6:59:12<2:49:21,  5.67s/it]

💾 Saving progress at sample 14710

 89%|████████▉ | 14719/16500 [7:00:10<2:50:15,  5.74s/it]

💾 Saving progress at sample 14720

 89%|████████▉ | 14729/16500 [7:01:08<2:45:50,  5.62s/it]

💾 Saving progress at sample 14730

 89%|████████▉ | 14739/16500 [7:02:04<2:46:24,  5.67s/it]

💾 Saving progress at sample 14740

 89%|████████▉ | 14749/16500 [7:03:02<2:43:00,  5.59s/it]

💾 Saving progress at sample 14750

 89%|████████▉ | 14759/16500 [7:04:00<2:46:55,  5.75s/it]

💾 Saving progress at sample 14760

 90%|████████▉ | 14769/16500 [7:04:58<2:48:46,  5.85s/it]

💾 Saving progress at sample 14770

 90%|████████▉ | 14779/16500 [7:05:55<2:43:22,  5.70s/it]

💾 Saving progress at sample 14780

 90%|████████▉ | 14789/16500 [7:06:53<2:43:05,  5.72s/it]

💾 Saving progress at sample 14790

 90%|████████▉ | 14799/16500 [7:07:51<2:40:38,  5.67s/it]

💾 Saving progress at sample 14800

 90%|████████▉ | 14809/16500 [7:08:47<2:36:39,  5.56s/it]

💾 Saving progress at sample 14810

 90%|████████▉ | 14819/16500 [7:09:45<2:40:09,  5.72s/it]

💾 Saving progress at sample 14820

 90%|████████▉ | 14829/16500 [7:10:42<2:34:47,  5.56s/it]

💾 Saving progress at sample 14830

 90%|████████▉ | 14839/16500 [7:11:39<2:36:29,  5.65s/it]

💾 Saving progress at sample 14840

 90%|████████▉ | 14849/16500 [7:12:36<2:32:28,  5.54s/it]

💾 Saving progress at sample 14850

 90%|█████████ | 14859/16500 [7:13:33<2:33:00,  5.59s/it]

💾 Saving progress at sample 14860

 90%|█████████ | 14869/16500 [7:14:31<2:33:33,  5.65s/it]

💾 Saving progress at sample 14870

 90%|█████████ | 14879/16500 [7:15:28<2:37:24,  5.83s/it]

💾 Saving progress at sample 14880

 90%|█████████ | 14889/16500 [7:16:26<2:34:19,  5.75s/it]

💾 Saving progress at sample 14890

 90%|█████████ | 14899/16500 [7:17:24<2:35:39,  5.83s/it]

💾 Saving progress at sample 14900

 90%|█████████ | 14909/16500 [7:18:21<2:27:56,  5.58s/it]

💾 Saving progress at sample 14910

 90%|█████████ | 14919/16500 [7:19:17<2:24:59,  5.50s/it]

💾 Saving progress at sample 14920

 90%|█████████ | 14929/16500 [7:20:13<2:23:49,  5.49s/it]

💾 Saving progress at sample 14930

 91%|█████████ | 14939/16500 [7:21:10<2:25:36,  5.60s/it]

💾 Saving progress at sample 14940

 91%|█████████ | 14949/16500 [7:22:07<2:22:16,  5.50s/it]

💾 Saving progress at sample 14950

 91%|█████████ | 14959/16500 [7:23:03<2:23:42,  5.60s/it]

💾 Saving progress at sample 14960

 91%|█████████ | 14969/16500 [7:24:00<2:18:02,  5.41s/it]

💾 Saving progress at sample 14970

 91%|█████████ | 14979/16500 [7:24:57<2:23:11,  5.65s/it]

💾 Saving progress at sample 14980

 91%|█████████ | 14989/16500 [7:25:54<2:25:47,  5.79s/it]

💾 Saving progress at sample 14990

 91%|█████████ | 14999/16500 [7:26:52<2:22:03,  5.68s/it]

💾 Saving progress at sample 15000

 91%|█████████ | 15009/16500 [7:27:49<2:23:05,  5.76s/it]

💾 Saving progress at sample 15010

 91%|█████████ | 15019/16500 [7:28:46<2:15:53,  5.51s/it]

💾 Saving progress at sample 15020

 91%|█████████ | 15029/16500 [7:29:43<2:18:16,  5.64s/it]

💾 Saving progress at sample 15030

 91%|█████████ | 15039/16500 [7:30:41<2:21:05,  5.79s/it]

💾 Saving progress at sample 15040

 91%|█████████ | 15049/16500 [7:31:39<2:18:19,  5.72s/it]

💾 Saving progress at sample 15050

 91%|█████████▏| 15059/16500 [7:32:36<2:14:43,  5.61s/it]

💾 Saving progress at sample 15060

 91%|█████████▏| 15069/16500 [7:33:33<2:14:45,  5.65s/it]

💾 Saving progress at sample 15070

 91%|█████████▏| 15079/16500 [7:34:31<2:18:00,  5.83s/it]

💾 Saving progress at sample 15080

 91%|█████████▏| 15089/16500 [7:35:28<2:13:35,  5.68s/it]

💾 Saving progress at sample 15090

 92%|█████████▏| 15099/16500 [7:36:25<2:13:55,  5.74s/it]

💾 Saving progress at sample 15100

 92%|█████████▏| 15109/16500 [7:37:22<2:13:33,  5.76s/it]

💾 Saving progress at sample 15110

 92%|█████████▏| 15119/16500 [7:38:21<2:17:03,  5.95s/it]

💾 Saving progress at sample 15120

 92%|█████████▏| 15129/16500 [7:39:19<2:11:26,  5.75s/it]

💾 Saving progress at sample 15130

 92%|█████████▏| 15139/16500 [7:40:16<2:07:42,  5.63s/it]

💾 Saving progress at sample 15140

 92%|█████████▏| 15149/16500 [7:41:12<2:05:19,  5.57s/it]

💾 Saving progress at sample 15150

 92%|█████████▏| 15159/16500 [7:42:10<2:03:46,  5.54s/it]

💾 Saving progress at sample 15160

 92%|█████████▏| 15169/16500 [7:43:07<2:05:52,  5.67s/it]

💾 Saving progress at sample 15170

 92%|█████████▏| 15179/16500 [7:44:05<2:05:35,  5.70s/it]

💾 Saving progress at sample 15180

 92%|█████████▏| 15189/16500 [7:45:02<2:03:51,  5.67s/it]

💾 Saving progress at sample 15190

 92%|█████████▏| 15199/16500 [7:46:00<2:02:48,  5.66s/it]

💾 Saving progress at sample 15200

 92%|█████████▏| 15209/16500 [7:46:57<2:03:00,  5.72s/it]

💾 Saving progress at sample 15210

 92%|█████████▏| 15219/16500 [7:47:55<2:02:59,  5.76s/it]

💾 Saving progress at sample 15220

 92%|█████████▏| 15229/16500 [7:48:50<1:58:53,  5.61s/it]

💾 Saving progress at sample 15230

 92%|█████████▏| 15239/16500 [7:49:46<1:58:38,  5.65s/it]

💾 Saving progress at sample 15240

 92%|█████████▏| 15249/16500 [7:50:45<1:57:42,  5.65s/it]

💾 Saving progress at sample 15250

 92%|█████████▏| 15259/16500 [7:51:41<1:53:57,  5.51s/it]

💾 Saving progress at sample 15260

 93%|█████████▎| 15269/16500 [7:52:38<1:55:46,  5.64s/it]

💾 Saving progress at sample 15270

 93%|█████████▎| 15279/16500 [7:53:35<1:55:14,  5.66s/it]

💾 Saving progress at sample 15280

 93%|█████████▎| 15289/16500 [7:54:32<1:56:41,  5.78s/it]

💾 Saving progress at sample 15290

 93%|█████████▎| 15299/16500 [7:55:30<1:51:31,  5.57s/it]

💾 Saving progress at sample 15300

 93%|█████████▎| 15309/16500 [7:56:26<1:52:36,  5.67s/it]

💾 Saving progress at sample 15310

 93%|█████████▎| 15319/16500 [7:57:25<1:52:57,  5.74s/it]

💾 Saving progress at sample 15320

 93%|█████████▎| 15329/16500 [7:58:21<1:50:02,  5.64s/it]

💾 Saving progress at sample 15330

 93%|█████████▎| 15339/16500 [7:59:18<1:54:50,  5.93s/it]

💾 Saving progress at sample 15340

 93%|█████████▎| 15349/16500 [8:00:16<1:49:28,  5.71s/it]

💾 Saving progress at sample 15350

 93%|█████████▎| 15359/16500 [8:01:13<1:47:02,  5.63s/it]

💾 Saving progress at sample 15360

 93%|█████████▎| 15369/16500 [8:02:10<1:44:30,  5.54s/it]

💾 Saving progress at sample 15370

 93%|█████████▎| 15379/16500 [8:03:07<1:43:15,  5.53s/it]

💾 Saving progress at sample 15380

 93%|█████████▎| 15389/16500 [8:04:04<1:44:07,  5.62s/it]

💾 Saving progress at sample 15390

 93%|█████████▎| 15399/16500 [8:05:02<1:44:36,  5.70s/it]

💾 Saving progress at sample 15400

 93%|█████████▎| 15409/16500 [8:05:59<1:42:59,  5.66s/it]

💾 Saving progress at sample 15410

 93%|█████████▎| 15419/16500 [8:06:59<1:45:51,  5.88s/it]

💾 Saving progress at sample 15420

 94%|█████████▎| 15429/16500 [8:07:56<1:42:53,  5.76s/it]

💾 Saving progress at sample 15430

 94%|█████████▎| 15439/16500 [8:08:53<1:40:31,  5.69s/it]

💾 Saving progress at sample 15440

 94%|█████████▎| 15449/16500 [8:09:50<1:42:12,  5.83s/it]

💾 Saving progress at sample 15450

 94%|█████████▎| 15459/16500 [8:10:47<1:34:44,  5.46s/it]

💾 Saving progress at sample 15460

 94%|█████████▍| 15469/16500 [8:11:44<1:37:17,  5.66s/it]

💾 Saving progress at sample 15470

 94%|█████████▍| 15479/16500 [8:12:41<1:36:15,  5.66s/it]

💾 Saving progress at sample 15480

 94%|█████████▍| 15489/16500 [8:13:38<1:32:20,  5.48s/it]

💾 Saving progress at sample 15490

 94%|█████████▍| 15499/16500 [8:14:35<1:36:02,  5.76s/it]

💾 Saving progress at sample 15500

 94%|█████████▍| 15509/16500 [8:15:32<1:33:31,  5.66s/it]

💾 Saving progress at sample 15510

 94%|█████████▍| 15519/16500 [8:16:29<1:32:49,  5.68s/it]

💾 Saving progress at sample 15520

 94%|█████████▍| 15529/16500 [8:17:26<1:30:06,  5.57s/it]

💾 Saving progress at sample 15530

 94%|█████████▍| 15539/16500 [8:18:24<1:34:20,  5.89s/it]

💾 Saving progress at sample 15540

 94%|█████████▍| 15549/16500 [8:19:22<1:31:08,  5.75s/it]

💾 Saving progress at sample 15550

 94%|█████████▍| 15559/16500 [8:20:20<1:32:06,  5.87s/it]

💾 Saving progress at sample 15560

 94%|█████████▍| 15569/16500 [8:21:17<1:25:11,  5.49s/it]

💾 Saving progress at sample 15570

 94%|█████████▍| 15579/16500 [8:22:14<1:26:47,  5.65s/it]

💾 Saving progress at sample 15580

 94%|█████████▍| 15589/16500 [8:23:13<1:27:31,  5.76s/it]

💾 Saving progress at sample 15590

 95%|█████████▍| 15599/16500 [8:24:09<1:24:28,  5.63s/it]

💾 Saving progress at sample 15600

 95%|█████████▍| 15609/16500 [8:25:06<1:21:29,  5.49s/it]

💾 Saving progress at sample 15610

 95%|█████████▍| 15619/16500 [8:26:04<1:23:08,  5.66s/it]

💾 Saving progress at sample 15620

 95%|█████████▍| 15629/16500 [8:27:01<1:22:36,  5.69s/it]

💾 Saving progress at sample 15630

 95%|█████████▍| 15639/16500 [8:27:57<1:21:03,  5.65s/it]

💾 Saving progress at sample 15640

 95%|█████████▍| 15649/16500 [8:28:56<1:22:19,  5.80s/it]

💾 Saving progress at sample 15650

 95%|█████████▍| 15659/16500 [8:29:51<1:18:40,  5.61s/it]

💾 Saving progress at sample 15660

 95%|█████████▍| 15669/16500 [8:30:49<1:21:43,  5.90s/it]

💾 Saving progress at sample 15670

 95%|█████████▌| 15679/16500 [8:31:46<1:18:30,  5.74s/it]

💾 Saving progress at sample 15680

 95%|█████████▌| 15689/16500 [8:32:43<1:14:38,  5.52s/it]

💾 Saving progress at sample 15690

 95%|█████████▌| 15699/16500 [8:33:41<1:16:30,  5.73s/it]

💾 Saving progress at sample 15700

 95%|█████████▌| 15709/16500 [8:34:38<1:13:01,  5.54s/it]

💾 Saving progress at sample 15710

 95%|█████████▌| 15719/16500 [8:35:35<1:12:26,  5.56s/it]

💾 Saving progress at sample 15720

 95%|█████████▌| 15729/16500 [8:36:33<1:11:57,  5.60s/it]

💾 Saving progress at sample 15730

 95%|█████████▌| 15739/16500 [8:37:29<1:10:22,  5.55s/it]

💾 Saving progress at sample 15740

 95%|█████████▌| 15749/16500 [8:38:28<1:13:00,  5.83s/it]

💾 Saving progress at sample 15750

 96%|█████████▌| 15759/16500 [8:39:25<1:09:55,  5.66s/it]

💾 Saving progress at sample 15760

 96%|█████████▌| 15769/16500 [8:40:24<1:11:27,  5.87s/it]

💾 Saving progress at sample 15770

 96%|█████████▌| 15779/16500 [8:41:23<1:14:07,  6.17s/it]

💾 Saving progress at sample 15780

 96%|█████████▌| 15789/16500 [8:42:20<1:05:57,  5.57s/it]

💾 Saving progress at sample 15790

 96%|█████████▌| 15799/16500 [8:43:18<1:07:40,  5.79s/it]

💾 Saving progress at sample 15800

 96%|█████████▌| 15809/16500 [8:44:15<1:05:20,  5.67s/it]

💾 Saving progress at sample 15810

 96%|█████████▌| 15819/16500 [8:45:12<1:03:12,  5.57s/it]

💾 Saving progress at sample 15820

 96%|█████████▌| 15829/16500 [8:46:11<1:02:41,  5.61s/it]

💾 Saving progress at sample 15830

 96%|█████████▌| 15839/16500 [8:47:09<1:02:09,  5.64s/it]

💾 Saving progress at sample 15840

 96%|█████████▌| 15849/16500 [8:48:06<1:02:05,  5.72s/it]

💾 Saving progress at sample 15850

 96%|█████████▌| 15859/16500 [8:49:04<1:01:46,  5.78s/it]

💾 Saving progress at sample 15860

 96%|█████████▌| 15869/16500 [8:51:40<1:11:51,  6.83s/it]

💾 Saving progress at sample 15870

 96%|█████████▌| 15879/16500 [8:52:38<1:00:02,  5.80s/it]

💾 Saving progress at sample 15880

 96%|█████████▋| 15889/16500 [8:53:36<59:55,  5.88s/it]

💾 Saving progress at sample 15890

 96%|█████████▋| 15899/16500 [8:54:33<55:58,  5.59s/it]

💾 Saving progress at sample 15900

 96%|█████████▋| 15909/16500 [8:55:30<55:18,  5.61s/it]

💾 Saving progress at sample 15910

 96%|█████████▋| 15919/16500 [8:56:27<54:29,  5.63s/it]

💾 Saving progress at sample 15920

 97%|█████████▋| 15929/16500 [8:57:24<53:36,  5.63s/it]

💾 Saving progress at sample 15930

 97%|█████████▋| 15939/16500 [8:58:21<54:00,  5.78s/it]

💾 Saving progress at sample 15940

 97%|█████████▋| 15949/16500 [8:59:18<52:17,  5.69s/it]

💾 Saving progress at sample 15950

 97%|█████████▋| 15959/16500 [9:00:15<51:22,  5.70s/it]

💾 Saving progress at sample 15960

 97%|█████████▋| 15969/16500 [9:01:12<50:30,  5.71s/it]

💾 Saving progress at sample 15970

 97%|█████████▋| 15979/16500 [9:02:10<49:16,  5.68s/it]

💾 Saving progress at sample 15980

 97%|█████████▋| 15989/16500 [9:03:09<49:25,  5.80s/it]

💾 Saving progress at sample 15990

 97%|█████████▋| 15999/16500 [9:04:07<46:47,  5.60s/it]

💾 Saving progress at sample 16000

 97%|█████████▋| 16009/16500 [9:05:06<48:10,  5.89s/it]

💾 Saving progress at sample 16010

 97%|█████████▋| 16019/16500 [9:06:03<44:16,  5.52s/it]

💾 Saving progress at sample 16020

 97%|█████████▋| 16029/16500 [9:07:00<43:55,  5.59s/it]

💾 Saving progress at sample 16030

 97%|█████████▋| 16039/16500 [9:07:58<44:05,  5.74s/it]

💾 Saving progress at sample 16040

 97%|█████████▋| 16049/16500 [9:08:56<43:00,  5.72s/it]

💾 Saving progress at sample 16050

 97%|█████████▋| 16059/16500 [9:09:53<42:17,  5.75s/it]

💾 Saving progress at sample 16060

 97%|█████████▋| 16069/16500 [9:10:51<40:31,  5.64s/it]

💾 Saving progress at sample 16070

 97%|█████████▋| 16079/16500 [9:11:50<40:28,  5.77s/it]

💾 Saving progress at sample 16080

 98%|█████████▊| 16089/16500 [9:12:48<38:32,  5.63s/it]

💾 Saving progress at sample 16090

 98%|█████████▊| 16099/16500 [9:13:45<37:48,  5.66s/it]

💾 Saving progress at sample 16100

 98%|█████████▊| 16109/16500 [9:14:44<38:01,  5.83s/it]

💾 Saving progress at sample 16110

 98%|█████████▊| 16119/16500 [9:15:41<36:05,  5.68s/it]

💾 Saving progress at sample 16120

 98%|█████████▊| 16129/16500 [9:16:39<35:09,  5.69s/it]

💾 Saving progress at sample 16130

 98%|█████████▊| 16139/16500 [9:17:37<33:46,  5.61s/it]

💾 Saving progress at sample 16140

 98%|█████████▊| 16149/16500 [9:18:34<31:55,  5.46s/it]

💾 Saving progress at sample 16150

 98%|█████████▊| 16159/16500 [9:19:31<33:23,  5.88s/it]

💾 Saving progress at sample 16160

 98%|█████████▊| 16169/16500 [9:20:29<31:29,  5.71s/it]

💾 Saving progress at sample 16170

 98%|█████████▊| 16179/16500 [9:21:27<30:40,  5.73s/it]

💾 Saving progress at sample 16180

 98%|█████████▊| 16189/16500 [9:22:24<29:27,  5.68s/it]

💾 Saving progress at sample 16190

 98%|█████████▊| 16199/16500 [9:23:21<28:34,  5.69s/it]

💾 Saving progress at sample 16200

 98%|█████████▊| 16209/16500 [9:24:19<27:02,  5.58s/it]

💾 Saving progress at sample 16210

 98%|█████████▊| 16219/16500 [9:25:16<26:14,  5.60s/it]

💾 Saving progress at sample 16220

 98%|█████████▊| 16229/16500 [9:26:14<25:24,  5.62s/it]

💾 Saving progress at sample 16230

 98%|█████████▊| 16239/16500 [9:27:11<24:34,  5.65s/it]

💾 Saving progress at sample 16240

 98%|█████████▊| 16249/16500 [9:28:08<23:25,  5.60s/it]

💾 Saving progress at sample 16250

 99%|█████████▊| 16259/16500 [9:29:05<22:43,  5.66s/it]

💾 Saving progress at sample 16260

 99%|█████████▊| 16269/16500 [9:30:02<21:53,  5.69s/it]

💾 Saving progress at sample 16270

 99%|█████████▊| 16279/16500 [9:30:59<20:45,  5.64s/it]

💾 Saving progress at sample 16280

 99%|█████████▊| 16289/16500 [9:31:56<19:54,  5.66s/it]

💾 Saving progress at sample 16290

 99%|█████████▉| 16299/16500 [9:32:52<18:59,  5.67s/it]

💾 Saving progress at sample 16300

 99%|█████████▉| 16309/16500 [9:33:50<18:17,  5.74s/it]

💾 Saving progress at sample 16310

 99%|█████████▉| 16319/16500 [9:34:47<16:45,  5.56s/it]

💾 Saving progress at sample 16320

 99%|█████████▉| 16329/16500 [9:35:45<16:18,  5.72s/it]

💾 Saving progress at sample 16330

 99%|█████████▉| 16339/16500 [9:36:44<15:32,  5.79s/it]

💾 Saving progress at sample 16340

 99%|█████████▉| 16349/16500 [9:37:41<14:11,  5.64s/it]

💾 Saving progress at sample 16350

 99%|█████████▉| 16359/16500 [9:38:39<13:36,  5.79s/it]

💾 Saving progress at sample 16360

 99%|█████████▉| 16369/16500 [9:39:36<12:29,  5.72s/it]

💾 Saving progress at sample 16370

 99%|█████████▉| 16379/16500 [9:40:35<11:46,  5.84s/it]

💾 Saving progress at sample 16380

 99%|█████████▉| 16389/16500 [9:41:31<10:33,  5.71s/it]

💾 Saving progress at sample 16390

 99%|█████████▉| 16399/16500 [9:42:28<09:34,  5.69s/it]

💾 Saving progress at sample 16400

 99%|█████████▉| 16409/16500 [9:43:26<08:52,  5.86s/it]

💾 Saving progress at sample 16410

100%|█████████▉| 16419/16500 [9:44:22<07:43,  5.73s/it]

💾 Saving progress at sample 16420

100%|█████████▉| 16429/16500 [9:45:21<06:47,  5.74s/it]

💾 Saving progress at sample 16430

100%|█████████▉| 16439/16500 [9:46:19<05:41,  5.60s/it]

💾 Saving progress at sample 16440

100%|█████████▉| 16449/16500 [9:47:17<04:45,  5.60s/it]

💾 Saving progress at sample 16450

100%|█████████▉| 16459/16500 [9:48:14<03:51,  5.65s/it]

💾 Saving progress at sample 16460

100%|█████████▉| 16469/16500 [9:49:12<02:55,  5.66s/it]

💾 Saving progress at sample 16470

100%|█████████▉| 16479/16500 [9:50:09<01:58,  5.66s/it]

💾 Saving progress at sample 16480

100%|█████████▉| 16489/16500 [9:51:08<01:04,  5.89s/it]

💾 Saving progress at sample 16490

100%|█████████▉| 16499/16500 [9:52:05<00:05,  5.72s/it]

💾 Saving progress at sample 16500

100%|██████████| 16500/16500 [9:52:12<00:00,  2.15s/it]

✅ Final full CSV saved: /content/drive/MyDrive/QML/validation/stroke_quantum_features_partial_windowed.csv

In [ ]:
df_quantum.head()

,Quantum_Feature_0,Quantum_Feature_1,Quantum_Feature_2,Quantum_Feature_3,Quantum_Feature_4,Quantum_Feature_5,Quantum_Feature_6,Quantum_Feature_7,Quantum_Feature_8,Quantum_Feature_9,...,Quantum_Feature_23,Quantum_Feature_24,Quantum_Feature_25,Quantum_Feature_26,Quantum_Feature_27,Quantum_Feature_28,Quantum_Feature_29,Quantum_Feature_30,Quantum_Feature_31,Label
0,0.023990,0.004696,0.060631,0.136102,0.139476,0.027302,0.004812,0.010803,3.351136e-03,6.559673e-04,...,9.895821e-04,0.003190,0.016297,0.092455,0.041187,0.040191,0.205322,0.015903,0.007084,0
1,0.015243,0.000057,0.001407,0.229707,0.237190,0.000888,0.000059,0.009622,2.773385e-08,1.038693e-10,...,1.328477e-10,0.000046,0.012307,0.185451,0.001136,0.001100,0.293793,0.011918,0.000073,0
2,0.003019,0.000392,0.024669,0.177140,0.184072,0.023892,0.000407,0.002924,6.071456e-04,7.880574e-05,...,8.162856e-05,0.000393,0.003029,0.177707,0.024748,0.023816,0.183485,0.002915,0.000406,0
3,0.000080,0.000091,0.041820,0.057055,0.060036,0.068404,0.000095,0.000130,1.246212e-04,1.419906e-04,...,1.138858e-04,0.000119,0.000104,0.074852,0.054864,0.052140,0.045762,0.000099,0.000073,0
4,0.000002,0.000016,0.012224,0.004137,0.004425,0.040800,0.000018,0.000006,2.558194e-05,2.358799e-04,...,1.335295e-04,0.000031,0.000003,0.007816,0.023096,0.021594,0.002342,0.000003,0.000009,0